### ISSUE TITLE
Mon activité locales => contenu inconnu aux bataillons + bug sur les liens

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#100]
![capture d ecran de 2017-05-02 15-58-13](https://cloud.githubusercontent.com/assets/6576514/25620923/3af280ee-2f50-11e7-82d5-b1a12c18b697.png)
Bug lien :
#page.type.poi.id.58d12d5ddd0452fc1935bf5c

**Comment by Kgneo** [comment]
ce sont les POI les plus récent qu'on a dans la base de données
Dans "mon activité locale" on a : 
- les 10 prochains événements
- les 10 dernières annonces postées
- les 10 derniers POI publiés.
Et quand on est communecté, la recherche est scopée sur le département de la communexion (par défaut) donc on a résumé communecté de l'activité de mon département.

Dans la prochaine version : les user pourront paramétrer cette section pour définir leurs préférences

**Comment by clement59** [comment]
Mais je comprends pas, c'est pas "mon" activités du coup... c'est plutot "activité autour de moi"

**Comment by Kgneo** [comment]
j'ai changé le titre pour "activité territorial"
quand on est pas communecté, on propose la communexion + explications
quand on est communecté, on affiche le scope utilisé pour cette section : le département de l'utilisateur connecté (pour l'instant, paramétrable ensuite)
![Uploading activite-territoriale.png…]()

**Comment by clement59** [comment]
Super ma gueule ! La c'est compréhensible !
