### ISSUE TITLE
Photo d'annonce en photo de profil

### ISSUE THREAD

**Issue by vincentux** [pixelhumain/co2#1016]
Bonjour,
après avoir créé une annonce,
je me retrouve avec la photo de l'annonce en photo de profil... :/

**Comment by clement59** [comment]
Hello vincent,

Désolé pour le délai de réponse ! Peux tu me dire dans quel context es tu ... quel url ? quelle vue ? car je n'arrive pas à reproduire.

**Comment by vincentux** [comment]
> Désolé pour le délai de réponse !

Pas de souci... ;)

Mon problème est apparu créant une annonce de vélo de femme, ça me mettais la photo du vélo aussi en photo de profil. Ensuite j'ai créé l'annonce "[Vélo Homme VTT Decathlon Rockrider 320](https://www.communecter.org/#@vincentux.view.directory.dir.classifieds)" et ça me mettais encore le vélo femme en profil, j'ai donc supprimé l'annonce du vélo de femme mais j'ai toujours les photos mélangé dans l'annonce du VTT et on ne peut pas les retirer...

Enfin bref, je viens de réessayer et.... ça fonctionne :p

**Comment by clement59** [comment]
ok super !
Merci du retour !
