### ISSUE TITLE
Directory element - Up fonctionnalités et remarques

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#104]
1 - Pouvoir supprimer tout mes liens de mes directory
2 - Quand une personne est en cours d'invitation toujours j'avais plugguer une fonction qui permettait de le réinviter (intéressant pour nos user pending ?)
wdyt? @pixelhumain/dev

**Comment by clement59** [comment]
REMARQUE SYLVAIN SUR EVENT MAIS GENERIQUE POUR PROJET / EVENT
Affichage de la liste des invités en tant qu'organisateur de l'événement :
    Affichage du tootltip "En attente de confirmation" => au passage de la souris sur l'image aussi ça serait mieux. Actuellement c'est seulement sur le texte.
    A quoi sert le bouton link avec le tooltip "Participer"
    On n'avait pas parler à un moment donné de pouvoir relancer les invitations des gens qui n'ont pas répondu ?

**Comment by clement59** [comment]
Comment supprimer des membres d'une orga ? #170

**Comment by Kgneo** [comment]
on en est où la-dessus ?

**Comment by clement59** [comment]
nulle part l'ami

**Comment by Kgneo** [comment]
![capt2](https://cloud.githubusercontent.com/assets/7578166/26534906/5ced3ed0-4474-11e7-9dc8-fdadb813e56d.png)

![capt](https://cloud.githubusercontent.com/assets/7578166/26534907/618bf6ac-4474-11e7-93b0-41d272cfbfcb.png)

**Comment by Kgneo** [comment]
getAdminToolBar dans directory.js

**Comment by clement59** [comment]
yes mali !! Super Merci

**Comment by clement59** [comment]
1 - Suppression de mes liens dans mes directory (follows, orga, projet, event) => fait
![capture d ecran de 2017-05-30 17-03-52](https://cloud.githubusercontent.com/assets/6576514/26590320/7d2441f8-455a-11e7-9c72-73fc4f3d1bcd.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-05-30 22-12-58](https://cloud.githubusercontent.com/assets/6576514/26602873/29b0d592-4585-11e7-897b-8820cc95918f.png)
Bouton brancher sur les directorys... Je verais un truk un peu plus sexy comme un dropdown admin a partir d'un btn fa-cog à la place des btn de follow ou de link en haut à gauche de chaque fiche ou sur le hover de l'image en plus comme sur communecter
J'ai rajouté dans les datas un data.statusLink toutes les notions (toBevalidated, isAdminPending, isAdmin du contextData) donc y'a plus qu'à rajouter un tiot label pour chaque cas
toBeValidated => en attente de confirmation
isAdminPending => en attente de cof pour administrer
isAdmin => logo / couler / flag / text est admin de l'element

**Comment by clement59** [comment]
Plus bug design en xs et sm : 
![capture d ecran de 2017-05-30 21-48-07](https://cloud.githubusercontent.com/assets/6576514/26603212/504fb208-4586-11e7-870b-3599c9362013.png)

**Comment by clement59** [comment]
bon j'ai pris les devant:
1- Administrateur label => done
![capture d ecran de 2017-06-07 20-22-28](https://user-images.githubusercontent.com/6576514/26894582-17d608ac-4bbf-11e7-8d03-7ae9aed02002.png)
2- remove follow btn if location ==#page
3- design admin manage => done
![capture d ecran de 2017-06-07 20-04-52](https://user-images.githubusercontent.com/6576514/26894626-3b1b114a-4bbf-11e7-87a3-21a1d04cdca8.png)

**Comment by clement59** [comment]
personne pour test trop global mtn .. new issue si bug
