### ISSUE TITLE
Design cassé

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#1078]
En ce moment quand j'ouvre CO le matin j'ai ça : 
![screenshot_2018-10-30 reseau societal citoyen 1](https://user-images.githubusercontent.com/2474636/47705200-20aee180-dc26-11e8-9e11-f8e1403f14c4.png)

**Comment by clement59** [comment]
tu as toujours cette erreur avec la nouvelle version ??

**Comment by Drakone** [comment]
Nop
