### ISSUE TITLE
Design menu left Settings + DOCS broken

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#1081]
Le focus en rouge ne se met plus à jour sur les grandes section (My section / Confidentialité / Notifications)  [cf image == tout est focus]
![capture d ecran de 2018-11-03 09-44-44](https://user-images.githubusercontent.com/6576514/47950069-929c6900-df4d-11e8-98e8-d584b427205c.png)

Le design était mutualisé avec la doc => ya de la casse sur le hover
![capture d ecran de 2018-11-03 09-45-40](https://user-images.githubusercontent.com/6576514/47950073-a051ee80-df4d-11e8-99ba-404115aecea9.png)

Proposition: je préférais les hover en rouge sur les sous titres (moins multi color)

**Comment by clement59** [comment]
[] trad My account

[] Changer la documentation de changement de mot de passe dans le mail
![capture d ecran de 2018-11-03 09-51-11](https://user-images.githubusercontent.com/6576514/47950104-050d4900-df4e-11e8-9de6-eb3b6b0c1d7e.png)

**Comment by Drakone** [comment]
> Le focus en rouge ne se met plus à jour sur les grandes section (My section / Confidentialité / Notifications) [cf image == tout est focus]
> ![capture d ecran de 2018-11-03 09-44-44](https://user-images.githubusercontent.com/6576514/47950069-929c6900-df4d-11e8-98e8-d584b427205c.png)
> 
> Le design était mutualisé avec la doc => ya de la casse sur le hover
> ![capture d ecran de 2018-11-03 09-45-40](https://user-images.githubusercontent.com/6576514/47950073-a051ee80-df4d-11e8-99ba-404115aecea9.png)
> 
> Proposition: je préférais les hover en rouge sur les sous titres (moins multi color)

J'ai pas osé faire la remarque mais c'est pas ouf comme menu. Un jour je pourrais contribuer à ce genre de truc :p.

**Comment by RaphaelRIVIERE** [comment]
Moi non plus je suis pas fan du menu , si jamais tu peux faire un proposition de visuel.

On peut rapidement le changer

**Comment by Drakone** [comment]
OK pour ce bug.
