### ISSUE TITLE
Like de commentaire sur proposition

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#1115]
Le clique sur j'aime ne fait rien : 
![capture d ecran_2018-11-29_09-40-57](https://user-images.githubusercontent.com/2474636/49209545-11ed5300-f3bb-11e8-8439-5352201707f8.png)

**Comment by RaphaelRIVIERE** [comment]
#1119 meme bug a mon avis a voir plutot celui de #1119 plus de détail sur l'erreur

**Comment by clement59** [comment]
Moi j'ai réussi
