### ISSUE TITLE
Bug : ajout event : page perso 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#1131]
![capture d ecran de 2018-12-04 09-10-53](https://user-images.githubusercontent.com/8775448/49420382-96b5e380-f7a4-11e8-9478-b9d52939d998.png)

**Comment by clement59** [comment]
![capture d ecran de 2018-12-04 12-10-45](https://user-images.githubusercontent.com/6576514/49438125-abeb3c00-f7bd-11e8-98da-a511889bc9c4.png)
tiens @RaphaelRIVIERE je pense que tu seras le plus rapide sans faire de casse

**Comment by clement59** [comment]
Okay c'etait de l'ordre du $$ ;) Tu peux pomper ! @RaphaelRIVIERE
