### ISSUE TITLE
Communexion pas prise en compte dans le menu en haut à gauche

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#118]
![capture d ecran de 2017-05-02 21-05-47](https://cloud.githubusercontent.com/assets/6576514/25634511/39977382-2f7b-11e7-9078-8f45506f022b.png)

**Comment by clement59** [comment]
ok pour la mise à jour ... Mais tu mets pas le lien pour la ville de communexion ??

**Comment by Kgneo** [comment]
testé ok pour moi
je vais faire un autre raccourci pour trouver + facilement le bouton "communectez-vous"

**Comment by Kgneo** [comment]
![activite-territoriale](https://cloud.githubusercontent.com/assets/7578166/25802998/a40345c4-3440-11e7-88c7-da20e3893388.png)

quand on est pas communecté, la colonne "activité territoriale" affiche le bouton "Je me communecte"
avec un message d'explication.

Ce serait bien de rajouter un message sur la nouvelle interface de saisie d'addresse, pour rappeler le contexte, en l'occurence, montrer qu'on est en train de se communecter.

**Comment by clement59** [comment]
ok je close ici
