### ISSUE TITLE
quand je crée un element d'un element => news ne prend pas en compte la target

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#128]
L'auteur est l'organisation qui a créée l'orga
![capture d ecran de 2017-05-08 22-42-14](https://cloud.githubusercontent.com/assets/6576514/25824434/b8a12812-343f-11e7-9798-7357ee5b3335.png)

**Comment by clement59** [comment]
pour les activityStream il faut que tu prenne en compte la target et l'auteur

**Comment by clement59** [comment]
pour les activityStream il faut que tu prenne en compte la target et l'auteur

**Comment by Kgneo** [comment]
je dirais que ça devrait être fait au moment du save de l'activityStream ça, plutot qu'au moment de l'affichage, non ?

**Comment by Kgneo** [comment]
![activitystream](https://cloud.githubusercontent.com/assets/7578166/25946711/135eb152-3698-11e7-8a4b-17a1ce2f4a4c.png)
ou alors on dit que "author" est toujours un Citoyen (ya pas de authorType, authorId)
et effectivement on le fait à l'affichage pour rester cohérent dans la donnée
c'est ça ?

**Comment by Kgneo** [comment]
![projetactictystream](https://cloud.githubusercontent.com/assets/7578166/25948157/12fb88b0-369e-11e7-9dbe-75cf1915e6bf.png)
ok c'est bon pour l'auteur d'un element sur un autre element
par contre j'ai des soucis avec l'upload de l'image de profil (depuis dynForm et pareil depuis la page de l'element

**Comment by clement59** [comment]
ok j'ai rajouté les defaultImage par type et la bonne url aussi de l'auteur 
![capture d ecran de 2017-05-11 19-16-15](https://cloud.githubusercontent.com/assets/6576514/25962571/8d4223e2-367e-11e7-91d0-e24e8215e861.png)
Par contre pour l'auteur il ne faut pas toucher au newsTranslator... A changer asap

**Comment by Kgneo** [comment]
ok l'image est bien uploadé maintenant
mais j'ai toujours le pb de double id sur la redirection vers la page après le save
![doubleid2](https://cloud.githubusercontent.com/assets/7578166/26138260/842f99f8-3b13-11e7-90a1-07b3e3256e69.png)
