### ISSUE TITLE
Clique droit ne fonctionne plus 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#13]
Le clic droit ne fonctionne plus
![capture d ecran de 2017-04-10 14-54-1 8](https://cloud.githubusercontent.com/assets/8775448/24858505/a9a6d5f8-1dfd-11e7-98c4-332184ac8e50.png)

**Comment by clement59** [comment]
ok je ferme c'est corrigé @oceatoon a du passer par là
![capture d ecran de 2017-05-09 20-06-37](https://cloud.githubusercontent.com/assets/6576514/25865393/096e80f6-34f3-11e7-9b5c-8d1d69dff17b.png)
