### ISSUE TITLE
Url image /upload/communecter => prevoir redirect apache /upload/co2

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#144]

**Comment by oceatoon** [comment]
pourquoi on a le dossier /upload/co2 ? 
faut pas commencer a faire des chemins relatifs aux différents modules
ca doit etre en dure pour ne pas changer a chaque chgt de module 
un chemin unique /uploads/communecter et lé bon 
ou alors on peut aussi viré communecter , qui a peut etre porté a confusion

**Comment by oceatoon** [comment]
j'avais désactiver la création des chemins co2 mais je vois que ca a été réactivé ?
donc a présent on a 2 dossiers images pas top

**Comment by clement59** [comment]
Oui tu n'as pas du lire mais ca arrange fortement @aboire qui as tout mis avec co2... Donc on a viré pour co2 pour etre en accord avec l'appli mobile dans un premier temps

**Comment by clement59** [comment]
ok j'ai remis le path upload/communecter/ partout @pixelhumain/dev
