### ISSUE TITLE
double id sur la redirection vers element, apres create element

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#146]
je créé un nouveau projet, je valide, c'est enregistré, on me redirige vers cette url : 
![doubleid](https://cloud.githubusercontent.com/assets/7578166/25946206/cd7bb7fe-3695-11e7-92b6-0d9e1994b442.png)

**Comment by Kgneo** [comment]
je sais pas où est le code de la fonction save du dynForm, je trouve pas le moment où on redirige vers la nouvelle page.
Si quelqu'un sait où c'est !

**Comment by RaphaelRIVIERE** [comment]
Ok, je vais regarder ça :)

**Comment by RaphaelRIVIERE** [comment]
@clement tu peux t'en charger.

Quand on essaye d'ajouter un projet, on mets juste le nom et une image et le lien de redirection ressemble a ça : http://127.0.0.1/ph/co2#project.detail.id.nullnull

Si on ne pas d'image c'est bon

**Comment by clement59** [comment]
ok ma caille ! ça c'est cool ... marche avec et sans fineUploader good job l'artiste
