### ISSUE TITLE
Edit date project => ne pas mettre les heures et affichage en francais

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#151]
![capture d ecran de 2017-05-11 18-56-36](https://cloud.githubusercontent.com/assets/6576514/25961725/992fbfa0-367b-11e7-99d8-031d945c9561.png)

**Comment by RaphaelRIVIERE** [comment]
Je close ici , la traduction a déjà été signaler et j'ai remonter l'autre bug sur les heures ici : #117
