### ISSUE TITLE
Enlever la roue d'administration pour les contenus partagés

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#155]
![capture d ecran de 2017-05-11 19-35-29](https://cloud.githubusercontent.com/assets/6576514/25963272/03ba5c36-3681-11e7-85e5-192c39682fae.png)

**Comment by Kgneo** [comment]
hmm pour quelle raison ?
je m'étais posé la question mais je trouve que ça gène pas.

**Comment by clement59** [comment]
ca surchage .. comme le btn de link

**Comment by Kgneo** [comment]
oué mais vu qu'on a plus accès à la news directement, a partir du moment où la news est shared, on peut plus la signaler.
Ou alors il faut cliquer sur "un message" pour accéder à la page #page.type.news, pour pouvoir la signaler ? ou la supprimer ?
