### ISSUE TITLE
POI CREATION

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#161]
1- ne s'enregistre pas visiblement ..
2- redireger sur l'element createur du poi 
==> #page.type.$type.id.$id.view.directory.dir.poi

**Comment by Kgneo** [comment]
+ faire la page pour les POI : #page.type.poi.id...
@clement59 : est-ce que on peut réutiliser le template POI de notragora ?

**Comment by RaphaelRIVIERE** [comment]
J'ai crée la page  #page.type.poi.id.  ça passe dans le meme design que element, après a voir si on prend celui de notrAgora
J'suis suis jamais aller sur notreAgora

Bug redirection après avoir ajouter une image je crée une nouvelle issue , ici je le passe en test

**Comment by clement59** [comment]
issue duplique à creation poi !! hasta la vista
