### ISSUE TITLE
standalone news activitystream design broken

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#162]
![capture d ecran de 2017-05-12 19-49-20](https://cloud.githubusercontent.com/assets/6576514/26010173/2d647492-374c-11e7-807f-842c4d8a8f69.png)

**Comment by Kgneo** [comment]
comment t'es arrivé là ? ya pas de lien pour y accéder sur les activityStream

**Comment by clement59** [comment]
Les notifications like unlike comment coment d'un coment

**Comment by clement59** [comment]
et du coup bientot la notif de partage =P
