### ISSUE TITLE
Pop up partage => n'affiche pas le contenu à partager

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#167]
Cas 1: 
![capture d ecran de 2017-05-15 21-41-53](https://cloud.githubusercontent.com/assets/6576514/26075960/6f56db84-39b7-11e7-8cd7-c88509f97dfe.png)
le btn partage de la news envoie cette pop up
![capture d ecran de 2017-05-15 21-41-56](https://cloud.githubusercontent.com/assets/6576514/26075986/824c8ec8-39b7-11e7-9502-dfeeae7e56e8.png)
Cas 2:
Quand je clique sur le btn partage d'un element, il y a rien dedans

**Comment by Kgneo** [comment]
![share](https://cloud.githubusercontent.com/assets/7578166/26137346/4ac206c0-3b0d-11e7-97a2-751f65ce0343.png)
