### ISSUE TITLE
creer une annonce type besion  sur une orga > redirirgé vers poi

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#175]

**Comment by oceatoon** [comment]
cannot duplicate

**Comment by aboire** [comment]
pour toute les annonces quand je crée une annonce le lien de redir est vers poi http://dev.communecter.org/#page.type.citoyens.id.55ed9107e41d75a41a558524.view.directory.dir.classified

**Comment by clement59** [comment]
Yop yop c'est bon ! tester c'est bien sur annonces et classified correspond bien aux annonces
