### ISSUE TITLE
Recherche > Tags > hastags

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#19]
Imposible de mettre un hashtag dans  la barre de recherche
![capture d ecran de 2017-04-10 14-22-04](https://cloud.githubusercontent.com/assets/8775448/24857380/1963b3fc-1df9-11e7-93ee-19c11bf410ed.png)

**Comment by Kgneo** [comment]
bien vu !
c'est corrigé, on peut à nouveau mettre un # 
par contre ça provoque cette erreur : ;)
![hashtag_error](https://cloud.githubusercontent.com/assets/7578166/24968260/74827966-1ff8-11e7-9610-916a5644389b.png)

**Comment by RaphaelRIVIERE** [comment]
je peux la regarder si tu veux :)

**Comment by RaphaelRIVIERE** [comment]
C'est fais a testé

**Comment by Kgneo** [comment]
je valide
