### ISSUE TITLE
Si preference user directory hide/private, ne pas afficher les btn du menuLeft sur une page.citoyens !=  seesionUserId

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#190]
Enlever Follows Folowers Organization Project Event Annonces etc

**Comment by RaphaelRIVIERE** [comment]
Mec c'est déjà le cas, vérifie que ton user n'étais en superAdmin 
Sinon je veux bien ton cas exemple parce que j'arrive pas à reproduire

**Comment by clement59** [comment]
you're right
