### ISSUE TITLE
Error standAlone news => text undefined

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#199]
![capture d ecran de 2017-05-26 21-31-03](https://cloud.githubusercontent.com/assets/6576514/26509798/ad8ea570-425a-11e7-8988-4c5e902acf91.png)

**Comment by Kgneo** [comment]
![news textnug](https://cloud.githubusercontent.com/assets/7578166/26533640/9443406c-4467-11e7-802d-e98b274b02de.png)
