### ISSUE TITLE
Directory members des orga => object of citoyens with links instead of is private preferences.directory  

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#204]
![capture d ecran de 2017-05-30 17-27-54](https://cloud.githubusercontent.com/assets/6576514/26591249/56bc0354-455d-11e7-8e31-cc49f8be7918.png)

**Comment by RaphaelRIVIERE** [comment]
1) c'est quoi le nom de ton objet ? ta vu ça ici ?
![capture d ecran de 2017-05-31 09-21-49](https://cloud.githubusercontent.com/assets/8775448/26616857/b868067c-45e2-11e7-8057-7d5ef7e748b5.png)


2) Est-ce que tu est sur que l'user avec l'email "actionman@gmail.com" ne follows pas l'utilisateur ? Parce que si c'est le cas c'est normalement que tu vois ces données privées


Règles des préférences : 
- Si dans publicFields : tout le monde peut voir la donnée
- Si dans privateFields : Seul les personnes que je follows peuvent voir la donnée
- Si aucun des 2, cela signifie que c'est masqué : Seul l'utilisateur lui-même peut voir les données
