### ISSUE TITLE
Connection on welcome page - keypress tab from email input go to password input  

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#210]
Bug retour wrong connection:
![capture d ecran de 2017-06-01 22-55-00](https://cloud.githubusercontent.com/assets/6576514/26700424/9596bb70-471d-11e7-8447-9fc114aa71be.png)
Enhancement:
Ce serait cool quand on est sur le input mail et qu'on tape sur la touche "tab" qu'il mette le focus sur le input de password !!

**Comment by clement59** [comment]
bug fixer pour le design eyt vue sm done

**Comment by clement59** [comment]
pour le tab rien à faire j'arrive pas à changer le focus sur password input

**Comment by Kgneo** [comment]
ça c'est plus d'actu vu qu'il n'y a plus le form de connexion dans le menuTop
il y a le bouton "connexion" qui ouvre le form en modal
