### ISSUE TITLE
Modifier annonce pour un citoyen formulaire pas afficher

### ISSUE THREAD

**Issue by aboire** [pixelhumain/co2#213]
http://dev.communecter.org/#page.type.classified.id.5937bb0bdd0452c826226370

![capture du 2017-06-08 02 27 10](https://user-images.githubusercontent.com/1200525/26904546-7a2299ba-4bf3-11e7-99fd-ac4cd9eb06ec.png)
![capture du 2017-06-08 02 27 20](https://user-images.githubusercontent.com/1200525/26904550-7f8eb0f0-4bf3-11e7-8665-8bb73f761726.png)

**Comment by RaphaelRIVIERE** [comment]
Je viens de test , ça fonctionne
