### ISSUE TITLE
Bug : Devenir admin

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#216]
S'il il n'y a pas d'admin dans l'organisation et que je demande a etre admin, je suis en attente de validation au lieu d’être directement admin
![capture d ecran de 2017-06-08 10-46-12](https://user-images.githubusercontent.com/8775448/26915658-04d0ad74-4c38-11e7-97a3-2a8e40bc80fb.png)

**Comment by clement59** [comment]
Euh je n'ai pas réussi à reproduire l'ami
![capture d ecran de 2017-06-08 15-52-28](https://user-images.githubusercontent.com/6576514/26932007-8ad046b2-4c62-11e7-9a21-9fb60e485777.png)
![capture d ecran de 2017-06-08 15-51-19](https://user-images.githubusercontent.com/6576514/26932010-9184c078-4c62-11e7-941c-d8d725fa070a.png)

**Comment by clement59** [comment]
j'ai checker avec directory en privatefields mais rien à faire, tjrs pas le bug !!
