### ISSUE TITLE
Gallerie photos liens "voir tout" "albums" "profils" affiche la même chose

### ISSUE THREAD

**Issue by aboire** [pixelhumain/co2#220]
pour Gallerie photos les liens "voir tout" "albums" "profils" affiche la même chose quand on clique dessus,
en faite ça disparait et ça revient direct
http://dev.communecter.org/#page.type.citoyens.id.55ed9107e41d75a41a558524.view.gallery

**Comment by clement59** [comment]
Bon je viens de me casser les dents 1h ... Probleme du mixitup !!
Il prend bien compte les classes à filtrer et boom il remet tout !!!
I need help @pixelhumain/dev

**Comment by oceatoon** [comment]
@clement59  tu as pu faire la creation des addPhotos contentKey/"+uploadObj.contentKey ???

**Comment by clement59** [comment]
moi ca marche

**Comment by Kgneo** [comment]
one shot ! 

![luck](https://user-images.githubusercontent.com/7578166/27464454-511ad1cc-5819-11e7-8d2a-284e6221c219.jpeg)

**Comment by clement59** [comment]
hell yeah !!
