### ISSUE TITLE
annonce formulaire update divers bugs

### ISSUE THREAD

**Issue by aboire** [pixelhumain/co2#224]
1) l'adresse n'est pas affiché
![capture du 2017-06-14 08 00 12](https://user-images.githubusercontent.com/1200525/27114854-97adb922-50d7-11e7-9daa-315e78ad8634.png)
2) l'update ne ce fait pas car ça part en GET

**Comment by aboire** [comment]
pour 1 c'est toujour la,
pour le 2 ça passe plus par GET
parcontre il y a un autre soucis il faut appuyer 2 fois sur valider pour que ça passe car il y a une erreur 500
POST http://dev.communecter.org/co2/search/globalautocomplete 500 (Internal Server Error) qui bloque la suite de l'envoie je pense

**Comment by RaphaelRIVIERE** [comment]
L'erreur 500 corrigé.

**Comment by clement59** [comment]
c'est good jack !!
