### ISSUE TITLE
Probleme affichage directory admin

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#241]
![capture d ecran de 2017-06-16 16-12-59](https://user-images.githubusercontent.com/6576514/27230208-c78db402-52ae-11e7-852f-631c44f3d795.png)

**Comment by Kgneo** [comment]
![admin](https://user-images.githubusercontent.com/7578166/27266327-ede9bed6-54eb-11e7-8590-9d740d224973.png)
