### ISSUE TITLE
Problem end date - creation event

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#249]
![capture d ecran de 2017-06-20 15-28-24](https://user-images.githubusercontent.com/6576514/27335560-2d020aa6-55cd-11e7-8466-3fe7e9cc01c0.png)
Ici mon event parent est toute la journée le 21 et le 22... Or je peux pas un event fils le 22 qui se finit à 18:00 car il me dit que ça doit etre le 22 à 00:00

**Comment by clement59** [comment]
create update affichage des dates !!! Boum bada bim !!!

**Comment by RaphaelRIVIERE** [comment]
Maintenant les dates sont plus sous le bon format
![capture d ecran de 2017-06-26 11-54-05](https://user-images.githubusercontent.com/8775448/27529609-364a8690-5a66-11e7-99cf-9c885919f0be.png)

**Comment by RaphaelRIVIERE** [comment]
J'ai trouver d'ou vient le problèmes , ça vient de ce commit : https://github.com/pixelhumain/co2/commit/c24a28833ff7a31602f11f96ea44f35414897e9f 

Du coup il te sert a quoi la variable outputFormat ?  Dans quel cas ta besoin d'un tel format ? @clement59

**Comment by RaphaelRIVIERE** [comment]
J'ai fais une correction. parce que il y avait aussi le jquery.validator qui a sauté a cause du format de date : "YYYY-MM-DD". 
J'ai pas réussie a reproduire le bug initiale. Faudrait qu'on se pose un soir @clement59  si jamais tu la toujours

**Comment by Danzal974** [comment]
C'est bon pour moi.

**Comment by Drakone** [comment]
OK
