### ISSUE TITLE
person.detail > ajout d'une news 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#25]
j'ai pu clicker sur le btn envoyer 
ca m'a fait plusieurs envoie de news 
mais ya pas mes images dedans
![image](https://cloud.githubusercontent.com/assets/192076/24958551/b98bac4c-1fa0-11e7-9f95-0d84c58db02f.png)

et au refresh 
ca bloque , je peux plus ajouter de news avec cette erreur 
ReferenceError: liveScopeType is not defined

**Comment by RaphaelRIVIERE** [comment]
pour la cas où, on ajoute une new avec image et qu'on refresh, la new existe bien avec l'image et on peut crée d'autres news

Par contre quand j'ajoute un new, la partie pour ajouter une new ne se réinitialise pas 
![capture d ecran de 2017-04-21 11-42-21](https://cloud.githubusercontent.com/assets/8775448/25267979/081963de-2688-11e7-8ac5-f1faeff783ad.png)

Du coup , si je l'enleve l'image depuis cette partie "ajout d'une new"
![capture d ecran de 2017-04-21 11-42-28](https://cloud.githubusercontent.com/assets/8775448/25268001/1948ed8c-2688-11e7-8fcc-1ef44b894c82.png)

J'ai plus l'image dans ma new

Image quand je viens juste de crée la new 
![capture d ecran de 2017-04-21 11-42-14](https://cloud.githubusercontent.com/assets/8775448/25268077/6b6387bc-2688-11e7-9ee9-810881c108ec.png)

Image quand je supprime depuis "l'ajout dune new" et que je refresh 
![capture d ecran de 2017-04-21 11-43-08](https://cloud.githubusercontent.com/assets/8775448/25268099/7f31e36a-2688-11e7-9d4a-f60be0521152.png)

Du coup, je pense qu'il faudrait réinitialiser cette parti quand on ajout une new 

![capture d ecran de 2017-04-21 11-49-14](https://cloud.githubusercontent.com/assets/8775448/25268121/97d4a56a-2688-11e7-9f02-7369b54291b2.png)

**Comment by RaphaelRIVIERE** [comment]
Et aussi bloquer le bouton Envoyer , une fois qu'on a cliquer dessus, sinon on peut enregistrer plusieurs fois la même new

**Comment by clement59** [comment]
Ok c'est push ! A tester

**Comment by RaphaelRIVIERE** [comment]
Yessaï, c'est bon :)
