### ISSUE TITLE
Bug sur la page d'accueil

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#255]
Dans la section en amélioration continue. 

On peut faire une click droit sur le bouton "Développeur", ca switch sur la carto et on ne peut plus fermer cette carto.

Il y a également une 404 sur le bouton "Association Open Atlas" et "Projet Communecter"

![capture d ecran de 2017-06-30 11-16-12](https://user-images.githubusercontent.com/22808909/27725188-3a9dc04a-5d86-11e7-8cb3-490d2d586485.png)

**Comment by clement59** [comment]
Ok j'ai changer l'appel pour developpeur en utilisant la fonction directement.
Pour les liens, openAtlas et communecter ce sont des variables params (donc normal que sur dev ça pete), j'ai mis les bonnes variables dans paramsconfig et je les ai rajouté dans co2.org avec les bash à passer !!
