### ISSUE TITLE
404 dans Annonces > Partager

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#256]
On a une 404 quand on clique sur le nom d'un élément pour avoir le détail (ici "tessssstfff")
On a aussi une 404 quand on clique sur l'adresse de l'élément partagé.

![capture d ecran de 2017-06-30 11-28-47](https://user-images.githubusercontent.com/22808909/27725479-98cf8b84-5d87-11e7-9625-c7074838c08c.png)

**Comment by GrondinDam** [comment]
J'ai l'impression que le bug est présent dans tout le module Annonces

**Comment by clement59** [comment]
Je n'arrive pas à le reproduire @oceatoon tu as fais un hotfix ?! Sinon je le close

**Comment by clement59** [comment]
@GrondinDam le bug est peut etre autre part comme sur #276

**Comment by RaphaelRIVIERE** [comment]
Corriger
