### ISSUE TITLE
Footer un peu intrusif 

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#258]
Le footer s'affiche tout le temps quand on n'est pas connecté et il prend beaucoup de place. 

PS : @oceatoon à insisté pour que j'en fasse une issue xD`

**Comment by clement59** [comment]
add cookie and add help in loading page
![capture d ecran de 2017-06-30 19-22-07](https://user-images.githubusercontent.com/6576514/27747169-5d49a408-5dca-11e7-8402-97f18f12ec4d.png)
