### ISSUE TITLE
Bug Paramètres de confidentialités

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#259]
![confidentiality](https://user-images.githubusercontent.com/7578166/27726943-271485b2-5dc8-11e7-9aa0-0de214ec5dfb.png)

les modif ne sont pas enregistrée apparement
je met l'addresse en privé, mais quand je recharge la page, elle est à nouveau en Public

**Comment by RaphaelRIVIERE** [comment]
Le bug vient du fais que tu est superadmin et que tu modif les parametre de quelqu'un d'autre.
On a le message le "Vos paramètres ont bien été modifier" alors qu'en faite non

**Comment by clement59** [comment]
Pour moi tout est bon !!
