### ISSUE TITLE
Ajout d'une adresse d'un élément en n'étant pas connecté

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#260]
Quand on est pas connecté et qu'on va dans le "A propos" d'un élément Open Edition on peut toujours voir le bouton "Ajouter une adresse principale" et ouvrir la carto pour ajouter une adresse (cependant les modifications ne sont pas en compte)

![capture d ecran de 2017-06-30 12-36-17](https://user-images.githubusercontent.com/22808909/27727847-3e6fb68c-5d91-11e7-82e8-37bfb48bb170.png)

**Comment by clement59** [comment]
No comment !
