### ISSUE TITLE
Bouton carto visible dans les urls et bouton carto ne fonctionne pas pour collection

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#261]
Sur la page d'un élément,

Le bouton carto est visible lorsque quand l'on veut voir les urls de l'élément (une url ne peut pas être geolocalisé).

![capture d ecran de 2017-06-30 13-13-12](https://user-images.githubusercontent.com/22808909/27729254-3358b6e0-5d96-11e7-85c9-1d67a54a0a84.png)

ET ... 

La carto n'affiche aucun élément quand on est dans les collections d'un élément

**Comment by Kgneo** [comment]
to test !

**Comment by RaphaelRIVIERE** [comment]
c'est bon
