### ISSUE TITLE
Filtres dans le module Annonces

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#263]
Dans la page d'accueil du module annonce, le filtre par défaut est "A vendre", cependant quand je filtre avec autre chose comme "Partager" ou "Donner" je n'arrive plus a remettre le filtre "A vendre" autrement qu'en actualisant la page.

![capture d ecran de 2017-06-30 13-42-13](https://user-images.githubusercontent.com/22808909/27730589-d14bc29e-5d9a-11e7-89ef-9b4ce1ec6d79.png)

**Comment by clement59** [comment]
ok bon !!
