### ISSUE TITLE
Main text search dans le fil d'actualité

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#264]
Dans le module live 

Filtrage des news avec la main search bar non fonctionnel. 

Quand je tape un mot dans la main search bar et que j'appuie sur entrée, j'ai un alert qui pop. 
Le bug ne survient que la première fois où je le fais. 

![capture d ecran de 2017-06-30 13-56-57](https://user-images.githubusercontent.com/22808909/27730946-3907e3d0-5d9c-11e7-8e3f-563bc30a5b64.png)

**Comment by clement59** [comment]
ok searchbar cahcé !
