### ISSUE TITLE
Element non géolocalisé

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#268]
Sur la page d'un élément qui a ses paramètres de confidentialité  "Tout public", son adresse est bien bien visible 

![capture d ecran de 2017-06-30 15-03-32](https://user-images.githubusercontent.com/22808909/27733124-7abd306a-5da5-11e7-9f15-f07ece263fcc.png)

MAIS quand je switch sur la carto ca me dit que l'élément n'est pas géolocalisé 

![capture d ecran de 2017-06-30 15-06-13](https://user-images.githubusercontent.com/22808909/27733168-b65cb30c-5da5-11e7-84c3-07918b00f904.png)

**Comment by RaphaelRIVIERE** [comment]
Corriger

**Comment by clement59** [comment]
Ok pour celui là @RaphaelRIVIERE !!!
Par contre, mais exemple de pikachui, qui 4 abonnemnts, 10 orga, 5 event, 2 et qui a ces préférences

**Comment by RaphaelRIVIERE** [comment]
ça fonctionne bien en local ou dev 
![capture d ecran de 2017-07-04 10-19-17](https://user-images.githubusercontent.com/8775448/27817477-4f3f83fc-60a2-11e7-93c1-035648e5f375.png)

Faudrait voir quel manipulation tu a fais pour supprimer tous les éléments de la carte

**Comment by clement59** [comment]
![capture d ecran de 2017-07-04 15-03-30](https://user-images.githubusercontent.com/6576514/27831229-088f4c1c-60ca-11e7-902a-9cb4fa39fc46.png)
Jai juste cette erreur en arrivant sur son profil (fil d'actus) et je clique sur la carto

**Comment by RaphaelRIVIERE** [comment]
Ok je l'ai eu dans la journée se bug, c'est corriger

**Comment by Kgneo** [comment]
to test ?

**Comment by RaphaelRIVIERE** [comment]
Yep

**Comment by Drakone** [comment]
OK
