### ISSUE TITLE
Le logo sur Map : erreur 404

### ISSUE THREAD

**Issue by Danzal974** [pixelhumain/co2#270]
Quand je suis sur la map (passant par search), le logo CO2 envoi vers page-top et un 404 aparaît.
![capture d ecran de 2017-06-30 15-09-10](https://user-images.githubusercontent.com/19874163/27733282-56e9d962-5da6-11e7-80a8-4ae67887cfb9.png)

**Comment by clement59** [comment]
J'ai mis la redrect sur la page d'accueil
