### ISSUE TITLE
Le champ de recherche dans map

### ISSUE THREAD

**Issue by Danzal974** [pixelhumain/co2#272]
Quand je cherche avec le champ de recherche sur la map, rien ne s'affiche.
![capture d ecran de 2017-06-30 15-13-52](https://user-images.githubusercontent.com/19874163/27733411-1675eca8-5da7-11e7-9151-ff2d0fbda47a.png)

Dans la console on a : 
![capture d ecran de 2017-06-30 15-17-51](https://user-images.githubusercontent.com/19874163/27733476-618aee0a-5da7-11e7-9a56-8a6ab2071ddf.png)

**Comment by clement59** [comment]
Pour moi c'est bon ...

**Comment by Danzal974** [comment]
Le bug se produit quand on vient de "search" avant de passer sur map. Il y a un autre bug pour la recherche dans map (en venant d'une autre page : issue  #279

**Comment by Kgneo** [comment]
il faut appuyer sur "entrée", ou cliquer sur le bouton pour lancer la recherche

**Comment by clement59** [comment]
à partir du search:
1 - quand je switch sur la carte "le filtre tous" ne proposent que les citoyens et je n'ai pas les projets 
![capture d ecran de 2017-07-04 07-42-54](https://user-images.githubusercontent.com/6576514/27816590-c6e478ce-608c-11e7-966e-162f62261901.png)
2 - Et je suis focus sur le filtre "organisations" et que je recherche en haut dans le menu clément (citoyen), il ne me trouve pas
3 - le premier chargement affiche 0/0 résultat

**Comment by clement59** [comment]
Ma carto
![capture d ecran de 2017-07-04 07-50-41](https://user-images.githubusercontent.com/6576514/27816715-8c2e6022-608d-11e7-896f-27be3788b88b.png)
Pour ce search:
![capture d ecran de 2017-07-04 07-50-53](https://user-images.githubusercontent.com/6576514/27816732-a26dd8fe-608d-11e7-9806-5706ee9d4665.png)

**Comment by clement59** [comment]
Peut-etre que le scénario et le screen avec l'erreur vont aider:
1- Je suis sur une carto (celle citoyen dans ce cas)
2 - Je fais une recherche (Pikachu) => Il me trouve deux résultats !
3 - J'essaie d'enlever la recherche et ensuite je clique sur le filtre "tous"  et là, la carto est plantée !
![capture d ecran de 2017-07-04 07-58-47](https://user-images.githubusercontent.com/6576514/27816956-f6c72a8a-608e-11e7-88b6-c37d9f6d225e.png)

**Comment by Danzal974** [comment]
Maintenant ok pour moi.
