### ISSUE TITLE
Accueil btn valider 

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#273]
Quand je m'inscrit et que je rempli tous les champs sauf le champ "Répéter le mot de passe". 

![capture d ecran de 2017-06-30 15-52-03](https://user-images.githubusercontent.com/22808909/27734532-3cd73636-5dac-11e7-9713-42bc5fc03c47.png)

Le compte est quand même créer (ou du moins la modal suivante s'affiche) 

![capture d ecran de 2017-06-30 15-46-03](https://user-images.githubusercontent.com/22808909/27734585-7f254384-5dac-11e7-956c-71ed9caab162.png)

**Comment by clement59** [comment]
j'ai ajouter les regle mais ca bug encore sur le btn ladda ... Il envoie qd mm au ctk meme si les rules ne sont pas respecté bref je te laisse finir @RaphaelRIVIERE

**Comment by RaphaelRIVIERE** [comment]
Vu que vous avez enlever la modal, les modification qu'il fallais c'est juste enlever les -welcome dans les id et name

C'est fais

**Comment by RaphaelRIVIERE** [comment]
@Kgneo tu pourrais checker le bug avec le btn valider sur la page d'accueil

![capture d ecran de 2017-07-03 13-31-53](https://user-images.githubusercontent.com/8775448/27786907-15f09428-5ff4-11e7-9ea7-19caf5942277.png)

![capture d ecran de 2017-07-03 13-32-02](https://user-images.githubusercontent.com/8775448/27786918-1bb38956-5ff4-11e7-9997-00ed56600a2d.png)

Impossible de recliquer dessus

**Comment by clement59** [comment]
allez boum tout est corrigé -- btn validate (ladda ne marche po) et msg agree et passwordAgain required !!!
BoumShaKa

**Comment by RaphaelRIVIERE** [comment]
It's perfect
