### ISSUE TITLE
Bug lors de la création d'une news 

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#274]
Le bouton de communexion est grisé est il affiche se Communecter avec undefined 
![capture d ecran de 2017-06-30 16-36-18](https://user-images.githubusercontent.com/22808909/27735785-567c3270-5db2-11e7-855b-02ceeaeda56e.png)

Quand on clique dessus (oui il est grisé mais on peut cliquer dessus) ca affiche ça : 

![capture d ecran de 2017-06-30 16-37-40](https://user-images.githubusercontent.com/22808909/27735816-75d20528-5db2-11e7-85b5-bf82312bc513.png)

Dés lors que je fais ça, quand je vais valider la news, celle ci ne se crée pas 

Autre chose quand on clique sur la cible 

![capture d ecran de 2017-06-30 16-45-07](https://user-images.githubusercontent.com/22808909/27736068-8d786c5c-5db3-11e7-88a4-06c6f5bfd9b7.png)

Dans le DynForm qui s'ouvre, je n'arrive pas à faire fermer le select à moins de choisir un scope

![capture d ecran de 2017-06-30 16-44-09](https://user-images.githubusercontent.com/22808909/27736087-a5a0457a-5db3-11e7-896e-4d368328da76.png)

Le scope s'affiche comme ça dans la news : 

![capture d ecran de 2017-06-30 16-47-42](https://user-images.githubusercontent.com/22808909/27736136-e9048c36-5db3-11e7-81ae-b58f95870ac9.png)

Pareil si je choisi un scope, et que je valide la news elle ne se crée pas.

**Comment by ckiltolier** [comment]
Coucou @GrondinDam !

Je me pose la question juste, es-tu sur le chat de communecter : https://chat.lescommuns.org/channel/communecter_accueil ?

A+ !

**Comment by GrondinDam** [comment]
Hey salut Rémi, Oui je suis sur le chat ! En faite c'est moi damien_reunion :)

**Comment by ckiltolier** [comment]
Oh d'accord :)

**Comment by clement59** [comment]
Ok 1 et 2 corrigé + autres bugs sur les unable btns quand communexionActivated in save action 
3 pas encore @Kgneo une idée ?
4 - design de l'ajout ... Chez moi c'est bon l'ami !

**Comment by clement59** [comment]
ok 3 push
