### ISSUE TITLE
Commenter une news

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#276]
Quand j'essaie de commenter une news le champ texte est tout petit et ce que je tape ne s'affiche pas à l'écran 

![capture d ecran de 2017-06-30 17-00-47](https://user-images.githubusercontent.com/22808909/27736594-e235a9a6-5db5-11e7-9c67-45aee28320c7.png)

De manière général je ne peux pas commenter tout simplement .
Et enfin quand je clique autre part les input text ne disparaissent (cf capture suivante) 

![capture d ecran de 2017-06-30 17-02-51](https://user-images.githubusercontent.com/22808909/27736681-46306bd0-5db6-11e7-81ba-6e1aae638f74.png)

**Comment by clement59** [comment]
J'ai corriger un pb de size de la div parent des comment ....
Mais là j'ai l'impression que tout simplement tu as une erreur js qui à a voir avec le directory.js. So ouvre ton inspecteur et regarde dans la console la vrai erreur qu'il te péte

**Comment by RaphaelRIVIERE** [comment]
Je viens testé c'est good :)
