### ISSUE TITLE
Recherche et resultat furtif sur la map (depuis page citoyen)

### ISSUE THREAD

**Issue by Danzal974** [pixelhumain/co2#279]
La recherche sur map donne un résultat furtif qui disparaît quelques secondes après. 
J'étais sur une page citoyen avant switcher pour la map.

https://drive.google.com/open?id=0B71nY67nqhcGd2p2UEk4d21yY2c

**Comment by clement59** [comment]
good for me!

**Comment by Danzal974** [comment]
Ok pour moi aussi.
