### ISSUE TITLE
Btn "Nous Contacter"

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#28]
Ne fonctionne pas

**Comment by RaphaelRIVIERE** [comment]
Reste a faire : 
- Implémenter Le formulaire pour envoyer un mail
- Design des btn supprimer et modifier

**Comment by clement59** [comment]
On peut supprimer les contacts en mode déconnecter

**Comment by RaphaelRIVIERE** [comment]
C'est corriger 
Coté ctk ça passe par Element::updateField il y a déjà une vérification.

**Comment by clement59** [comment]
biene
