### ISSUE TITLE
Dans la liste "en ce moment" page d'accueil

### ISSUE THREAD

**Issue by Danzal974** [pixelhumain/co2#280]
Un élément cliqué ne revient plus dans la liste après disparition de la div "previewLocalActivity".
https://drive.google.com/open?id=0B71nY67nqhcGZUgxbkI1ZWkzTGc

Il y a le même comportement dans la div ".col-nowList". (sur ma page perso colonne de droite)

**Comment by clement59** [comment]
C'est peu fait exprès ? @Kgneo

**Comment by Kgneo** [comment]
oui c'est fait expres que ça disparaisse, mais ça devrait revenir après le hide de la preview
