### ISSUE TITLE
Ajouter urls et contact sont present pour des elements non open edition

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#282]
(ou je suis bien évident ni membre ni admin)
![capture d ecran de 2017-07-04 21-32-21](https://user-images.githubusercontent.com/6576514/27841302-5d45fb80-6100-11e7-8b57-6589aa26ce7b.png)

**Comment by RaphaelRIVIERE** [comment]
Ok , je prend

**Comment by clement59** [comment]
waterclosed
