### ISSUE TITLE
Probleme image : galerie

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#284]
![capture d ecran de 2017-07-10 16-04-12](https://user-images.githubusercontent.com/8775448/28017259-78d09a3a-6589-11e7-8c72-275995e9e7e0.png)

http://qa.communecter.org/#page.type.events.id.592b1fd540bb4e6c15d84ccf.view.gallery

1 ) Bannière écrasée
2 ) Pas d'image de profil 
3 ) les photos de gallerie ne chargent pas 
4 ) gallerie -> galerie

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-07-10 16-54-21](https://user-images.githubusercontent.com/8775448/28019018-7c10bf20-6590-11e7-9525-76198c807b4c.png)

**Comment by RaphaelRIVIERE** [comment]
la 4 c'est bon

**Comment by clement59** [comment]
allez hasta luego
