### ISSUE TITLE
Probleme mis a jour POI

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#286]
![capture d ecran de 2017-07-10 16-09-40](https://user-images.githubusercontent.com/8775448/28017434-43d6ea72-658a-11e7-876f-e01d3b3ad2e5.png)

 http://qa.communecter.org/#page.type.poi.id.587249ad40bb4e6070ccd1e4

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-07-10 16-51-06](https://user-images.githubusercontent.com/8775448/28018889-008d0412-6590-11e7-9b0f-38c08284ca22.png)

**Comment by Drakone** [comment]
OK pour moi.
