### ISSUE TITLE
Probleme post sur live 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#287]
![capture d ecran de 2017-07-10 16-13-40](https://user-images.githubusercontent.com/8775448/28017540-cd2cc47c-658a-11e7-823b-3b3da3e1effd.png)

@Drakone si tu peux détailler un peu plus s'il te plait :)

**Comment by clement59** [comment]
Effectivement, il n'y a pas eut le bash de @Kgneo pour les news

**Comment by clement59** [comment]
db.news.find({}).forEach(function(doc){
if(typeof doc.targetIsAuthor !="undefined" && doc.targetIsAuthor == "true"){
db.news.update({"_id":doc._id},{'$set':
{'sharedBy':[
{'id': doc.target.id,
'type':doc.target.type,
'updated': doc.created
}]
}})
}else{
db.news.update({"_id":doc._id},{'$set':
{'sharedBy':[
{'id': doc.author,
'type':'citoyens',
'updated': doc.created
}]
}})
}
})
