### ISSUE TITLE
quand on copie une url communecter dans le fil d'actu , le preview  n'est pas top 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#288]
1 - better preview 
2 - pré remplir les datas  (ex : tags, photo, titre )
3 - le lien clickable 

![image](https://user-images.githubusercontent.com/192076/28256370-ccfa8e42-6ad2-11e7-8758-4febf7950c73.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-09-06 18-37-13](https://user-images.githubusercontent.com/6576514/30126422-34e510ea-933c-11e7-8add-491bb7ed1fe1.png)
Ca c'est mieux ? 
Maintenant la prochaine étape est qu'il renvoit directe l'element si c'est dans notre site ... 
Et la suivante, est-ce qu'il faudrait pas modifier les metas suivant le context (cf screen) ?
![capture d ecran de 2017-09-06 19-48-58](https://user-images.githubusercontent.com/6576514/30126540-802fa93e-933c-11e7-93c8-06d7e8176f64.png)
Mais par exemple celle ci ne seront pas interprété par un extract comme facebook, ou autre site web ... A moins de mettre les bonnes métas des le début dans le fichier mainSearch ...
wdyt? @pixelhumain/dev

**Comment by clement59** [comment]
![capture d ecran de 2017-09-07 01-27-27](https://user-images.githubusercontent.com/6576514/30139009-bbc98094-936b-11e7-822e-58b4630d76c8.png) Et voilou le deuxième point ...

**Comment by clement59** [comment]
et le troisieme avec linkify qui vient concurencer sulugify ;)
