### ISSUE TITLE
Batch , Image Communecter vers Co2

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#29]
Faire une batch ou autre qui va mettre tout les images qui se trouve dans Communecter et les mettre dans Co2

**Comment by oceatoon** [comment]
on a préféré garder le dossier communecter pour les images
pourquoi tu veux faire ce batch , c'est pour quel contexte
a terme on se disait que ce serait bien de garder le module communecter

**Comment by RaphaelRIVIERE** [comment]
ah OK je savais pas :) Du coup je close
