### ISSUE TITLE
Edit Profil : type d'orga pas rempli

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#292]
![image](https://user-images.githubusercontent.com/192076/28257862-d8bdef92-6ade-11e7-960a-67ac7c16b658.png)
quand on Edit l'orga n'est pas rempli 
![image](https://user-images.githubusercontent.com/192076/28257889-01c0a2fe-6adf-11e7-997e-2b9b6791503f.png)

**Comment by RaphaelRIVIERE** [comment]
Je close ici, il y a doublon #316
