### ISSUE TITLE
Bugs poi project - Map accueil project

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#297]
1 - Je ne peux modifier les Poi dont je ne suis pas le créateur mais qui appartiennent à un projet que j'admin
2 - Tricky bug css - les p0i se chevauchent et j'ai une bande de la carte à la fin
![capture d ecran de 2017-07-17 15-12-37](https://user-images.githubusercontent.com/6576514/28269482-812b5f0c-6b02-11e7-9b19-154791e8dc98.png)
![capture d ecran de 2017-07-17 15-12-34](https://user-images.githubusercontent.com/6576514/28269490-8a4bde7c-6b02-11e7-902d-e8e37c6116d2.png)
3 - [Amélioration] les pois ne sont pas chargé dans la carte général d'un project/orga
https://www.communecter.org/#page.type.projects.id.58c72b1d40bb4e005792bed4

**Comment by oceatoon** [comment]
@Kgneo tu pourras regarder le #3 stp

**Comment by oceatoon** [comment]
#1 OK

**Comment by oceatoon** [comment]
point 2 je n'arrive pas reproduire 
point 3 il y a un btn expret pour voir les POI

**Comment by clement59** [comment]
ok a voir dans le #311
