### ISSUE TITLE
ShareElement

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#3]
Pouvoir partager n'importe quel Elements sur mon fil d'actu via une News, qui sera visible par tout mes follower

Par exemple partager un événement depuis la page Agenda.
![share](https://cloud.githubusercontent.com/assets/7578166/24783621/27c3f608-1b99-11e7-9bbf-9677e9fdc910.png)

**Comment by clement59** [comment]
Pour le share element, il reste la petite modif sur le share en mode privée à enlever et tu peux close :)

**Comment by clement59** [comment]
Ok man well done et tester !! Je ferme celle là qui est générale !
