### ISSUE TITLE
DynForm : input " mail, téléphone, fax "

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#307]
Envoyer par mail par un utilisateur : 

![capture d ecran de 2017-07-18 08-52-18](https://user-images.githubusercontent.com/8775448/28301279-80631616-6b96-11e7-9150-c6fe8d002d7c.png)

**Comment by oceatoon** [comment]
je ne comprends pas où il a trouvé ce champs ??

**Comment by RaphaelRIVIERE** [comment]
Ca était testé dans l'ancienne version. Je close
