### ISSUE TITLE
Amélioration : URL

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#308]
- Ajouter description 
- Reconnaitre lorsqu'il sagit de lien wiki , github, umap etc ...
- Reload la page interne , pas global lorsque l'on ajout ou modifi une url 
- Ajouter des tags
- Filtrer en fonction du type d'url

**Comment by clement59** [comment]
allez zougoulou !!! Fioooooou
![capture d ecran de 2017-09-04 17-37-40](https://user-images.githubusercontent.com/6576514/30032739-de2ff65c-9197-11e7-87f5-180238b3cfb7.png)
