### ISSUE TITLE
Finir la partie gallerie photo

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#31]
je pige pas le fonctionnement des boutons "voir tout" "album" et "profil"
je ne sais pas comment créer un album
![gallery](https://cloud.githubusercontent.com/assets/7578166/25002696/7c5d4680-2097-11e7-8e28-603cbf96dd1c.png)

**Comment by oceatoon** [comment]
je ne me souvient plus 
il me semblait avoir fait marcher les albums dans ph-dori 
faut que je regarde a nouveau

**Comment by oceatoon** [comment]
j'ai relu le code de communecter.js 
j'ai fait des albums, relatif a des poi, affichant une modal quand un POI avait plus d'une photo, 
en faisant juste 
```
album.show('<?php echo (string)$p["_id"] ?>','poi')
```

**Comment by Kgneo** [comment]
@clement59 : en l'état est-ce que le module de galerie gère les albums ?
est-ce qu'on peut créer plusieurs album sur un meme element ?
ou est-ce que toutes les photos sont ensemble ?

**Comment by clement59** [comment]
Pour le pod gallerie il ne gére pas du tout les albums...
Enfaite album est l'attribut donné à la base pour les images venant des news.
Maintenant qu'on a des collections, il faudrait utiliser le dev de tib et les plugguer aux collections

**Comment by clement59** [comment]
Plouf
