### ISSUE TITLE
Editer profil 

### ISSUE THREAD

**Issue by seballot** [pixelhumain/co2#312]
Dans réseaux sociaux : la mise à jour du lien vers la page github ne fonctionne pas, ça tourne en boucle
 
![capture d'écran](https://user-images.githubusercontent.com/17404254/28363280-3c8d4c00-6c80-11e7-8b70-4811b31c468c.png)

Dans informations générales, la date de naissance ne fonctionne pas. On peut en entrer une et suavegarder, mais quand on recharge la page elle est différente

![image](https://user-images.githubusercontent.com/17404254/28363389-ad98ba1a-6c80-11e7-9ba6-3a9719af63be.png)

**Comment by RaphaelRIVIERE** [comment]
Corrigé , ça va etre prochainement mis en prod
