### ISSUE TITLE
poi - clé en francais

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#317]
![capture d ecran de 2017-07-19 19-30-45](https://user-images.githubusercontent.com/6576514/28380827-fc630032-6cb8-11e7-8ade-28f1c21d48af.png)
"RessourceFinanciere"=>"financialRessource"
"RessourceMaterielle"=>"materialRessource"
"ficheBlanche"=>"whitePage" ?

Pour le moment, les clés sont affichées mais je le prends dans mon chantier trad !! donc de souchis de ce côté

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-07-20 10-15-57](https://user-images.githubusercontent.com/8775448/28403143-71dd8e88-6d34-11e7-8f72-9d991cac73b7.png)
Mec quand tu test vérifie que tu n'est pas sur ta branch translateCO21

ta du oublié quelque part les traductions

**Comment by clement59** [comment]
Je close mais y'a un bash à prévoir la MAJ en prod avec le translate car les clés sont pas bonnes
