### ISSUE TITLE
Init les élements dans la map

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#32]
Ré-iniatiliser les éléments présent dans la map quand on change de page 

Exemple : 
- Aller sur la page search
- Aller sur une Organisation (pas de membres si possible)
- Aller sur la carte ( On voit tout les éléments présent dans la page search )

**Comment by RaphaelRIVIERE** [comment]
Sur une page element, les liens sont charger quand on clic sur la map

**Comment by clement59** [comment]
Je remets en bug :)

**Comment by RaphaelRIVIERE** [comment]
Reste a faire : 
- Quand on est sur la carto , et qu'on enlève la vue de de la map, ne pas récuperer les links
- Icon des links ne s'affiche pas sur la map, si l'élément n'a pas d'image

**Comment by clement59** [comment]
Pour moi icon c'est bon et les liens me paraissent good ! Je te laisse fermer l'issue mon tit @RaphaelRIVIERE

**Comment by clement59** [comment]
allez boom
