### ISSUE TITLE
Connexion : "﻿Se souvenir de moi" semble ne pas avoir d'effet

### ISSUE THREAD

**Issue by funkycram** [pixelhumain/co2#326]
Lorsque je me connecte et que je coche "﻿Se souvenir de moi", si j'ai fermé l'onglet mais que je ne me suis pas déconnecté, le lendemain il faut que je me reconnecte.
Par contre, si je ne coche pas "﻿Se souvenir de moi", si je quitte le navigateur et que je le relance, je reste connecté.
A voir ce qui se pratique, mais il me semble qu'il faudrait une durée de sessions très longue (comme sur gmail par exemple) si on a coché "se souvenir de moi" et une déconnexion à la fermeture de l'onglet ou du navigateur si on ne l'a pas coché pour les cas où un utilisateur n'est pas sur son ordi personnel.
Je cocherai "se souvenir de moi" par défaut aussi pour faciliter la vie des utilisateurs. #

**Comment by marc-fun** [comment]
Précision : lorsque je coche  "﻿Se souvenir de moi", même sans fermer le navigateur (juste l'onglet) je dois me reconnecter plusieurs fois par jour

**Comment by oceatoon** [comment]
yes marc ya un truc qui a sauter
j'ai regarder rapidement ce WE

**Comment by funkycram** [comment]
Up ! C'est très pénible de devoir se reconnecter plusieurs fois dans la journée...

**Comment by funkycram** [comment]
@oceatoon

**Comment by clement59** [comment]
Duplicate #408
