### ISSUE TITLE
Nombre de résultats

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#327]
![capture d ecran_2017-07-25_15-41-03](https://user-images.githubusercontent.com/2474636/28570599-e7c65804-714f-11e7-87d9-7a2b301303d3.png)
14 résultats alors que 7 sont affichés dans le module Agenda en mode déconnecter. Alors que connecté il est bien affiché "7 résultats".

EDIT : Ah bah non ça passe à 14 quand je suis connecté, en faite c'est aléatoire.

**Comment by RaphaelRIVIERE** [comment]
On dirais c'est corrigés. A redéclarer si ça se reproduit
