### ISSUE TITLE
Lorsqu'on modifie un contact, il se duplique

### ISSUE THREAD

**Issue by marc-fun** [pixelhumain/co2#334]
Exemple : https://www.communecter.org/#page.type.projects.id.596d0ef440bb4e83147b23e6.view.contacts

Si on clique sur le crayon pour le modifier, ça crée un nouveau contact.

**Comment by RaphaelRIVIERE** [comment]
Seulement pour le premier 
@oceatoon faudrait je vois ça avec toi. 
C'est parce que l'index du contact est égal a 0 et il ne veux pas s'ajouter dans l'input index .

**Comment by marc-fun** [comment]
Sur QA ça fonctionne maintenant, super !
