### ISSUE TITLE
Journal : impossible de supprimer un message et impossible de supprimer un lien dans un message

### ISSUE THREAD

**Issue by marc-fun** [pixelhumain/co2#335]
Exemple : https://www.communecter.org/#page.type.projects.id.596d0ef440bb4e83147b23e6

Si je supprime un message (petit engrenage -> supprimer), ça supprime, mais si je recharge la page il y est encore.

Dans un message, j'ai un lien qui m'a créé un aperçu cliquable. Si je modifie le lien dans le texte, le lien ne se modifie pas dans l'aperçu et surtout, si je supprime l'aperçu, il réapparait après enregistrement des modifications

**Comment by clement59** [comment]
Fixé pour la suppression

Pour le lien, le comportement que tu décris m'a l'air normal (si apercu alors pas de reload de l'apercu par contre si on le supprime on check si l'url a changée pour relancer l'extract process ... Après il se comporte bizarement par moment, mais d'autres issues sont ouvertes dessus

**Comment by marc-fun** [comment]
Sur QA ça fonctionne pas encore :
http://qa.communecter.org/#page.type.projects.id.593d470040bb4e5007e2080c
![image](https://user-images.githubusercontent.com/23310825/29003334-1eb3f858-7ab5-11e7-9909-8bbf65f45b2a.png)

**Comment by clement59** [comment]
nop c'est en local ! j'ai pas les droits pour up ... prochaine MAJ

**Comment by clement59** [comment]
Mais la c'est différent ... tu essaie de supprimer le projet ???

**Comment by marc-fun** [comment]
Oui, c'est ça, j'essaye de modifier le projet qui s'appelle Test32.
Si tu veux je te mets admin pour que tu testes

**Comment by clement59** [comment]
Mais c'est encore un autre bug du coup ... Cette issue porte sur les news d'un projet (corrigé mais pas encore MAJ) 
Par contre imprim ecran montre autre chose qui sont une autre issue non ?

**Comment by marc-fun** [comment]
Ou là là, j'ai confondu en effet, je parlais de ce bug.... https://github.com/pixelhumain/co2/issues/321
Super pour la correction alors, je testerai quand t'auras pushé sur QA

**Comment by marc-fun** [comment]
Je vais supprimer ces commentaires qui ne sont pas utiles du coup pour ce sujet, désolé !!

**Comment by clement59** [comment]
yes top ! Merci @marc-fun

**Comment by clement59** [comment]
je close c'est good
