### ISSUE TITLE
Lien non-clickable dans les news

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#337]
![linkunlclikable](https://user-images.githubusercontent.com/7578166/28702798-315df230-73ab-11e7-9b71-59ebe9326ed3.png)

**Comment by clement59** [comment]
wi c'est bizarre normalement il y a le résultat de l'extract url qui donne le lien en dessous. Mais du coup c'est pas prévu que les liens du text deviennent des urls ... amélioration close ?

**Comment by clement59** [comment]
que fait-on ?

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-11-16 16-02-46](https://user-images.githubusercontent.com/8775448/32892547-9e4c8012-cae7-11e7-8c48-72231ae30295.png)

Corriger
