### ISSUE TITLE
Ville ne s'affiche pas 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#341]
![2017-07-31](https://user-images.githubusercontent.com/30291819/28779799-b5c79e26-7604-11e7-83f2-33f8172ad5ab.png)

En cliquant sur Marseille je suis directement redirigée sur la page d'accueil, rien ne s'affiche

**Comment by clement59** [comment]
c'est possible, les view cities remarchent ??
En voyant cela j'enleverrais aussi les cities de la topBar !!

**Comment by Kgneo** [comment]
effectivement, c'est un oubli de ma part.
non on a pas rétabli les pages City, mais on a mis les cities dans la recherche pour pouvoir changer sa communexion facilement.

Donc je dirais qu'il faut faire comme dans #search : quand on clique sur la commune, le système se communecte sur cette commune, et si on est pas sur #search on est redirigé vers #search pour avoir un aperçu des acteurs locaux

![communes](https://user-images.githubusercontent.com/7578166/28853451-66ba7762-777c-11e7-9d0c-1f34c856a40a.png)

**Comment by Kgneo** [comment]
walou c'est corrigé. A tester

**Comment by corail974** [comment]
thanks !
