### ISSUE TITLE
Tous les titres des dynforms update sont en font-blanc donc pas visible

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#343]
![capture d ecran de 2017-08-01 20-21-06](https://user-images.githubusercontent.com/6576514/28840374-104e20ac-76f7-11e7-9ef8-c72d8e0ff8f3.png)

**Comment by Kgneo** [comment]
j'en ai plein le cul de régler 4 fois le même bug.
je dis pas ça pour quelqu'un en particulier, c'est juste une remarque globale ;)
mais ça commence à me souler, ça fait au moins 15 bug que je règle plusieurs fois. Pourquoi ça saute ? pourquoi ça revient ? Mystère...

**Comment by Kgneo** [comment]
je perd un temps fou à refaire plusieurs fois les mêmes fix,
c'est pas possible, il doit y avoir un Gitkraken ou un SourceTree mal configuré...

**Comment by Kgneo** [comment]
c'est comme le design des addresses dans les dynForm, j'ai passé au moins 3h dessus pour faire ça : 
![addresses](https://user-images.githubusercontent.com/7578166/28854552-8c2a899a-7783-11e7-9b86-910b7795a681.png)

Je le reste 2 jours plus tard et je retrouve ça : 
![address](https://user-images.githubusercontent.com/7578166/28854563-9de1f9e8-7783-11e7-8ab3-2870e2640a92.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-08-02 15-09-20](https://user-images.githubusercontent.com/6576514/28875110-a945cf1a-7794-11e7-8589-e1eef604b5eb.png)

**Comment by clement59** [comment]
fait ! 
1- Addresse remis avec ton design @Kgneo et tout cela fixé par la même occasion #348
2- Titre du update fait (par contre cela n'était pas fait)

**Comment by Kgneo** [comment]
wahou :) top cool !
mais alors c'est quoi qui avait fait sauté le design des adresses ?

il doit quand même y avoir un pb de config git quelque part, parce que ça arrive souvent.
