### ISSUE TITLE
Bug BretagneTelecom carto

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#345]
![capture d ecran de 2017-08-01 21-22-12](https://user-images.githubusercontent.com/6576514/28842850-8499643c-76ff-11e7-9180-2fd85ebe7e47.png)
http://www.territoires-collaboratifs.net/cartographie-vtc/
url utilisée:
https://www.communecter.org/?network=BretagneTelecom

**Comment by clement59** [comment]
le problème est sur chrome l'ami @RaphaelRIVIERE

**Comment by clement59** [comment]
![capture d ecran de 2017-08-02 17-45-13](https://user-images.githubusercontent.com/6576514/28882061-6274d778-77aa-11e7-8043-f3a76c585e49.png)
Carto provence zero west 404

**Comment by clement59** [comment]
Meme erreur que la premiere, sur chrome: pour paris zero waste:
https://www.communecter.org/network/default/index?src=https://gist.githubusercontent.com/Simroubriff/3e14264620d9e59e874d44d306314679/raw/947d0b7f3b048a8534f3f67fc0bb1a66ff6027dd/ZD-Paris

**Comment by clement59** [comment]
terre et avenir pareil !
http://terreetavenir.com/la-carte-du-zero-dechet/

**Comment by RaphaelRIVIERE** [comment]
Je close, toute les carte fonctionnes

**Comment by clement59** [comment]
Moi j'ai toujours l'erreur en prod ... Je sais pas si tu as up (je ré-ouvres au cas où !
![capture d ecran de 2017-09-06 16-28-46](https://user-images.githubusercontent.com/6576514/30117474-9b21d4e0-9320-11e7-928a-d908b2476784.png)

**Comment by RaphaelRIVIERE** [comment]
Faut tu me montre comment tu arrive a avoir cette page

**Comment by clement59** [comment]
Je prend ce lien et je le copie colle ... https://www.communecter.org/network/default/index?src=https://gist.githubusercontent.com/Simroubriff/3e14264620d9e59e874d44d306314679/raw/947d0b7f3b048a8534f3f67fc0bb1a66ff6027dd/ZD-Paris
Et ça donne ça !
![capture d ecran de 2017-09-07 14-16-18](https://user-images.githubusercontent.com/6576514/30162946-3de667de-93d7-11e7-85da-68f7081f6831.png)

**Comment by RaphaelRIVIERE** [comment]
Ok , bah il y a un gros probleme , parce que sur firefox comme sur chrome moi quand je copie colle le lien j'ai ça 
![capture d ecran de 2017-09-08 09-04-17](https://user-images.githubusercontent.com/8775448/30196861-d32d8870-9474-11e7-86ea-7016d9979588.png)

Chrome : Version 59.0.3071.115 (Build officiel) (64 bits)

et la tiens @clement59  ?

**Comment by clement59** [comment]
héhé hé Version 57.0.2987.98 (64-bit)

**Comment by RaphaelRIVIERE** [comment]
Yes , c'est bien ça , c'est du a la version. J'ai testé sur l'ordi de Sitti qui a la version 57 et elle a le probleme.

Je vais me l'installer et réglé tous ça :)
