### ISSUE TITLE
close dynForm non visible en sm

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#350]
![capture d ecran de 2017-08-02 22-06-48](https://user-images.githubusercontent.com/6576514/28892642-f9a74aee-77ce-11e7-8ff8-082ad60ce3ad.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-11-16 17-10-17](https://user-images.githubusercontent.com/8775448/32895424-150a996a-caf1-11e7-82e7-1942deeeea4c.png)
