### ISSUE TITLE
New : publication pour une commune

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#351]
![capture d ecran de 2017-08-03 14-50-35](https://user-images.githubusercontent.com/8775448/28920613-96bf897e-7863-11e7-8b9d-829d65e3a3a1.png)

@clement59 si ta besoin de plus d'indication faut voir avec @Drakone 

@Drakone tu pourrais peut etre décrire les étapes que tu a fais pour arriver au bug

**Comment by clement59** [comment]
Il n'y pas de bug ... Le message a bien son label privé ! Seul toi @Drakone et les admin/membre de la ville voit ce post !!

**Comment by Drakone** [comment]
Autant pour moi.
