### ISSUE TITLE
Dates évènements

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#353]
La sélection de dates bug parfois.
Difficile à expliquer alors je l'ai pris en vidéo : https://cloud.communecter.org/index.php/s/ey66rAJeaJkFLp1/download

**Comment by Drakone** [comment]
En réactualisant ça refonctionne, difficile de vous dire exactement dans quel contexte ça bug et quand ça bug pas...

**Comment by RaphaelRIVIERE** [comment]
@Drakone tu a toujours se bug ?

**Comment by Drakone** [comment]
Ça ne me l'a jamais refait.
