### ISSUE TITLE
Partage d'événement : affiche " invalid date" 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#362]
![2017-08-08 2](https://user-images.githubusercontent.com/30291819/29070527-0dd2dc48-7c40-11e7-9a61-dad305308141.png)
![2017-08-08 1](https://user-images.githubusercontent.com/30291819/29070528-0e4187a6-7c40-11e7-9e6f-44c5bd97d6db.png)

J'ai ouvert l'événement, il s'affiche correctement mais au moment de vouloir le partager c'est affiché "Invalid date" la date ne s'affiche donc pas quand on veut partager. 
Et pourquoi il nous parle anglais d'un coup c'lui là?

**Comment by Drakone** [comment]
Invalid date le retour
![capture d ecran_2017-11-28_12-28-39](https://user-images.githubusercontent.com/2474636/33309546-d8fa9222-d437-11e7-8d6c-708f5fb00517.png)
![capture d ecran_2017-11-28_12-27-07](https://user-images.githubusercontent.com/2474636/33309506-c197f796-d437-11e7-9589-93b529febc49.png)

**Comment by Kgneo** [comment]
lé buen for mi
