### ISSUE TITLE
Confirmation suppression

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#363]
Il n'y a pas le bouton pour confirmer.
![capture d ecran_2017-08-09_09-14-04](https://user-images.githubusercontent.com/2474636/29106006-6299aace-7ce3-11e7-9f2e-d656bb710777.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-11-16 17-15-37](https://user-images.githubusercontent.com/8775448/32895644-ce068b22-caf1-11e7-80d7-07e975f8346e.png)
