### ISSUE TITLE
Annonce et lieux : mettre le bouton valider inactif

### ISSUE THREAD

**Issue by Danzal974** [pixelhumain/co2#37]
Bonjour, lorsqu'on créer une annonce ou un lieux, le bouton "Valider" est actif pour les premières questions : 
"De quel type d'annonce s'agit-il?" ou "De quel type de Lieu s'agit-il ?".
Si on clic dessus, on obtient une annonce ou un lieux vide dans la base de donnée mongodb.
![capture d ecran de 2017-04-17 10-45-26](https://cloud.githubusercontent.com/assets/19874163/25081564/1f7af544-235c-11e7-9111-89f4dd5d8934.png)

**Comment by oceatoon** [comment]
to test
