### ISSUE TITLE
Le lien dans le mail envoyé pour autoriser un contributeur ne fonctionne pas

### ISSUE THREAD

**Issue by marc-fun** [pixelhumain/co2#372]
Voir le lien dans le mail ci-joint qui mène à une page 404.
[mail.pdf](https://github.com/pixelhumain/co2/files/1219841/mail.pdf)

De plus, il y a écrit "RDV sur la liste des membres". Or il faudrait écrire plutôt "RDV sur la liste des Contributeurs". Et lorsque j'ai la fiche avec écrit "en attente de validation", je n'ai pas de bouton pour le valider :
![image](https://user-images.githubusercontent.com/23310825/29241444-6a979c9c-7f7a-11e7-8d20-34f4a9f041c3.png)

**Comment by clement59** [comment]
ok fixé @marc-fun !
@RaphaelRIVIERE du coup j'ai trouvé pourquoi ça plantait sur le $dir undefined qui ne passait pas dans le mail AskToBecome ... La variable checkée était de type controler et non collection ;)
Le label est amélioré aussi ...
Pour le dernier, en passant ta souris sur l'image ou sur le btn avec la roue crantée, tu devrais voir apparaître les boutons de validation : 
![capture d ecran de 2017-08-14 22-42-21](https://user-images.githubusercontent.com/6576514/29291419-d33c66ae-8143-11e7-9308-54acd46f73e0.png)

**Comment by marc-fun** [comment]
OK, super ! C'est pas encore visible chez moi mais j'imagine que ça va venir
![image](https://user-images.githubusercontent.com/23310825/29293911-32a9dbd6-814d-11e7-9b80-eb711d9a5fd3.png)

**Comment by clement59** [comment]
Mince !! Je t'ai fait la démo sur la prod communecter.org ... donc là y'a un bug spécifique à ton compte !
Tu es sur quel navigateur ? tu es bien connecté ?

**Comment by marc-fun** [comment]
Firefox 54 sur mac, connecté avec le compte "marc".
Je te joins une capture la console si ça peut t'aider.
Si besoin je t'envoi en mp sur le chat mon mot de passe.
![image](https://user-images.githubusercontent.com/23310825/29294801-78f24e9e-8151-11e7-9c5d-7fb1363d206d.png)

**Comment by clement59** [comment]
hello Marc, Console pas d'erreur et firefox pour moi ça marche !
Donc oui je veux en mp ton mp ca m'aidera à y voir plus clair

**Comment by clement59** [comment]
dingue mm erreur que sur le delete des news projects ... A devenir dingo !!
Merci à toi !!!

**Comment by clement59** [comment]
Ok corriger !! j'ai refait la demande pour que tu check le mail !!
Je te laisse me faire un retour avant de fermer l'issue ... Ou si tu as les droits pour fermer à toi l'honneur !

**Comment by clement59** [comment]
Oups j'ai annulé le lien avec ton compte ... Je t'ai réinvité à devenir admin du coup ;)
Et voici le mail corrigé avec le bon lien qui marche !!
![capture d ecran de 2017-08-18 14-54-50](https://user-images.githubusercontent.com/6576514/29460004-709b5204-8426-11e7-8438-dc6c9f00c922.png)
