### ISSUE TITLE
Modifier ou ajouter un numéro de téléphone 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#376]
Lorsqu'une organisation est déjà référencé et que l'on veut modifier le numéro de téléphone ou l'ajouter, il y a un chargement infini et au final ça ne s'enregistre pas

**Comment by RaphaelRIVIERE** [comment]
@corail974  Tu aurez un exemple a me donnée ? 
Pour que je test , s'il te plait

**Comment by corail974** [comment]
Non ben apparemment c'est bon ça remarche :) 
Tes fautes d'orthographes m'ont presque manquées 😍

**Comment by corail974** [comment]
https://www.communecter.org/#page.type.organizations.id.555eba4ec655675cdd65bf18.view.detail
