### ISSUE TITLE
Modifier publication

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#377]
J'ai un chargement infini et un message d'erreur lorsque je tente de modifier ma publication.

![capture d ecran_2017-08-22_11-20-22](https://user-images.githubusercontent.com/2474636/29553569-b8076818-872c-11e7-93bc-ca11a265eafa.png)
![capture d ecran_2017-08-22_11-20-09](https://user-images.githubusercontent.com/2474636/29553568-b8050a00-872c-11e7-832a-ef1811405e9b.png)

**Comment by Drakone** [comment]
Ça fonctionne sur dev, merci 😃 .

**Comment by Drakone** [comment]
Je peux supprimer mais pas modifier (testé aussi sur QA).
![capture d ecran_2018-01-09_15-37-17](https://user-images.githubusercontent.com/2474636/34719286-a8d48b42-f553-11e7-9477-d0aea7aedfff.png)

**Comment by clement59** [comment]
Il me semble que c'est normal pour les partages ... @Kgneo  wdyt ??

**Comment by Drakone** [comment]
C'est normal que ce ne soit pas possible ? Ou c'est normal que ce n'est pas encore possible ?

Pouvoir modifier le message que l'on a partagé (que ce soit un partage ou non) c'est bien pratique :).

**Comment by clement59** [comment]
Non non dans tous les cas c'est un bug !
Je voulais savoir si c'était déjà dév ou pas ! C'est pour ça que j'ai pinger @Kgneo ;)

**Comment by Drakone** [comment]
Dans l'attente d'une réponse je remet le label bug car ce n'est toujours pas possible de modifier le message sur un partage.
