### ISSUE TITLE
Evénement passé s'efface

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#378]
Dans l'agenda quand un événement est passé il ne s'affiche plus. C'est dommage parce qu'on ne peut pas suivre la continuité de certains événements ni voir l'historique de tout ce qui s'est passé dans un même mois. 
![2017-08-22](https://user-images.githubusercontent.com/30291819/29555178-171fa352-8722-11e7-9ad8-94dc6c53e02f.png)

**Comment by clement59** [comment]
+1 ! Et j'ajouterais que dans les directory il y a tous les événements passés affichés... Je les mettrais cachés comme dans le floopdrawer. wdyt ?

**Comment by clement59** [comment]
Je pense que @Kgneo a geré cela ... @Kgneo ?
