### ISSUE TITLE
bug addMultiMember - undefined mapUrl.data.load

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#379]
if(typeof(mapUrl) != "undefined"){
					if(typeof(mapUrl.detail.load) != "undefined" && mapUrl.detail.load)
						mapUrl.detail.load = false;
					if(typeof(mapUrl.directory.load) != "undefined" && mapUrl.directory.load)
						mapUrl.directory.load = false;
				}
![capture d ecran de 2017-08-25 15-22-11](https://user-images.githubusercontent.com/6576514/29715825-34c819be-89a9-11e7-9741-b811805e3b0f.png)

**Comment by RaphaelRIVIERE** [comment]
@clement59 comment tu a eu le bug j'arrive pas a reproduire ?
