### ISSUE TITLE
Spécificité sur les Villes

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#38]
@clement59  ta voulus dire quoi par spécificité ?

J'ai corrigé un bug sur CO2.php, c'était dans le cas où  la requête  retourne qu'une ville.

Question : dans ton where tu ne mets que le code postal, pourquoi pas l'insee aussi ? Ligne 57

**Comment by RaphaelRIVIERE** [comment]
Autre question, la fonction getCommunexionCookies dans CO2.php elle est utiliser ou ?

**Comment by clement59** [comment]
merci pour la correction d'une ville !!
J'ai enlever l'insee de la requete que j'utilise après pour un use case:
exemple cp=62223 > tu as cinq villes avec des insee differents et je voulais récupérer leur nom pour creer le tooltip quand tu cliques sur 62223 (level de communexion 2 > supérieur a l'insee), comme ça on sait à quoi correspond le niveau 2 avec le cp.
Apres c'est uniquement pour le tooltip donc on peut le remettre ? wdyt ? @pixelhumain/dev

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-05-01 22-15-01](https://cloud.githubusercontent.com/assets/8775448/25588989/c1e9fd56-2ebb-11e7-8e9d-88ac4401ce4d.png)
Manque le level 2

**Comment by clement59** [comment]
ok a tester @RaphaelRIVIERE
