### ISSUE TITLE
Impossible de supprimer une orga si l'admin ne l'a pas mise en open data 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#382]
https://www.communecter.org/#page.type.organizations.id.55efe85ce41d756f52558517

Avec l'exemple de La ferme lou-cachet qui est déjà référencée plusieurs fois mais incompléte. J'ai choisi la plus détaillée pour la compléter, j'ai pu supprimer les doublons mais pas celui crée par Mireille. Comment faire?

**Comment by clement59** [comment]
Duplicate #326
