### ISSUE TITLE
Bug dans les url de certains mail

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#393]
url du mail : #person.detail.id.98789798787987
url à utiliser : #page.type.citoyens.985987987987

![bug_url_mail](https://user-images.githubusercontent.com/7578166/30008393-edb58024-916a-11e7-9cd4-cf34c1b86f60.png)

**Comment by clement59** [comment]
@oceatoon Normalement la redirection devrait marcher ?

**Comment by Drakone** [comment]
Je sais pas si c'est qui est relevé ici mais je pense qu'on devrait mettre le nom affiché à la place du pseudo (ici ckiltolier).

**Comment by clement59** [comment]
c'est le nom ;)

**Comment by RaphaelRIVIERE** [comment]
J'ai ne trouve plus d'url de ce type dans les mails #person.detail

Il me sembles que @clement59 a déjà fais le taf , je close
