### ISSUE TITLE
Mail : [Communecter] Un citoyen demande à devenir contributeur 

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#394]
![capture d ecran 2017-09-04 a 11 46 42](https://user-images.githubusercontent.com/29157378/30016810-abeee20a-9167-11e7-96ea-ca1b2e71cf87.png)

Le premier lien (sa fiche profil) ne fonctionne pas, il renvoie à la page d'accueil Communecter

**Comment by clement59** [comment]
Merci pour le retour ! Je ferme ... dupliqué dans #393
