### ISSUE TITLE
Bug sur organisation

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#398]
![capture d ecran de 2017-09-06 09-14-26](https://user-images.githubusercontent.com/8775448/30095458-de87d9d8-92e3-11e7-82b6-c8112e9b8347.png)

Il faudrait une image ou plus d'explication pour voir ou se situe le problème

**Comment by Pierre-Magnin** [comment]
Depuis ma page perso, je clic sur organisation cela lance l'URL 
https://www.communecter.org/#page.type.citoyens.id.55ee6932e41d75356255851b.view.directory.dir.organizations

qui échoue en erreur 404

hope it help

**Comment by Pierre-Magnin** [comment]
cette fonction marchait antérieurement

**Comment by clement59** [comment]
@Pierre-Magnin peux-tu mettre tes directory en public pour qu'on retrouve l'erreur ?
![capture d ecran de 2017-09-06 17-54-47](https://user-images.githubusercontent.com/6576514/30121642-89658312-932c-11e7-84fc-7586520bdf06.png)
![capture d ecran de 2017-09-06 17-54-42](https://user-images.githubusercontent.com/6576514/30121643-8967145c-932c-11e7-93a2-948f02d05205.png)

**Comment by Pierre-Magnin** [comment]
done

**Comment by clement59** [comment]
Super ! Maintenant on l'a 
![capture d ecran de 2017-09-06 18-47-39](https://user-images.githubusercontent.com/6576514/30123951-f373a0a2-9333-11e7-90e7-5777d95ee9e2.png)

**Comment by clement59** [comment]
Merci @Pierre-Magnin tu viens de mettre le doigt sur un bug d'import d'orga sans type !
On régle ça au plus vite !

**Comment by RaphaelRIVIERE** [comment]
C'est réglé, il me reste a remettre le bon type pour chaque orga , mais tu peux de nouveau accèder a la fiche de l'organisation
