### ISSUE TITLE
Scopes Live

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#4]
Terminer la publication de news sur la page Live 
=> gérer les scopes

**Comment by clement59** [comment]
A tester !!! AINSI QUE LES SCOPES en général filtre dans les autres vues

**Comment by clement59** [comment]
a retest à la fin de push partage/refactor news

**Comment by clement59** [comment]
manque encore l'interprétation des target activtyStream mais j'ai ouvert un commite sur ça je close
