### ISSUE TITLE
Invitation par mail

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#402]
Le "Envoi en cours" tourne à l'infini.

![capture d ecran_2017-09-06_15-39-21](https://user-images.githubusercontent.com/2474636/30110035-aea8296c-9319-11e7-8c41-cea1223bc873.png)

**Comment by Drakone** [comment]
Lorsque j'essai d'inviter.

![capture d ecran_2017-11-29_11-25-23](https://user-images.githubusercontent.com/2474636/33363162-9af260ce-d4f8-11e7-8b43-c5dc1a80bd27.png)

**Comment by Drakone** [comment]
Lorsque je test sur prod ça ne fonctionne pas.

![capture d ecran_2017-11-29_11-25-23](https://user-images.githubusercontent.com/2474636/33363351-757344de-d4f9-11e7-873f-b52894350d9e.png)

**Comment by clement59** [comment]
Ok mais ca c'est du à l'ivitation via une liste d email #646
