### ISSUE TITLE
network - le form n'itialise pas les tags de la carto 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#403]
https://gist.githubusercontent.com/Simroubriff/6f8b3d2ab0efc9aa53cd68954f87913c/raw/234110d778a03a5e7e33fe09537132efa274edf2/TEA
les tags "vrac" ou "produits biologiques" ne sont pas init dans l'ajout de l'élément. Ainsi l'organisation ajoutée ne se retrouve pas dans la carto

**Comment by RaphaelRIVIERE** [comment]
ça veut dire que tout ce qui se trouve dans searchTag doit etre mis automatiquement en tant que tag ?

``` 
        "searchTag" : [
 		"Vrac",
		"Produits Biologiques"
	]

```

**Comment by clement59** [comment]
En faite je pense qu'il faudrait les mettre automatiquement dans linput en disant mettant une infos disant que le network est initialisé avec un de ces deux tags ... wdyt ?

**Comment by clement59** [comment]
C'est good l'ami
