### ISSUE TITLE
BUG "se souvenir de moi"

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/co2#408]
Cas d'usage:

je rentre mon mail et mon mot de passe puis clic sur la case à cocher "se souvenir de moi" qui affiche une coche.

Je fais ma session sur communecter.

Je me déconnecte ou ferme le navigateur (firefox 55.0.2 (64 bits) sur un OS Ubuntu

Quand je me reconnecte, la case cochée ne semble pas avoir été prise en compte car 
 mon mail n'est pas préafficher, ni le mot de passe
Pierre

**Comment by Drakone** [comment]
Pareil pour moi.

Archlinux, Firefox

**Comment by Drakone** [comment]
J'ai plus eu ce souci depuis un petit moment.
