### ISSUE TITLE
Bug "type évenement ou type d'organisation" 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#409]
Lorsqu'un événement ou une structure est déjà enregistré et que l'on veut modifier les informations générales par exemple le titre ou les mots clés, le type d'événement ou d'organisation s'efface

**Comment by RaphaelRIVIERE** [comment]
Il est corrigé sur dev 
![capture d ecran de 2017-09-11 16-06-07](https://user-images.githubusercontent.com/8775448/30273689-27c96398-970b-11e7-8cf9-c22276afc2a8.png)
