### ISSUE TITLE
Amélioration visibilité contributeur 

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#410]
![capture d ecran 2017-09-08 a 13 58 33](https://user-images.githubusercontent.com/29157378/30206741-16a6bbca-949e-11e7-9c54-6d89fbed15ff.png)

voir contributeur Coralie : "actif il y a 4min" empêche la visibilité du choix

**Comment by clement59** [comment]
Je viens à l'instant de le pushé sur master avec les rôles !
