### ISSUE TITLE
Recherche étendue

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#411]
![capture d ecran_2017-09-08_15-21-42](https://user-images.githubusercontent.com/2474636/30209616-05b19aae-94aa-11e7-8382-053bb5a2ed1c.png)

Quand on clique sur "Recherche étendue" il renvoie vers la page https://www.communecter.org/#search.
J'aimerai que ça fasse une recherche étendue avec les mots clés déjà ajoutés dans le champs de recherche.

**Comment by RaphaelRIVIERE** [comment]
Plus d'actualité avec la prochaine maj
