### ISSUE TITLE
Ajout contributeur > Role 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#413]
Il y a 2 bug :  

- la premiere :
![capture d ecran de 2017-09-11 10-39-54](https://user-images.githubusercontent.com/8775448/30261438-a7ce5176-96dd-11e7-8fc1-3d5eb71490ff.png)

![capture d ecran de 2017-09-11 10-39-29](https://user-images.githubusercontent.com/8775448/30261445-b108ad5e-96dd-11e7-8587-db33425408c7.png)

J'ai essayé d'inviter un utilisateur et j'ai eu se bug.

La deuxieme : 

J'ai ajouté un role à l'utilisateur pour l'invité . Puis j'ai ajouté un nouvelle utilisateur sans role et ça ma mis le role que j'ai mis sur le premier utilisateur.

![capture d ecran de 2017-09-11 10-54-36](https://user-images.githubusercontent.com/8775448/30262016-4721d322-96e0-11e7-964a-55034b22089d.png)

![capture d ecran de 2017-09-11 10-54-45](https://user-images.githubusercontent.com/8775448/30262113-9d40baf2-96e0-11e7-8407-d3ea14a2048c.png)

**Comment by clement59** [comment]
Ajout de roles si pas de roles pour un membre alors qu'on en ajoute !!
