### ISSUE TITLE
Librairie

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#414]
J'ai crée des dossiers et sous dossier.
voici la hiérachie : 
- Tableur
     - sous dossier
          - sous dossier 2
          - sous dossier 3
                - sous dossier 4 

J'ai d'abords ajouté un fichier à la racine. Puis je l'est déplacer dans "Tableur" , jusque la nickel . Puis j'ai voulus la déplacer dans "sous dossier 4" et j'ai eu cette erreur 

![capture d ecran de 2017-09-11 11-09-37](https://user-images.githubusercontent.com/8775448/30262533-5b42bd4c-96e2-11e7-82d3-c5a9c765f9e4.png)
![capture d ecran de 2017-09-11 11-09-22](https://user-images.githubusercontent.com/8775448/30262538-5db89010-96e2-11e7-8788-2db9b135bb75.png)
![capture d ecran de 2017-09-11 11-09-13](https://user-images.githubusercontent.com/8775448/30262557-6d7fbc1c-96e2-11e7-9fe2-370723817734.png)

**Comment by Drakone** [comment]
Sur QA j'ai réussi à déplacer [mon pdf](http://qa.communecter.org/#openAtlas.view.library) à tous les niveaux de l'arborescences des fichiers de bas en haut et de haut en bas.
