### ISSUE TITLE
Bug news DDA on coment => fond vert

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#430]
![capture d ecran de 2017-09-15 16-04-58](https://user-images.githubusercontent.com/6576514/30486064-bb9dffc6-9a2f-11e7-84b1-ebdc57aff51e.png)

**Comment by Kgneo** [comment]
je n'ai pas réussi à reproduire ce bug, par contre j'ai trouvé plusieurs petits problèmes sur les commentaires (un peu lié au dda mais pas que)
normalement tout est ok, en tout cas pour ceux que j'ai trouvé.

le bug sur les réponses de com, sur le DDA a l'air d'être réglé aussi : https://github.com/pixelhumain/co2/issues/449

![comments](https://user-images.githubusercontent.com/7578166/30841822-f461b9ae-a2c9-11e7-86d2-31bc520bb762.png)

**Comment by clement59** [comment]
ok good
