### ISSUE TITLE
Renommer "évènement" dans un évènement

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#436]
Lorsqu'on est sur un évènement ce serait plus compréhensible de renommer l'onglet "Évènements" en "Programme".

Cette proposition part du principe que les sous-évènements seront surtout utilisé par les festivals. Exemple pour Alternatiba péi : https://www.communecter.org/#page.type.events.id.59bf946240bb4e6006cf5d4d.view.directory.dir.events

![capture d ecran_2017-09-18_14-21-49](https://user-images.githubusercontent.com/2474636/30537940-d4e780b6-9c7c-11e7-8a55-5b96ce34a0bd.png)

**Comment by clement59** [comment]
+1 Programme et a voir calendrier pour les autres !?

**Comment by RaphaelRIVIERE** [comment]
+1 aussi pour Programme

**Comment by RaphaelRIVIERE** [comment]
@oceatoon et @Kgneo  wdyt ?

**Comment by clement59** [comment]
Ok maintenant ce sera "Programme" dans les événements et "Agenda" dans les autres éléments
![capture d ecran de 2017-11-13 22-00-50](https://user-images.githubusercontent.com/6576514/32749020-40c805fe-c8be-11e7-891c-00984b8520c8.png)
![capture d ecran de 2017-11-13 22-01-22](https://user-images.githubusercontent.com/6576514/32749029-47229dd8-c8be-11e7-849c-3d1327b94520.png)
@Drakone si tu es ok ... To close :)

**Comment by Drakone** [comment]
+1
