### ISSUE TITLE
Être participant

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#441]
Quand je clique sur "être participant" rien ne se passe, même après réactualisation.
![capture d ecran_2017-09-19_14-19-41](https://user-images.githubusercontent.com/2474636/30588202-de333898-9d46-11e7-9e39-7ab0a5302e78.png)

**Comment by clement59** [comment]
Peux-tu tester sur qa et fermé si c'est bon @Drakone ?

**Comment by Drakone** [comment]
Ok pour moi.

**Comment by Drakone** [comment]
J'ai un retour de ce bug !

![capture d ecran_2018-11-14_16-07-57](https://user-images.githubusercontent.com/2474636/48491337-9ff80400-e827-11e8-95d2-8e0a5048f6f5.png)
