### ISSUE TITLE
Bug - Cities search bar menutop 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#442]
![capture d ecran de 2017-09-19 15-39-57](https://user-images.githubusercontent.com/6576514/30595226-e341f0cc-9d50-11e7-94c1-d71f3b0cf414.png)
Moi je suis pour les enlever !

**Comment by clement59** [comment]
Ok pour la redirection sur city par contre le scope de la communexion n'est pas activé donc recherche globale

**Comment by RaphaelRIVIERE** [comment]
Plus d'actualités
