### ISSUE TITLE
Inter - Indiquer au utilisateur de saisir la ville en entier

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#454]

**Comment by RaphaelRIVIERE** [comment]
Tu peux me donner un exemple que ta mis ? 
Parce que en local j'ai réussi

**Comment by clement59** [comment]
Chili > santiago || valparaiso

**Comment by RaphaelRIVIERE** [comment]
Pour Santiago, je le trouve 
![capture d ecran de 2017-10-12 13-31-45](https://user-images.githubusercontent.com/8775448/31490361-ba79cbe0-af54-11e7-9d85-ab0d9b63e44f.png)

valparaiso , je trouve aussi mais il y a un soucis de geoshape  que je check

**Comment by clement59** [comment]
Ok ! alors il faut indiquer à l'utilisateur qu'il faut rentrer la ville en entier

**Comment by clement59** [comment]
Ok
