### ISSUE TITLE
Inter - Multi use case (module search,live,agenda)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#458]
1- Je me suis communecté à cuzco au pérou sur mon profil ( ca c'est ok, ca marche)

2- j'arrive sur le live et mon scope de communexion n'est pas pris en charge == Il me propose de me communecter (bug)

3- Du coup, je me recommuncete tout de même pour tester mais au save pas contre là il me fait une erreur: (erreur dans la console screenshot)
![capture d ecran de 2017-09-25 14-39-02](https://user-images.githubusercontent.com/6576514/30808766-a53cb5c4-a1ff-11e7-834a-c7a0d3cb69b0.png)

**Comment by clement59** [comment]
1 - ok pour le please wait !!

2 - ok pour valparaiso et la communexion est bien prise en compte

3- si du coup je supprime ma communexion à partir de ma page et qu'ensuite je retourne sur les breadcrums==> Il me propose de me connecté avec null / et au reload erreur js
![capture d ecran de 2017-10-12 20-33-01](https://user-images.githubusercontent.com/6576514/31512895-c7306f8c-af8c-11e7-9a98-cd64a333203a.png)


New bug : 
1 - Ma ville n'est pas visible dans mon panel about
![capture d ecran de 2017-10-12 20-23-05](https://user-images.githubusercontent.com/6576514/31512455-4bbffb84-af8b-11e7-952c-928928d738df.png)
Au reload c'est good !

2 - Le live fait du globalautocomplete (il se croit dans le search)

3 - Pour Lille normalement je devrait avoir des news cp 59000
![capture d ecran de 2017-10-12 20-31-42](https://user-images.githubusercontent.com/6576514/31512786-70ac2a66-af8c-11e7-9d3a-706806551bb3.png)

4 - Je n'ai pas les niveau supérieur pour valparaiso

**Comment by RaphaelRIVIERE** [comment]
Alors je re-list les codes : 

1 /  Supprimer sa communexion à partir de ma page et qu'ensuite je retourne sur les breadcrums==> Il me propose de me connecté avec null / et au reload erreur js : En cours

2 / Ma ville n'est pas visible dans mon panel about : Corrigé et a testé

3 / Le live fait du globalautocomplete (il se croit dans le search) : en cours

4 / Je n'ai pas les niveau supérieur pour valparaiso : Corriger

**Comment by clement59** [comment]
Ok pour le live ...
Pour le 1 je ferme car je viens de commenter une autre issue avec ce bug
