### ISSUE TITLE
Multiscope non cliquable après un choix de thématique 

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#459]
Dans le module search (et aussi mon module d'intérop par la même occasion ^^"), les boutons du multiscope ne sont plus cliquables après un clic sur une thématique. 

D'ailleurs est ce normal qu'ils sont en anglais ?

**Comment by GrondinDam** [comment]
D'ailleurs j'avais pas fait gaffe mais un clic sur une thématique te fait sortir de ta communexion.

**Comment by clement59** [comment]
Roulalalala full bugs:
1- Les click select/ deselect marchent une fois sur deux 
2 - Je désactive tous les scopes mais ils restent focus sur mon dernier scope (qui est désactivé)
![capture d ecran de 2017-11-13 18-28-23](https://user-images.githubusercontent.com/6576514/32739642-ca0265bc-c8a0-11e7-8309-0c102c1c7cac.png)
3- Le click sur les thématiques réactivent tous les scopes
