### ISSUE TITLE
En ce moment

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#461]
En haut à droite de tous les event il y a "En ce moment".
![capture d ecran_2017-09-26_14-57-51](https://user-images.githubusercontent.com/2474636/30857241-0d5fd07e-a2cc-11e7-84e0-0f01ff2a84d2.png)

**Comment by clement59** [comment]
Normalement c'est réglé

**Comment by Drakone** [comment]
Pour "En ce moment" c'est reglé en effet.
Par contre "1 mois et 0 jour" c'est pas top.
![capture d ecran_2017-11-14_19-14-11](https://user-images.githubusercontent.com/2474636/32787557-3d78773c-c970-11e7-8a7b-cdffa7959383.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-11-14 17-56-34](https://user-images.githubusercontent.com/6576514/32793145-695daae4-c965-11e7-8934-6fba1940415e.png)
