### ISSUE TITLE
Bug Url notifcation

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#468]
![image](https://user-images.githubusercontent.com/8775448/30966442-ef59c982-a469-11e7-87a8-3b0b584737d7.png)

l'url c'est person.detail.id.{user-id} au lieu de page.type.citoyens.id.user-id

d'ailleur il me semblais que @oceatoon avait fais en sorte que les ancienne url fonctionne si je me trompe ?

**Comment by clement59** [comment]
Arf ! j'ai eut peuuuuur :) c'est la vue des elements ou tu as les btns de propositions ?

**Comment by RaphaelRIVIERE** [comment]
ça meme :)
