### ISSUE TITLE
Certaines icones sur la carte sont transparentes

### ISSUE THREAD

**Issue by funkycram** [pixelhumain/co2#470]
![image](https://user-images.githubusercontent.com/23310825/31052412-38585f42-a684-11e7-8759-f9a78223a43f.png)

**Comment by RaphaelRIVIERE** [comment]
Est-ce que c'est sur PROD ? si c'est QA ou Dev "c'est normal", c'est a cause du fait qu'on a copié prod sur qa pour des test mais qu'on a pas rapatrier les images

**Comment by funkycram** [comment]
Ha ben oui, c'est ça !
