### ISSUE TITLE
Formulaire "Créer un compte" 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#480]
En remplissant le formulaire de création de compte : 
Je rentre d'abord un nom et prénom puis un nom d'utilisateur, une fois que je passe à l'adresse mail ça me remodifie automatiquement le nom et prénom par le nom d'utilisateur
Petite répétition à la case mot de passe également 
![2017-10-04](https://user-images.githubusercontent.com/30291819/31160914-4cc9dd82-a8d4-11e7-8c03-16f8b31670e6.png)
![2017-10-04 1](https://user-images.githubusercontent.com/30291819/31160918-4f632fd0-a8d4-11e7-8ed7-ec7610aea0f3.png)

**Comment by scoid** [comment]
Petite répétition à la case mot de passe également. Aussi en anglais et en allemand.
![screenshot-2017-10-24 reseau societal citoyen allemande](https://user-images.githubusercontent.com/2099251/31951439-68258756-b8de-11e7-83bf-e19600d86817.png)
![screenshot-2017-10-24 reseau societal citoyen anglais](https://user-images.githubusercontent.com/2099251/31951444-6b35c6e0-b8de-11e7-8f3d-354a7bac09ae.png)

**Comment by scoid** [comment]
Cela vaut également pour les versions anglaise et allemande.

**Comment by clement59** [comment]
Pour la répétition c'est ok
