### ISSUE TITLE
Liens Facebook

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#482]
C'est pas joli :(

![capture d ecran_2017-10-04_11-40-50](https://user-images.githubusercontent.com/2474636/31164669-264ec04e-a8f9-11e7-8cbc-20ad72ab0652.png)

PS : et c'est pas joli non plus de mettre un lien Facebook sur Communecter, on est d'accord :)

**Comment by clement59** [comment]
Faudra dire merci à facebook ! Si c'est ok pour toi ... to close !
