### ISSUE TITLE
Comportement filtres des membres

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#491]
C'est étrange.
![peek 10-10-2017 14-59](https://user-images.githubusercontent.com/2474636/31383401-f8ebed48-adcb-11e7-86a6-f6c1c70582e1.gif)

**Comment by clement59** [comment]
Moi y'a bon normalement !

**Comment by Drakone** [comment]
Trop bien on peut activer plusieurs filtres. C'est top :)

**Comment by clement59** [comment]
Ok je close
