### ISSUE TITLE
Changement de dates

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#492]
Ça change tout seul de dates quand je valide.

![screenshot from 2017-10-04 10-48-03](https://user-images.githubusercontent.com/2474636/31426678-59c6dbc4-ae75-11e7-80cf-d2cac8e4690f.png)

**Comment by clement59** [comment]
Enfaite c'est quand ca passe à la sauvegarde des données que le format change parce que coté serveur on a besoin d'un autre format ...Mais normalement ceux sont quand les bonnes dates àprès enregistrement.
