### ISSUE TITLE
ajout de Tags et modification d'un post 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#494]
En faisant un post je n'ai pas mis les tags correctement du coup en modifiant j'ai un message qui me dit "something went wrong" (d'ailleurs pourquoi il me parle anglais celui là??? ;) ) 
et ça charge indéfiniment... 
![2017-10-12](https://user-images.githubusercontent.com/30291819/31489319-547fa8b2-af51-11e7-840b-0c2f4507277e.png)
![2017-10-12 1](https://user-images.githubusercontent.com/30291819/31489320-54bb8da0-af51-11e7-8840-d5af0f4bf060.png)

**Comment by clement59** [comment]
Hello @corail974,
Il me faudrait toutes les infos de ton post : 
Qui est l'auteur, sur quel page as tu posté cette news, le lien que tu insères, ton texte et les tags que tu as voulu rajouter ... Si tu as le lien vers la news ce sera plus simple :)

**Comment by corail974** [comment]
Hola @clement59 !
C'est moi l'auteur du post, je l'ai posté a partir de ma page, les tags je l'ai ai mis d'abord juste avec les hashtag j'avais oublié qu'il y avait la section spéciale en dessous. Du coup après j'ai juste voulu modifier pour mettre les tags correctement 
![2017-10-12 2](https://user-images.githubusercontent.com/30291819/31513248-d4c78236-af9e-11e7-8ffa-87595b8615db.png)

**Comment by clement59** [comment]
J'arrive po à le reproduire ;(
![capture d ecran de 2017-10-12 20-54-50](https://user-images.githubusercontent.com/6576514/31513790-ac1e892e-af8f-11e7-9dd6-1edda5d26439.png)

**Comment by clement59** [comment]
Peux tu me faire un imprim écran de ta console au moment ou tu save la modification 

> clique droit souris > inspecter l'élément > tu auras la console (cf imprim écran)

![capture d ecran de 2017-10-12 20-56-37](https://user-images.githubusercontent.com/6576514/31513892-ffd85a72-af8f-11e7-962f-613ef6174ca4.png)

**Comment by corail974** [comment]
![2017-10-14 1](https://user-images.githubusercontent.com/30291819/31572778-a76db294-b0be-11e7-9c09-0940d2337db4.png)
![2017-10-14 2](https://user-images.githubusercontent.com/30291819/31572779-a7a4f178-b0be-11e7-8a30-c4224a463de0.png)

J'ai retenté ...

**Comment by RaphaelRIVIERE** [comment]
J'ai pu faire la modif en ajoutant un tags
Je close
