### ISSUE TITLE
Trad pays 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#497]
![capture d ecran de 2017-10-12 20-17-16](https://user-images.githubusercontent.com/6576514/31512201-644adb98-af8a-11e7-82e9-73256684562f.png)
Je pense que pour ça ya des docs déjà tout fait

**Comment by RaphaelRIVIERE** [comment]
J'ai trouver ça  :  https://restcountries.eu/#rest-countries
Test : https://restcountries.eu/rest/v2/lang/es?fields=translations;alpha2Code;name

Vous en pensez quoi @clement59 @oceatoon @Drakone @aboire ?

**Comment by RaphaelRIVIERE** [comment]
https://github.com/mledoze/countries/blob/master/dist/countries.json

**Comment by clement59** [comment]
![capture d ecran de 2017-11-13 17-24-15](https://user-images.githubusercontent.com/6576514/32736346-80952210-c897-11e7-955b-b83347b438a1.png)
Yeeeeaaaaaaaaah !
