### ISSUE TITLE
Annonces - personne / contact inexistant !

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#500]
![capture d ecran de 2017-10-14 14-27-30](https://user-images.githubusercontent.com/6576514/31575659-2ae7fe36-b0ec-11e7-99d3-4c78421dd211.png)
![capture d ecran de 2017-10-14 14-27-22](https://user-images.githubusercontent.com/6576514/31575664-2f064a0e-b0ec-11e7-928d-62e9bf57fbed.png)

**Comment by oceatoon** [comment]
ah ouais pas mal , comment j'ai pu le rater celui ci !!
