### ISSUE TITLE
Inter - save city error 500

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#505]
Deutschland / Hamburg / addres == Sternschwanze => 500 sur geo undefined
![capture d ecran de 2017-10-16 16-31-45](https://user-images.githubusercontent.com/6576514/31617502-ad96631e-b28f-11e7-9b37-2003d02daccf.png)
![capture d ecran de 2017-10-16 16-31-41](https://user-images.githubusercontent.com/6576514/31617503-adc767c0-b28f-11e7-8270-f9946b9979a0.png)

**Comment by RaphaelRIVIERE** [comment]
Ok meme , probleme que le mexique, j'suis dessus

**Comment by clement59** [comment]
génial
