### ISSUE TITLE
Bug sur la communexion

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#507]
Si je suis communecté 

![capture d ecran de 2017-10-18 16-12-52](https://user-images.githubusercontent.com/22808909/31718009-4a63edde-b41f-11e7-87a8-0b55938e9cd0.png)

Et que je vais ensuite sur mon profil perso dans "A propos" et que je clique sur la poubelle rouge
![capture d ecran de 2017-10-18 16-14-52](https://user-images.githubusercontent.com/22808909/31718058-82d08b00-b41f-11e7-90d5-07c959e0e24a.png)

Les boutons n'ont pas value 
![capture d ecran de 2017-10-18 15-55-09](https://user-images.githubusercontent.com/22808909/31718088-9c09a26e-b41f-11e7-9ea0-07a36f64093c.png)

Et a partir de là, même si je clique sur la croix, le bouton rouge ou le bouton vert, cela enleve ma communexion et en plus cela créer un bug sur la page search qui plante complétement

![capture d ecran de 2017-10-18 15-56-19](https://user-images.githubusercontent.com/22808909/31718146-d94bf0f0-b41f-11e7-87f2-ae3ce1d4bf29.png)

**Comment by clement59** [comment]
Outcha toujours d'actu !!! Pour le retour après suppression sur search
![capture d ecran de 2017-11-13 16-59-00](https://user-images.githubusercontent.com/6576514/32735053-058b48c2-c894-11e7-9693-4e488b923f08.png)

**Comment by clement59** [comment]
Bueno !!
