### ISSUE TITLE
Problem add address in form => persistance du btn addresse principale

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#51]
on comprend pas trop car j'ai fait l'action de communecter donc j'ai bien l'adresse au dessus. Mais du coup en recliquant il ne me remet pas sur hellemmes (formulaire qui engendre le bug #50 quand on ferme ;) )
Je verrais l'adresse en plus esthéthique genre:
L'organisation est communectée à "$adresse"
et deux btn:
Modifier l'adresse / Supprimer la communexion
![capture d ecran de 2017-04-24 21-10-09](https://cloud.githubusercontent.com/assets/6576514/25354332/dee1ca3a-2932-11e7-8f5b-f3ece08d8967.png)

**Comment by RaphaelRIVIERE** [comment]
@clement59  Comment ta fais pour pas avoir (locality centrale) ? 
![capture d ecran de 2017-04-27 11-56-11](https://cloud.githubusercontent.com/assets/8775448/25473472/a7f7fd40-2b40-11e7-8ca6-53e5f6906805.png)

**Comment by RaphaelRIVIERE** [comment]
@clement59 est-ce que ta un bug sur ça ? est-ce que c'est pas plutôt une amélioration
