### ISSUE TITLE
Sélectionner "point d'intéret" après création impossible 

### ISSUE THREAD

**Issue by corail974** [pixelhumain/co2#513]
J'ai crée un point d'intéret à partir d'une orga, une fois crée impossible de l'ouvrir sauf en faisant clique droit "ouvrir dans un nouvel onglet" 
![2017-10-20](https://user-images.githubusercontent.com/30291819/31823518-6ee82aae-b5bd-11e7-99f0-1f26b3373a5c.png)

**Comment by clement59** [comment]
ok ca venait du mapElement vide
