### ISSUE TITLE
Mauvaise url à l'enregistrement d'un element

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#52]
/ph/co2#organization.detail.id.586f6493e2f07ea55a8b456b586f6493e2f07ea55a8b456b

**Comment by RaphaelRIVIERE** [comment]
@oceatoon  est dessus il me semble , il est entrain de faire un process pour que les anciennes url fonctionne toujours

**Comment by clement59** [comment]
+1111

**Comment by clement59** [comment]
quand c'est un nouvel element on est tjrs reste sur lurl en court

**Comment by clement59** [comment]
garde l'id de l'élément en court ... Pas bueno

**Comment by clement59** [comment]
ok ca rejoint #146 je ferme
