### ISSUE TITLE
Carto - sur le click du citoyen(colonne droite), le pop up n'affiche rien et btn sur "afficher +"

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#520]
Aucune info dans le pop up du citoyen et le click + de détail ne fait rien à part fermer la pop up
![capture d ecran de 2017-10-24 14-06-47](https://user-images.githubusercontent.com/6576514/31942206-d92c45da-b8c4-11e7-893d-4d150643f81e.png)

**Comment by RaphaelRIVIERE** [comment]
Je viens de testé et on est ça fonctionne
