### ISSUE TITLE
Activité territoriale - Rien ne se passe au click des poi et classified

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#521]
Aucune redirection sur les standalone

**Comment by clement59** [comment]
Effecxtivement le mapElement est empty !!
Ce genre de cas pourrait être réglé avec la preview développé sur terla ... affaire à suivre !

**Comment by oceatoon** [comment]
en local pour moi  ca tourne bien 
vous avez un use case précis ?

**Comment by oceatoon** [comment]
c bon j'ai trouvé sur PROD, je suis dessus
