### ISSUE TITLE
L'affichage du résultat de la recherche ne doit pas être traduit

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#523]
peut-être que le code source est ici https://github.com/pixelhumain/co2/blob/51e9acdc0f0647a0b4b177094cec13037061c624/views/default/directory.php

![bildschirmfoto vom 2017-10-24 19-05-22](https://user-images.githubusercontent.com/2099251/31957472-2c37d0b2-b8ef-11e7-8932-bb167414dc0b.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-10-27 20-10-21](https://user-images.githubusercontent.com/6576514/32118686-e2dafb2c-bb52-11e7-8fad-0e4be28d69b6.png)
