### ISSUE TITLE
Bug communexion à la page d'acceuil

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#527]
Le formulaire de communexion de la page d'acceuil lance un globalautocomplete

![capture d ecran de 2017-10-25 11-17-54](https://user-images.githubusercontent.com/22808909/31985443-30e597c0-b976-11e7-8f91-64782c518aa3.png)

**Comment by RaphaelRIVIERE** [comment]
c'est normal qu'il lance un globalautocomplete
