### ISSUE TITLE
Bug redirect dans menu person en haut à droite (communexion + admin)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#53]
Admin == erreur 404 (mais je pense que rapha tu es desus)
Communexion == renvoie sur les propositions d'ajout
![capture d ecran de 2017-04-24 21-16-39](https://cloud.githubusercontent.com/assets/6576514/25354525/87559f20-2933-11e7-90ba-0e5a8af2c87e.png)

**Comment by RaphaelRIVIERE** [comment]
C'est parce que ton compte n'est pas admin. J'ai fais la modif sur le bouton admin pour qu'il apparaisse seulement si t'es superAdmin

**Comment by RaphaelRIVIERE** [comment]
Corriger a testé

**Comment by clement59** [comment]
good
