### ISSUE TITLE
Modifier les informations générales d'un événement déjà existant

### ISSUE THREAD

**Issue by Fanie-reunion** [pixelhumain/co2#532]
Quand j'essaie de modifier les informations générales d'un événement, la validation ne fonctionne pas. 
Le nom de l'événement est incomplet, le l'organisateur n'apparait plus
![capture d ecran de 2017-10-25 15-28-13](https://user-images.githubusercontent.com/32702764/31996334-39684578-b999-11e7-8f41-57642b8e6dd2.png)

**Comment by Drakone** [comment]
Pour ajouter une image tu dois cliquer sur le petit message en dessous de l'endroit où tu tapes ;).
Le glisser-déposer fonctionne aussi.

**Comment by clement59** [comment]
Je l'ai tjrs ...
![capture d ecran de 2017-11-13 15-25-09](https://user-images.githubusercontent.com/6576514/32730305-f044a7fe-c886-11e7-9e6a-a718793fcb2f.png)

**Comment by clement59** [comment]
Ok bon enfaite c'est écris c'est obligatoire ;) Et il y a un label "je ne sais pas" ! 
Par contre ça a permet de fixer un autre quand on passe d'un event ou il y a un organizator à un event ou l'on ne sait pas quel est l'organisateur !
