### ISSUE TITLE
Bug dynForm pour ajouter un evenement

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#534]
Le titre est blanc de la même couleur que le background du coup on le voit pas 

Dans le select "Fait parti d'un événement ?" il y a un "undefined ?"

![capture d ecran de 2017-10-25 16-44-44](https://user-images.githubusercontent.com/22808909/31999323-eabe7590-b9a3-11e7-8b66-2fabce510e1f.png)

**Comment by GrondinDam** [comment]
Pour avoir le bug il faut se placer dans le module d'agenda

**Comment by scoid** [comment]
il y a un "undefined ?"
![img_3911](https://user-images.githubusercontent.com/2099251/32011726-e4882d26-b9b5-11e7-8aee-a1f27159edac.png)

**Comment by GrondinDam** [comment]
Je n'ai plus le "undefined" cependant j'ai toujours le titre blanc (je rapelle qu'il faut se placer dans le module "agenda" pour avoir le bug 

![image](https://user-images.githubusercontent.com/22808909/32049155-06b1a592-ba5d-11e7-8dbf-3171b987cfd2.png)
