### ISSUE TITLE
Bug lors de la décommunexion 

### ISSUE THREAD

**Issue by GrondinDam** [pixelhumain/co2#537]
Lors d'un refresh de la page ma communexion est bien activé cependant lorsque je clique sur la croix pour me décommunecter je n'arrive plus à me re-communecter avec ma ville

![image](https://user-images.githubusercontent.com/22808909/32047447-043f472a-ba57-11e7-9701-46960d27566e.png)

On me demande de communecter avec une ville 
![image](https://user-images.githubusercontent.com/22808909/32047573-66c09ba6-ba57-11e7-875d-b3f8e115247c.png)

Et meme si je le fais et choisi une ville pour me communecter avec cela ne fonctionne pas et on en revien au screen précédent. 

Je suis obligé de refresh la page pour activer ma communection

**Comment by RaphaelRIVIERE** [comment]
J'arrive pas a reproduire, à retesté
