### ISSUE TITLE
la traduction des calendriers n'est pas internationalisée

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#539]
![bildschirmfoto vom 2017-10-25 16-56-16](https://user-images.githubusercontent.com/2099251/32054815-fa87a476-ba5f-11e7-9e81-b28d0a4da987.png)
![bildschirmfoto vom 2017-10-26 12-17-17](https://user-images.githubusercontent.com/2099251/32054818-fcb0d326-ba5f-11e7-8460-5298f162b98b.png)

**Comment by clement59** [comment]
Pour le premier, les calendriers des forms je reporte dans une autre issue car ça peut avoir des impacts de le traduire
![capture d ecran de 2017-10-27 20-27-29](https://user-images.githubusercontent.com/6576514/32119363-47ef04d4-bb55-11e7-8047-898970a13732.png)
![capture d ecran de 2017-10-27 20-54-00](https://user-images.githubusercontent.com/6576514/32120483-0bb5173e-bb59-11e7-8835-b650c528a8e3.png)
