### ISSUE TITLE
Le beau module de carte n'est pas encore traduisible

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#558]
![bildschirmfoto vom 2017-10-25 20-50-48](https://user-images.githubusercontent.com/2099251/32057685-4388eefc-ba68-11e7-90ca-f109087f1655.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-11-08 11-33-10](https://user-images.githubusercontent.com/8775448/32538871-a24bb3d8-c478-11e7-854c-b0c3a8daa91a.png)

**Comment by RaphaelRIVIERE** [comment]
@scoid c'est bon j'ai mis la traduction de la map dans de/common.php :)
