### ISSUE TITLE
non traduit, aussi infobulles, par floopdrawer

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#562]
![bildschirmfoto vom 2017-10-26 21-35-56](https://user-images.githubusercontent.com/2099251/32133685-a9c8fdc6-bbdd-11e7-8945-4585d4f90ee3.png)
![bildschirmfoto vom 2017-10-28 12-33-43](https://user-images.githubusercontent.com/2099251/32133686-a9f57d42-bbdd-11e7-9aa6-bc6530ae41c4.png)

**Comment by clement59** [comment]
Done yesterday !
