### ISSUE TITLE
réintégrer le calendar (programme d'un événement)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#572]
![capture d ecran de 2017-10-29 17-53-44](https://user-images.githubusercontent.com/6576514/32146057-3f26fc5c-bcd2-11e7-8514-3ecc7cbbeb77.png)

**Comment by clement59** [comment]
To test in qa

**Comment by Drakone** [comment]
Il y a sûrement moyen d'améliorer l'ergonomie de l'affichette mais ça fonctionne :)

![capture d ecran_2017-11-14_19-19-50](https://user-images.githubusercontent.com/2474636/32787843-0d208538-c971-11e7-98b2-6182648dbd19.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-11-14 18-00-26](https://user-images.githubusercontent.com/6576514/32793296-c8e178e2-c965-11e7-8144-17936a5d6ec5.png)
![capture d ecran de 2017-11-14 18-00-23](https://user-images.githubusercontent.com/6576514/32793297-c94752c0-c965-11e7-8e74-a8abb85ea055.png)
