### ISSUE TITLE
Notifiation résolution

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#573]
1 -> C'est en anglais
2 -> Pourquoi c'est Jahne qui est mentionné ? C'est une décision collective prise à l'issue d'un vote

Le lien renvoi vers : https://www.communecter.org/#page.type.organizations.id.555eba56c655675cdd65bf19.view.coop.room.59cfc09e40bb4e9c3a991ba5.resolution.59db5f0540bb4ebc758afb89

![capture d ecran_2017-10-30_13-04-48](https://user-images.githubusercontent.com/2474636/32162640-230dbc94-bd73-11e7-8c7a-ebd59ad5503d.png)

**Comment by clement59** [comment]
Ok c'est fixé ! a tester sur qa ... Pour les résolutions qui arriveront

**Comment by clement59** [comment]
@Drakone mieux ??
![capture d ecran de 2017-11-15 13-55-04](https://user-images.githubusercontent.com/6576514/32837157-be11c2a8-ca0c-11e7-9206-916c57b0119b.png)
ou encore en allemand ^^
![capture d ecran de 2017-11-15 13-55-33](https://user-images.githubusercontent.com/6576514/32837156-bded6796-ca0c-11e7-8827-8d24e0fd24b2.png)

**Comment by Drakone** [comment]
Okay
