### ISSUE TITLE
organnisation introuvable

### ISSUE THREAD

**Issue by julien-RE** [pixelhumain/co2#574]
jai crée lorganisation mais je le trouve pas avec le moteur de recherche 

http://qa.communecter.org/#ComplexeSportifRochesmaigres.view.detail

![capture d ecran de 2017-10-30 13-56-38](https://user-images.githubusercontent.com/33219941/32164868-318d6a92-bd7a-11e7-9709-c3367a17c255.png)

**Comment by Drakone** [comment]
Erreur de choix de serveur pour créer l'orga. J'ai fait le topo à Julien, il bascule l'orga en prod ;)
