### ISSUE TITLE
Multiscope - impossible de chercher sur tous les pays

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#586]
![capture d ecran de 2017-11-03 20-15-04](https://user-images.githubusercontent.com/6576514/32391816-c306e0f0-c0d3-11e7-87ee-dc87b74c4491.png)

**Comment by RaphaelRIVIERE** [comment]
c'est pas un bug , c'est normal, J'ai seulement les pays ou il y a une ville de crée.

**Comment by clement59** [comment]
Bah si c'est un bug ... Pourquoi on a pas tout  ?!

**Comment by clement59** [comment]
Du coup c'est pareil pour les zones d'un pays ?
Par exemple je suis Allemagne et je veux rajouter la région Schleswig-Holstein mais il ne trouve pas .. ?

**Comment by clement59** [comment]
![capture d ecran de 2017-11-13 19-55-55](https://user-images.githubusercontent.com/6576514/32743444-b284f740-c8ac-11e7-9490-b836597e8744.png)
Buen papi @RaphaelRIVIERE ?

**Comment by RaphaelRIVIERE** [comment]
Top :)
