### ISSUE TITLE
Image de profil cachée - Amélioration

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#587]
![capture d ecran 2017-11-04 a 03 32 37](https://user-images.githubusercontent.com/29157378/32401547-f08dd348-c110-11e7-83a6-e747e3891c77.png)
C'est dommage qu'on ne puisse pas bien voir l'image. ça arrive souvent aussi avec les bannières et les mentions "open data" "parenté à"

**Comment by clement59** [comment]
Ok je close btn d'action en -dessous maintenant
