### ISSUE TITLE
Evénements introuvables !!!!

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#589]
![capture d ecran 2017-11-05 a 22 41 57](https://user-images.githubusercontent.com/29157378/32419485-a7a0ba22-c27a-11e7-806d-558af5e2d52b.png)
impossible de trouver l'événement alors que je l'ai créé il y a 2 jours
je peux y avoir accès mais je dois avoir l'url dispo qlq part
ce problème persiste depuis un petit moment
(et ça commence à être chaud pour la com et les présentations)

**Comment by clement59** [comment]
Humm intéressant c'est parce que l'event est passé !

**Comment by Jahne-Anders** [comment]
même un jour avant je ne pouvais pas le retrouver sauf avec l'url

**Comment by Drakone** [comment]
Tango : 
c'est bon j'ai fait marcher la recherche sur des événements passés
du coup j'étais obligé de le prendre en compte dans l'agenda
donc maintenant les recherches se font mois par mois sur l'agenda. avec 100 event max
et quand on est sur une page element, la recherche globale renvoit tous les event, même ceux avec des dates dépassées
c'est commité sur master

**Comment by Jahne-Anders** [comment]
Un grand merci <3
