### ISSUE TITLE
Organisation introuvable pour invitation

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#591]
L'orga existe mais impossible de l'inviter.
![capture d ecran_2017-11-06_15-39-20](https://user-images.githubusercontent.com/2474636/32439652-13a571c0-c309-11e7-9efd-73c651fd4191.png)
![capture d ecran_2017-11-06_15-38-54](https://user-images.githubusercontent.com/2474636/32439655-13ed439c-c309-11e7-8fbd-240a38d1d1b9.png)

**Comment by clement59** [comment]
C'est un projet et non une orga (couleur violette)
