### ISSUE TITLE
Notification - nom en double

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#592]
Moi j'en connais qu'un seul Tibor :p
![capture d ecran_2017-11-06_15-44-51](https://user-images.githubusercontent.com/2474636/32439794-c729bbb6-c309-11e7-8041-998949267234.png)

**Comment by clement59** [comment]
Alors cela ... Je pense qu'il est réglé avec le petit refactor des notifications qui vient de passer ! Je le mets en to test et si vous retrouvez cette erreur dans vos nouvelles notifs, j'attends le nouveaux screenshot

**Comment by Drakone** [comment]
Difficile à reproduire... Perso je l'ai jamais eu de nouveau.
