### ISSUE TITLE
debuguer les url des notifications

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#6]
Problème : Les url des notif renvoient vers des pages qui n'existe pas dans C02
Solutions :
- Modifier les url des notif ?
- Ou créer les pages manquantes selon les url des notif ?
- Ou les 2 selon les cas ?

Todo : 
Vérifier toutes les url du nouveau système de notif

**Comment by clement59** [comment]
Pour les directory c'est bon, ca existe ! tu parles de news.detail ? et tu en as d'autres ?

**Comment by Kgneo** [comment]
moi j'en ai aucune qui marche

**Comment by clement59** [comment]
ok c'est push !! Manque plus que l'url des news en standalone .. Je te laisse me donner l'url

**Comment by clement59** [comment]
Url news pushé à test pour les nouvelles et il reste les anciennes url à rediriger (directory seulement)

**Comment by clement59** [comment]
si quelqu'un a encore des anciennes url je veux bien qu'il le fasse ... @pixelhumain/dev 
Pour interpréter les urls c'est dans co.js > urlCtrl.loadableUrls
Il y a l'exemple que @oceatoon a fait pour detail et le faire pour directory > vu qu'ils sont spécifique maintenant, ça donnerait:
organization.directory => aliasParams : "page.type.organizations.id.$id.view.directory.dir.members
project.directory => aliasParams : "page.type.projects.id.$id.view.directory.dir.contributors
event.directory => aliasParams : "page.type.events.id.$id.view.directory.dir.attendees

**Comment by clement59** [comment]
bon je les ai rajouté mais pour le test a vous de voir (sachant aussi que dansles notifs c'est des urls direct...)

**Comment by clement59** [comment]
ok normalement tout est bon !!! Meme pour les anciennes urls, j'ai rajouté un script !!! @RaphaelRIVIERE 

A fermer et faire du spécifique si anomalie !!!

**Comment by clement59** [comment]
Je ferme , faire du scpécifique pour celle ci
