### ISSUE TITLE
Internationalisation - Localisation Maldives - Ne trouve pas les villes 

### ISSUE THREAD

**Issue by Fanie-reunion** [pixelhumain/co2#604]
#42 
![capture d ecran de 2017-11-10 10-19-54](https://user-images.githubusercontent.com/32702764/32645630-a6af8596-c601-11e7-93bb-e9d7e06d325c.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2017-11-13 11-01-01](https://user-images.githubusercontent.com/8775448/32715134-018a2cd4-c862-11e7-96c9-5d8cadae458b.png)

**Comment by clement59** [comment]
![capture d ecran de 2017-11-13 21-23-25](https://user-images.githubusercontent.com/6576514/32747472-1a534ce4-c8b9-11e7-9b33-c0d3f413669c.png)
