### ISSUE TITLE
Inter - undefined lat au lancement de l'update adresse

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#607]
Mon use case est sur un projet que j'ai créé en Allemagne à Hamburg, Osterstrasse (== nom de rue)
Au update de l'adresses, j'ai cette erreur dans la console
![capture d ecran de 2017-11-13 17-24-10](https://user-images.githubusercontent.com/6576514/32736453-cab5eb86-c897-11e7-9200-634304be98c4.png)

**Comment by RaphaelRIVIERE** [comment]
Celui faut qu'on regarde ensemble , j'arrive pas à le reproduire

**Comment by clement59** [comment]
ok l'ai plus !
