### ISSUE TITLE
Auteur et date - fil d'actualité

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#611]
Le nom de l'auteur et la date des publications de la colonne de gauche du fil d'actualité s'affichent bizarrement.

![capture d ecran_2017-11-15_18-10-32](https://user-images.githubusercontent.com/2474636/32840209-76c2cfc2-ca30-11e7-8b65-f48f8903d671.png)

**Comment by Drakone** [comment]
J'utilise Firefox.

**Comment by clement59** [comment]
Héhé je viens de le fixer :) peux tu tester l'ami ! @Drakone

**Comment by Drakone** [comment]
C'est parfait ! Merci :)
