### ISSUE TITLE
Search city , communexion 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#612]
![capture d ecran de 2017-11-15 17-45-34](https://user-images.githubusercontent.com/8775448/32841950-e55ea70c-ca2c-11e7-8b1b-8c87e55de21b.png)

**Comment by clement59** [comment]
Pas mal mais reste un tio bug dans le breadcrum sur le niveau 2
![capture d ecran de 2017-11-17 19-54-35](https://user-images.githubusercontent.com/6576514/32963772-528bae4c-cbd1-11e7-83e1-0ed3f091616a.png)

**Comment by clement59** [comment]
Et je rajouter que le "communecter" n'est pas très clair ! Car on est sur du test aussi ici ...
![capture d ecran de 2017-11-17 19-57-33](https://user-images.githubusercontent.com/6576514/32963873-a7aea1d6-cbd1-11e7-8567-cd383d1e905c.png)

**Comment by clement59** [comment]
Outcha le refresh enleve carément les cookies : Donc on me repropose de me communecter ! ce que j'ai vraiment plus envi de faire ;) Et ensuite je vais sur mon profil qui est toujours communecté à Lille !
![capture d ecran de 2017-11-17 19-59-20](https://user-images.githubusercontent.com/6576514/32964038-25a0f076-cbd2-11e7-9b4a-0d8abe8258f8.png)
![capture d ecran de 2017-11-17 19-59-46](https://user-images.githubusercontent.com/6576514/32964058-35d71b32-cbd2-11e7-8ee7-0297e9fbcf18.png)

**Comment by RaphaelRIVIERE** [comment]
Corrrriiiigggggggggéééééééééééééééééééééééééééééééé 
@clement59 tu peux test

**Comment by clement59** [comment]
1- Je n'ai pas le popup qui me dit que je suis communecté à hamburg 
![capture d ecran de 2017-11-20 14-33-54](https://user-images.githubusercontent.com/6576514/33020820-e95563d8-cdff-11e7-8845-b2e1c755cd63.png)
![capture d ecran de 2017-11-20 14-33-51](https://user-images.githubusercontent.com/6576514/33020824-f24c0c94-cdff-11e7-8934-a1a1003b2b3a.png)
2 - Le scope de Lille est maintenant inversé (usecase ou cp et moins puissant que l'insee)
=> Ici sur le niveau le plus bas j'ai plus de résultat que sur le niveau du dessus ! (ca devrait être "lille ville entière) avec tous les cp
![capture d ecran de 2017-11-20 14-35-34](https://user-images.githubusercontent.com/6576514/33020919-495270b4-ce00-11e7-9667-228bb983373c.png)
![capture d ecran de 2017-11-20 14-35-21](https://user-images.githubusercontent.com/6576514/33020924-5014ed8c-ce00-11e7-9e64-bb79719bc138.png)
3- Bien pour le msg test de communexion, mais quand je change de page de search à agenda par ex, il perd le focus du breadcrum sur la communexion ... un peu déroutant !
![capture d ecran de 2017-11-20 14-40-02](https://user-images.githubusercontent.com/6576514/33021081-e9fb6138-ce00-11e7-8df9-dcce406369c3.png)
![capture d ecran de 2017-11-20 14-40-13](https://user-images.githubusercontent.com/6576514/33021092-eef7aa66-ce00-11e7-8f4c-3a18c089d193.png)
4 - J'ai toujours le bug au refresh => usecase, je suis communecté à lille, je vais tester la communexion de hamburg sur le search et au refresh il a oublié ma communexion ...
![capture d ecran de 2017-11-20 14-43-28](https://user-images.githubusercontent.com/6576514/33021234-6da7f6c2-ce01-11e7-8ac9-69f19dfc1e65.png)
![capture d ecran de 2017-11-20 14-43-50](https://user-images.githubusercontent.com/6576514/33021262-82aae930-ce01-11e7-939d-6dded736babd.png)

**Comment by RaphaelRIVIERE** [comment]
1 ) Fais
2 )  Cas à améliorer sur le test . mais si tu change ton adresse , c'est bon
3 ) Corriger , tout sa a cause d'un put1 de S manquant communexion.valueS ... 
4 )  Moi j'ai plus ce problème , j'arrive plus à le reproduire

**Comment by RaphaelRIVIERE** [comment]
Avec la nouvelle interface, on peut close
