### ISSUE TITLE
Update News : , il n'y a pas les tags

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#616]
1 ) J'ai une new avec un tag 
![capture d ecran de 2017-11-16 17-30-25](https://user-images.githubusercontent.com/8775448/32896359-e36e5fa6-caf3-11e7-9049-5862a74f14b5.png)

Mais quand je modif la new, le tags n'apparait  pas 
![capture d ecran de 2017-11-16 17-31-14](https://user-images.githubusercontent.com/8775448/32896419-05ac6950-caf4-11e7-8a71-1f043b314661.png)

2 ) L'input des tags n'est pas le meme que sur les autre dynform 
![capture d ecran de 2017-11-16 17-32-20](https://user-images.githubusercontent.com/8775448/32896490-30642372-caf4-11e7-8d3a-974f84218e49.png)

**Comment by clement59** [comment]
ok ca marche bien
