### ISSUE TITLE
Search by locality network

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#617]
Par contre le searchLocality ne fonctionne pas trop sur ce network : https://www.communecter.org/network/default/index?src=https://gist.github.com/Drakone/c9b890500107f9703fb3a6a8eae0d164/raw/d75c2f059a99f25204e75dded856c5a28fa73562/essreunion.json
 
![capture d ecran de 2017-11-16 18-30-14](https://user-images.githubusercontent.com/6576514/32906094-3882413a-cafc-11e7-9e31-505814c2a04b.png)

**Comment by RaphaelRIVIERE** [comment]
c'est juste pas le bon nom dans le searchLocalities

**Comment by Drakone** [comment]
Je met à jour la doc.

2017-11-17 12:20 GMT+04:00 RaphaelRIVIERE <notifications@github.com>:
