### ISSUE TITLE
Bug nombre result ne change pas with tags #search

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#618]
![capture d ecran de 2017-11-16 19-52-29](https://user-images.githubusercontent.com/6576514/32909834-efbeb080-cb07-11e7-8de6-41c8f285c94f.png)

**Comment by Drakone** [comment]
Un bug que j'ai noté sur ma feuille avec exactement le même exemple ^^.

**Comment by Drakone** [comment]
Et l'affichage de la map ne prend pas en compte le tag selectionné.
