### ISSUE TITLE
Pb notification "who is following you"

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#622]
![capture d ecran 2017-11-18 a 20 01 30](https://user-images.githubusercontent.com/29157378/32983822-58978c14-cc9b-11e7-9419-75973f8bb2f8.png)

le nom ne s'affiche pas

**Comment by clement59** [comment]
Ok c'est corrigé !

**Comment by clement59** [comment]
Merci pour le usecase !!
