### ISSUE TITLE
Notification commentaire sur une proposition

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#642]
Ça me renvoi vers cette URL : https://www.communecter.org/#page.type.projects.id.55dafac4e41d75571d848360.view.coop.room.59f5f87340bb4e03217f0087.proposal.5a12936340bb4e183b90a9bc

La proposition s'ouvre et me renvoi vers automatiquement vers le journal.

![capture d ecran_2017-11-27_15-54-45](https://user-images.githubusercontent.com/2474636/33265534-83428d28-d38b-11e7-83ca-746fe87c04e1.png)

**Comment by Kgneo** [comment]
ya eu des modif sur l'ouverture des notif DDA
normalement tout fonctionne
il faudrait tester une dernière fois et Close si tout est ok

**Comment by Drakone** [comment]
Merci
