### ISSUE TITLE
Carto - Pas d'icon carto p0i

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#644]
![pbp0i](https://user-images.githubusercontent.com/6576514/33323253-2a36bfee-d44c-11e7-8361-63959278b7b1.png)
![pb icon poi](https://user-images.githubusercontent.com/6576514/33323254-2a615498-d44c-11e7-888d-f6b51cad6e63.png)

**Comment by Kgneo** [comment]
![poi](https://user-images.githubusercontent.com/7578166/38805786-d9bb22aa-41c2-11e8-9281-466d0f9d635c.png)

**Comment by Drakone** [comment]
Oeil de lynx
