### ISSUE TITLE
Suppression dynform adresse principale adresse secondaire create / update => BuGUééééée

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#645]

**Comment by RaphaelRIVIERE** [comment]
Va falloir que tu me détail ton bug , parce que je comprend pas le titre et je viens de testé : 
Cas 1 ou j'ai juste l'addresse principal , je la supprime , c'est bon 
Cas 2 j'ai l'addresse principal et secondaire, je supprime la principale, la secondaire -> devient principal , donc c'est bon 

Du c'est quoi ton cas ? @clement59

**Comment by clement59** [comment]
Bas c'était exactement ces deux points ! 
Je pense que c'est en prod que j'ai remonté ça ... Je vais quand même retester dans la version actuelle

**Comment by clement59** [comment]
Bah y'est bueno
