### ISSUE TITLE
Agrandir l'image de couverture

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#649]
J'me rends compte qu'on ne peut pas agrandir l'image de couverture sur une page. 
L'image de couverture est souvent un moyen pour les orga de diffuser les dernières news. 
Moyen de pouvoir cliquer dessus et agrandir l'image ?

**Comment by clement59** [comment]
C'est oarcxe que c'est une ancienne ! Si tu en mets une nouvelle (rafraichi la page) tu pourras l'agrandir

**Comment by Jahne-Anders** [comment]
@clement59 tu gèèèères !

**Comment by Drakone** [comment]
Done
