### ISSUE TITLE
Map : Zürich = error / introuvable

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#652]
No Zürich on the map, que ce soit dans la version anglaise ou française
![capture d ecran 2017-12-05 a 03 41 00](https://user-images.githubusercontent.com/29157378/33587897-82939a94-d970-11e7-8e65-cf33901bc13d.png)
![capture d ecran 2017-12-05 a 03 56 46](https://user-images.githubusercontent.com/29157378/33587898-82ad9a84-d970-11e7-8602-b0b6b6c80e6e.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-02-08 11-28-06](https://user-images.githubusercontent.com/8775448/35960470-2f469d24-0cc3-11e8-89c5-6bd5999e700f.png)
ça arrive avec la nouvelle version
