### ISSUE TITLE
Recherche dans les favoris

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#655]
Impossible d'avoir des résultats via ce petit formulaire.

![capture d ecran_2017-12-12_09-34-49](https://user-images.githubusercontent.com/2474636/33869029-16df709c-df20-11e7-9a8d-c81a371b7426.png)

**Comment by clement59** [comment]
ok c'est fixé par contre j'ai modifier un bout de code qui a peut être un impact ... rapha tango
Function filterContact L737 doc element/addMembersFromMyContacts.php
![capture d ecran de 2017-12-19 23-22-18](https://user-images.githubusercontent.com/6576514/34181722-a6877afc-e513-11e7-82e8-a5c16abbcb57.png)
