### ISSUE TITLE
Warning news timeline - Empty news si only resolutions

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#660]
Si on a 6 news de résolutions d'affiler enregistrées ... alors plus rien car les news sont enlevées dans le newsConverter !
![capture d ecran de 2017-12-19 22-22-35](https://user-images.githubusercontent.com/6576514/34179425-22e32c8a-e50b-11e7-9231-e3ddea6688f7.png)

**Comment by clement59** [comment]
Ok fixé l'interprétation des ressources dans le retour du ctk ....
Reste le design directory
![capture d ecran de 2018-02-13 13-32-05](https://user-images.githubusercontent.com/6576514/36150365-bd82c85c-10c3-11e8-823e-5852728ef763.png)

**Comment by Kgneo** [comment]
je pige pas.
tu parles de ressource, mais la news parle d'une résolution, et affiche l'icon POI ?

**Comment by clement59** [comment]
Il n'y a pas de prise en compte de l'élément résolution dans le directory donc maintenant qu'on les récupére, voilà ce que ça affiche... un poi ! Sauf que c'est bien une résolution que je demande
![capture d ecran de 2018-02-22 13-41-08](https://user-images.githubusercontent.com/6576514/36539186-38a4645a-17d6-11e8-8fa2-120f5ab5c8c6.png)

**Comment by Kgneo** [comment]
je crois que c'étais le meme pb que ça : 
News sharedBy - creation de Rooms, proposal, resolution #689

**Comment by clement59** [comment]
ok y'est bon !
