### ISSUE TITLE
Bug agenda particper function

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#661]
Particper à un événement du directory (agenda)
  [ ] Je participe > erreur floopdrawer - undefined endDate in function isOldElement
 
![capture d ecran de 2017-12-20 12-49-24](https://user-images.githubusercontent.com/6576514/34234730-23d6e680-e5ed-11e7-833c-d9a2df31ca9c.png)
 [ ] Création d'un entrée undefined dans myContacts qui en continuant la navigation (exemple mon profil > mon agenda) 
    ==> Erreur dans la fonction inMyContacts (type,id) car undefined _id
![capture d ecran de 2017-12-20 13-04-27](https://user-images.githubusercontent.com/6576514/34234744-384d9758-e5ed-11e7-99aa-9acadaeae877.png)

  [ ] Si je participe à un evenement passé.. ma participation est bien prise en compte et j'ai au retour le btn de déconnexion
    [ ] Quand je clique sur le btn de déconnexion, il me dit que je suis bien déconnecté or au refresh on voit que je suis tjrs participant et le btn de déconnexion lui n'est plus visible

**Comment by RaphaelRIVIERE** [comment]
1) cas 1 corriger

**Comment by RaphaelRIVIERE** [comment]
@clement59 faut qu'on voit ensemble sur le nom d'une variable

**Comment by RaphaelRIVIERE** [comment]
Je close , clem a réglé la derniere parti
