### ISSUE TITLE
Amélioration : Teste Communexion

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#664]
Retour utilisateur : 
- Permettre de rendre le test permanent (meme quand on actualise)
- Montré que visuelement on est en mode test
- Ajouter bouton pour permettre de changer de commuxion en prennant celui du test

**Comment by Drakone** [comment]
C'est quoi l'intérêt du mode test ? Pourquoi ne pas directement faire la communexion ?

**Comment by RaphaelRIVIERE** [comment]
J'habite a la Riviere , et je veux regarder la communexion d'une autre ville sans pour autant devoir changer tout mon adresse
![capture d ecran de 2018-01-16 10-06-16](https://user-images.githubusercontent.com/8775448/34974158-f366d2a4-faa4-11e7-9331-35440f16ddae.png)

**Comment by Drakone** [comment]
La selection de scope dans la recherche n'est pas plus approprié ?

**Comment by RaphaelRIVIERE** [comment]
Avec le nouveux design, ce n'est plus d'actualité
