### ISSUE TITLE
Reselection type d'évènement

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#666]
Lorsqu'on modifie le À propos d'un évènement on doit reselectionner le type d'évènement.

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-02-26 16-42-18](https://user-images.githubusercontent.com/8775448/36671169-26541318-1b14-11e8-9e98-1aa3f7d2fb86.png)

![capture d ecran de 2018-02-26 16-42-26](https://user-images.githubusercontent.com/8775448/36671140-18c7dfea-1b14-11e8-9fdc-1fe5d83c37ed.png)
