### ISSUE TITLE
Scopes - list hotfix

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#671]
1 - Activationde deux scopes dans mes favoris qui sont les mêmes que dans ma communexion
=> Quand je reviens sur ma communexion => j'ai ces deux derniers scopes actifs
![capture d ecran de 2018-02-01 18-18-11](https://user-images.githubusercontent.com/6576514/35703187-92c24e98-079b-11e8-87a8-c42e95fd13d7.png)
![capture d ecran de 2018-02-01 18-18-07](https://user-images.githubusercontent.com/6576514/35703188-92f53e7a-079b-11e8-870f-fcbd02277113.png)
2 - Mon nom de communexion n'est pas sur mon plus petit level !!
Ici "Pas de calais" au lieu de "arras"
![capture d ecran de 2018-02-01 22-02-46](https://user-images.githubusercontent.com/6576514/35703232-b2568936-079b-11e8-9fa9-0416fa64dc32.png)
3 - Je n'ai plus de résultats pour "Hellemmes" (cp partagé avec lezennes et même insee/id que Lille)
![capture d ecran de 2018-02-01 22-00-40](https://user-images.githubusercontent.com/6576514/35703283-d924d3ec-079b-11e8-9fa4-2791622fad94.png)

**Comment by clement59** [comment]
4- Hamburg undefined (country ) dropdown search + button bread
![capture d ecran de 2018-02-02 00-03-05](https://user-images.githubusercontent.com/6576514/35708058-8d565bd2-07ac-11e8-8596-f87c038d4891.png)
![capture d ecran de 2018-02-02 00-03-03](https://user-images.githubusercontent.com/6576514/35708059-8d89a7f8-07ac-11e8-9970-9d97d72bbe29.png)

**Comment by RaphaelRIVIERE** [comment]
1 ) J'avais le bug , mais j'arrive plus a le reproduire , essaye de nouveau pour voir si tu la toujours
2 ) Corriger
3 ) Moi ça fonctionne . Mets a jour peu etre que j'avais oublié de pushé un truc
4 ) Corrigé il faut passer les batchs 
``` co2/datamigration/UpdateZoneMissingNameLevel1
co2/datamigration/UpdateZoneMissingNameLevel2
co2/datamigration/UpdateZoneMissingNameLevel3
```

**Comment by clement59** [comment]
5) Si je tapes "Hamburg" il me sors la région le "BundesLand" mais ne me sors pas la ville qui est enregistré en français "Hambourg" .. 
![capture d ecran de 2018-02-02 15-05-29](https://user-images.githubusercontent.com/6576514/35737120-bb95b3c0-082a-11e8-9193-b63593130dad.png)
![capture d ecran de 2018-02-02 15-05-25](https://user-images.githubusercontent.com/6576514/35737124-c24a3718-082a-11e8-860c-64002663e8f8.png)
Mais son vrai nom est Hamburg ... qu'est ce qu'on fait avec ce usecase ?

**Comment by clement59** [comment]
Ahahahahaaa j'ai rien dit => Si je passe en Allemand y'a tout bon il sort bien la ville d'Hamburg
Par contre ortographié en français, c'est comme si moi je tapais "Lille" et qu'il me sortait "Riejsel" tu veux une frite vin dieu !!
Bref screenshot 
![capture d ecran de 2018-02-02 15-09-03](https://user-images.githubusercontent.com/6576514/35737285-4c18205e-082b-11e8-9e2c-f4f6e4a47b06.png)

**Comment by RaphaelRIVIERE** [comment]
@clement59 c'est bon celui la on peut close ?
