### ISSUE TITLE
Btn mon réseau => redirection vers une carte vide

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#674]
![capture d ecran de 2018-02-02 17-06-28](https://user-images.githubusercontent.com/6576514/35742737-b4167358-083b-11e8-8d74-e80c261d0415.png)

![capture d ecran de 2018-02-02 17-05-43](https://user-images.githubusercontent.com/6576514/35742651-6389c94e-083b-11e8-989c-dabc78229163.png)
Alors que j'ai bien du monde dans mon network
![capture d ecran de 2018-02-02 17-07-11](https://user-images.githubusercontent.com/6576514/35742717-a490b72c-083b-11e8-808a-cfba6eed70f2.png)

**Comment by RaphaelRIVIERE** [comment]
J'ai commenté vu que ça va pas sortir dans cette version  et je retravailler dessus après a maj
