### ISSUE TITLE
Publication privée visible pour les invités

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#679]
https://www.communecter.org/#page.type.news.id.5a76e00940bb4e603340aceb

> "j'ai été invité à rejoindre ce groupe. Je n'ai rien fait pour accepter l'invitation mais je vois cette publication test "en privé" apparaître sur mon Fil d'Actualité..."

**Comment by clement59** [comment]
ah oui même débat tenu ... on a conclu que c'était bien d'avoir l'actu comme ça tu prends le temps de répondre ! Duplicate sur une autre issue
