### ISSUE TITLE
Publication impossible

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#681]
![capture d ecran de 2018-02-08 11-01-03](https://user-images.githubusercontent.com/2474636/35959662-f57ca7bc-0cbf-11e8-849c-6137e6a869c4.png)

Peu importe la portée et l'auteur impossible de publier sur https://www.communecter.org/#alternatibaNancy.

**Comment by Drakone** [comment]
@clement59 Est-ce qu'on est censé pouvoir publier au nom d'une orga en édition libre sans être membre. Car perso je peux pas. Ex : https://www.communecter.org/#alternatibaMarneEtChampignysurmarne.

**Comment by Drakone** [comment]
Et en étant membre je peux le faire. Alors que celles importée je peux pas... @RaphaelRIVIERE

**Comment by clement59** [comment]
Oui le problème vient de l'import car pas de postalCode dans les entités ... bref @RaphaelRIVIERE fait un bash demain et normalement ca devrait réglé le problème des ajout de post pour les orga venant de l'import @Drakone 
Du coup pour les suggestions/proposition, sur les permissions et le fonctionnement des news (scope), je te @Drakone  propose plus un doc et/ou issue pour converger vers une solution finale :)

**Comment by clement59** [comment]
C'est ici @RaphaelRIVIERE on ferme ?

**Comment by Drakone** [comment]
Ok c'est bon :+1:
