### ISSUE TITLE
Src video - media extract pocess [regression]

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#682]

**Comment by clement59** [comment]
to test en dév

**Comment by RaphaelRIVIERE** [comment]
ça me semble bon :)

![capture d ecran de 2018-02-27 13-51-36](https://user-images.githubusercontent.com/8775448/36721801-64489a84-1bc5-11e8-8b5c-505583d3b959.png)
![capture d ecran de 2018-02-27 13-51-22](https://user-images.githubusercontent.com/8775448/36721809-6a0fc5be-1bc5-11e8-9131-a0207269973b.png)
