### ISSUE TITLE
design form content in update info element - fait le oulahup !

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#688]
![capture d ecran de 2018-02-15 13-19-01](https://user-images.githubusercontent.com/6576514/36256367-ee191db4-1252-11e8-9e96-a458fe3199ff.png)

**Comment by Kgneo** [comment]
fait le oulahup ?
c'est quoi le pb ?

**Comment by RaphaelRIVIERE** [comment]
J'avoue je comprend pas non plus XD

**Comment by clement59** [comment]
Je pensais que l'image suffirait ;)
Le cadre noir en dessous du form est pas accès et déréglé

**Comment by RaphaelRIVIERE** [comment]
XD XD put1 il fallais le voir celui la XD XD

![capture d ecran de 2018-02-23 16-48-15](https://user-images.githubusercontent.com/8775448/36594879-6c64a690-18b9-11e8-8291-0738968c1e40.png)

J'ai pas le bug , du coup ça a surement été réglé. Check de ton coté pour voir si tu la toujours

**Comment by clement59** [comment]
yes it's good for me !!!!!!!!!
