### ISSUE TITLE
News sharedBy - creation de Rooms, proposal, resolution

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#689]
On se retrouve avec des news DDA des orga dans le filtre des news que seulement moi user j'ai posté ou chose que créé...
Du coup la on se retrouve avec des news 'Orga a créé un résolution, ou un proposition'
Parceque c'est le user qui est dans le shareby
![capture d ecran de 2018-02-16 15-21-50](https://user-images.githubusercontent.com/6576514/36311918-2acdb596-132d-11e8-8b1e-1d42c267b19b.png)

**Comment by Kgneo** [comment]
je comprend pas trop ce qui se passe en fait, l'activityStream créé pour les résolutions me semble correcte. Mais ça ne s'affiche pas bien.

ça te semble bon ça ? dans ctk/models/Cooperation.php  -  function afterSave

![capture du 2018-02-22 14-09-49](https://user-images.githubusercontent.com/7578166/36525500-6b9757b4-17fe-11e8-9754-e41cec104ad3.png)

**Comment by clement59** [comment]
ah voila c'est mieux avec le code
Enfaite dans le sharedBy il faut mettre le targetId et le targetType pour plus que ça arrive dans tes news perso

**Comment by clement59** [comment]
+ bash de data sur le sharedBy à prévoir

**Comment by Kgneo** [comment]
ok ! bon on avance !
j'ai réussi à comprendre et régler le pb d'affichage.
Donc les résolutions s'affichent bien, et s'ouvrent bien sur la bonne page
![capture du 2018-02-23 12-00-58](https://user-images.githubusercontent.com/7578166/36572692-5c5e977e-1891-11e8-91d5-868f4cba7a73.png)

**Comment by Kgneo** [comment]
reste le pb de la news qui tombe dans "mon journal" alors que l'auteur affiché est l'élément parent

**Comment by clement59** [comment]
Nop, ca dépend de ce que tu veux afficher : 
En faite si on laisse le sharedby citoyens bah le citoyens en question aura les news dans son journal perso ... 
Faut voir en faite ce qu'on veut ... après je pense qu'il faudrait revoir les news DDA (dans la prochaine version).
Genre la résolution affiché le résultat, la désaproprié du citoyens du type : 
Communecter a une nouvelle résolution avec le petit graphe un truk sympa quoi ...

Dans tous les cas, je sais pas qu'elle correction tu as émis mais j'ai toujours la news résolution en tant qu'orga, dans mon fil perso
![capture d ecran de 2018-03-03 14-26-28](https://user-images.githubusercontent.com/6576514/36934793-ef588b12-1eee-11e8-977b-4218c2388ade.png)

**Comment by clement59** [comment]
Allez
