### ISSUE TITLE
Pas de prix affiché sur les classified (directoryPanel + preview)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#697]

**Comment by Kgneo** [comment]
si si les prix sont bien affichés.
Mais toutes les annonces n'ont pas forcément de prix, donc tu as peux être regardé une annonce sans prix (à donner,ou à partager)

![capture du 2018-02-21 11-38-11](https://user-images.githubusercontent.com/7578166/36456975-d8a53a50-16fb-11e8-83d0-414643054e90.png)
