### ISSUE TITLE
ajouter les devises dans les filtres des annonces

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#698]
![devise](https://user-images.githubusercontent.com/7578166/36462840-06b07626-171a-11e8-9b39-26fc438dac22.png)

**Comment by Kgneo** [comment]
c'est bon pour les devises.

**Comment by Kgneo** [comment]
@oceatoon je maintiens qu'on ne devrait pas remettre les thématiques dans le header comme sur #search, sinon on permet des recherches qui n'ont pas de sens, du genre : 
"santé > à louer > loisir > jeux de société" 
ou "citoyenneté > à vendre > véhicule"
ou "alimentation > offre d'emplois > informatique"

on a fait des thématiques spécifiques pour les annonces, qui change en fonction de la section choisie (à donner, à vendre, à louer, emplois) à mon avis ce serait une erreur de dédoubler les thématiques globale

**Comment by Kgneo** [comment]
et pareil pour les ressources, puisqu'on a pas les thématiques dans le dynForm, on aura jamais de résultats si on recherche par thématique, sauf si par miracle le user utilise un #tag correct dans le dynForm...

**Comment by oceatoon** [comment]
L'objectif qui me semble  interessant, et sur lequel les gens réagissent 
est  de voir les annonces ou les ressource de santé, de dechet etc  
bien sur si tu focus sur les qlqs cas de figures bizarre ca marche pas 
c'est dans la globalité et les sous filtres s'amélioreront 

pour les thématiques jsutement ca devrait etre une amélioration du select tags 
d'y mettre un premiere section thématique dans la lliste

**Comment by RaphaelRIVIERE** [comment]
Je close l'issue, les devis ont été mis, pour le débat thématique sur les annonces ouvrir un dda pour ça à la limite
