### ISSUE TITLE
ouverture d'un nouveau chanel de tchat

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#700]
quand je clique sur le bouton tchat de le floopdrawer, ou dans la preview annonce ou ressource,
si le chanel n'existe pas on a ça : 
![capture du 2018-02-21 15-19-49](https://user-images.githubusercontent.com/7578166/36462961-c9b14902-171a-11e8-8650-2faaedfb6f28.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-02-27 11-50-04](https://user-images.githubusercontent.com/8775448/36716621-62e480f6-1bb4-11e8-96f8-20b7fbdda3b6.png)


ça fonctionne, peu etre que ton compte en local ne correspond pas au compte sur prod ou alors ça était corriger entre temps
