### ISSUE TITLE
carte vide sur #search

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#701]
le chargement des données sur la carte ne fonctionne plus sur les app
(ça marche sur les pages perso)

**Comment by Kgneo** [comment]
c'est bon sur #search 
je regarde pour afficher les auteurs des news sur la carte depuis le #live

**Comment by Kgneo** [comment]
c'est bon aussi pour le live

**Comment by Kgneo** [comment]
ok pour les annonces
![annoncemap](https://user-images.githubusercontent.com/7578166/36515027-a05d0bc0-17cb-11e8-829c-fbf22638b983.png)

**Comment by Kgneo** [comment]
![ressourcesig](https://user-images.githubusercontent.com/7578166/36515934-e1fdb3dc-17cf-11e8-876e-c147cd2be6d1.png)
et les ressources !

**Comment by RaphaelRIVIERE** [comment]
L'affichage fonctionne :) 

Par contre, quand on scroll on perd sur la carte la donnée déjà affiché, la carte est réinitialisé a chaque scroll et affiche les seulements les nouveaux élément

**Comment by clement59** [comment]
Ok c'est fixé ! avec la search bar de la map aussi que j'ai réglé tu peux test @RaphaelRIVIERE 
Ce serait cool qu'on lui fasse bouffer le bon nombre de result et si page le bon nombre de page (j'ouvre un enhancement pour ça)

**Comment by RaphaelRIVIERE** [comment]
Parfait :)
