### ISSUE TITLE
Search :  entraide 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#705]
Si aucun résultat  il y a "Recherche en cour qui tourne tjr "

![capture d ecran de 2018-02-21 09-55-33](https://user-images.githubusercontent.com/8775448/36465241-ae2a8004-16ed-11e8-9bfd-719a63f67c82.png)

**Comment by clement59** [comment]
Ok done ! C'étaoit commun à toutes les apps
