### ISSUE TITLE
Formulaire de connexion

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#711]
![capture d ecran_2018-02-22_11-07-11](https://user-images.githubusercontent.com/2474636/36524821-e6f3de0c-17c0-11e8-8630-654c123dcf53.png)

Quelques détails : 
- Juste "E-mail" et "Mot de passe"
- Je crée mon compte est en rouge :(

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-02-27 13-04-20](https://user-images.githubusercontent.com/8775448/36719646-0fedcb9a-1bbf-11e8-8e90-813935dabf07.png)
