### ISSUE TITLE
Menu des modules

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#712]
![capture d ecran_2018-02-22_11-18-12](https://user-images.githubusercontent.com/2474636/36525232-76e4fa04-17c2-11e8-91f4-4e57e25b1032.png)
![capture d ecran_2018-02-22_11-17-35](https://user-images.githubusercontent.com/2474636/36525236-7930fb46-17c2-11e8-87ea-c789e9e1405a.png)

Je propose qu'on laisse le menu accessible en haut où que l'on soit et qu'on le retire du bas.
Ça me perturbe un peu dans ma navigation, mais sinon c'est top :)

**Comment by RaphaelRIVIERE** [comment]
Retour d'un utilisateur : depuis co_bug

![capture d ecran de 2018-02-26 10-52-27](https://user-images.githubusercontent.com/8775448/36656804-50bf2d9e-1ae3-11e8-840d-f30cc0c1dddc.png)

**Comment by clement59** [comment]
Bah c'est permanent maintenant je close
