### ISSUE TITLE
image de profil manquante sur #annonce et #ressources

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/co2#714]
je pense que ça vient du fait qu'on est sur les modules Classified et Ressources, du coup le chemin vers l'image de profil est cassé

**Comment by Kgneo** [comment]
![capture du 2018-02-23 15-14-45](https://user-images.githubusercontent.com/7578166/36577633-8715442a-18ac-11e8-812c-d145fd73975f.png)

**Comment by Kgneo** [comment]
c'est dans le menuTop

**Comment by oceatoon** [comment]
bizare j'ai add classifieds qui marche 
mais pas ressource je regarde

**Comment by oceatoon** [comment]
j'ai réglé l'upload ya plus que l'affichage dans le panel à finir

**Comment by clement59** [comment]
Bon
