### ISSUE TITLE
L'impression doit être disponible

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#716]
L'impression doit être disponible en Allemagne, à tout moment sur n'importe quel site Internet. En ce moment, il est également inaccessible avec les défilements. Twitter résout le problème de cette façon:

![screenshot-twitter com-2018-02-23-09-08-20](https://user-images.githubusercontent.com/2099251/36584559-73347868-187a-11e8-96aa-c3ab635f891f.png)

**Comment by RaphaelRIVIERE** [comment]
@scoid , j'ai fais les modifications :)

![capture d ecran de 2018-02-27 09-27-46](https://user-images.githubusercontent.com/8775448/36712439-4522326e-1ba2-11e8-892a-6beffee643b3.png)

![capture d ecran de 2018-02-27 09-25-03](https://user-images.githubusercontent.com/8775448/36712461-5eaf88da-1ba2-11e8-93a7-faf9f9decac4.png)

**Comment by clement59** [comment]
ok le print out marche
