### ISSUE TITLE
traductions

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#717]
Je ne sais pas si nous faisons des traductions en allemand selon la même procédure.
S'il y a des objections et des suggestions d'amélioration, veuillez nous en faire part.

traduction de la page d'accueil avant le LOGIN, ainsi que des info-bulles
http://qa.communecter.org/co2#

![screenshot-qa communecter org-2018-02-23-09-48-59](https://user-images.githubusercontent.com/2099251/36587648-0d971018-1886-11e8-8b4c-f396544f2b1e.png)

![screenshot-qa communecter org-2018-02-23-10-09-41](https://user-images.githubusercontent.com/2099251/36587674-20255b72-1886-11e8-8941-0a02259211d4.png)

La page entière des statistiques n'est pas traduisible.
![screenshot-qa communecter org-2018-02-23-10-13-41](https://user-images.githubusercontent.com/2099251/36587688-29417e7a-1886-11e8-90b4-1c0f336c3045.png)

![screenshot-qa communecter org-2018-02-23-10-17-16](https://user-images.githubusercontent.com/2099251/36587706-2fa59b20-1886-11e8-8311-22693e770466.png)

![screenshot-qa communecter org-2018-02-23-10-22-24](https://user-images.githubusercontent.com/2099251/36587719-379cf918-1886-11e8-826a-495e8ba6e5db.png)

![screenshot-qa communecter org-2018-02-23-10-24-12](https://user-images.githubusercontent.com/2099251/36587729-3d465bca-1886-11e8-9b51-76c037440a03.png)

![screenshot-qa communecter org-2018-02-23-10-27-35](https://user-images.githubusercontent.com/2099251/36587738-43134932-1886-11e8-9a6f-fe2f587d1c5b.png)

![screenshot-qa communecter org-2018-02-23-10-29-25](https://user-images.githubusercontent.com/2099251/36587743-4976fc92-1886-11e8-83d7-a7a7c7417fd2.png)

![screenshot-qa communecter org-2018-02-23-10-30-12](https://user-images.githubusercontent.com/2099251/36587749-4e975884-1886-11e8-89a3-83d02817e066.png)

![screenshot-qa communecter org-2018-02-23-10-31-35](https://user-images.githubusercontent.com/2099251/36587759-53ea5eee-1886-11e8-8d9e-d77777e5c2af.png)

![screenshot-qa communecter org-2018-02-23-10-33-29](https://user-images.githubusercontent.com/2099251/36587768-59507940-1886-11e8-8d00-acbd6b7db09c.png)

**Comment by RaphaelRIVIERE** [comment]
Il y a eu plusieur traduction de faite , @clement59 en a fait pas mal 
J'en est rajouter d'autre. mail.php, common.php , coopération.php

@scoid n'hésite pas a nous redire, on en a peu etre oublié :)

**Comment by clement59** [comment]
Ok je ferme beaucoup de trad on était faite reste la page stats
