### ISSUE TITLE
Langue dans les email

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#718]
Prendre en compte les langues de l'utilisateur pour les mails

[X] Batch pour ajouter les languages aux users
[ ] Ajout dans le code pour la prise en compte des mails
[ ] Changement de langue -> update user

**Comment by RaphaelRIVIERE** [comment]
Prendre en compte les langues de l'utilisateur pour les mails

[ X ] Batch pour ajouter les languages aux users
[ X ] Ajout dans le code pour la prise en compte des mails ( Fais pour invitation et pour relance)
[ ] Changement de langue -> update user

**Comment by clement59** [comment]
ok mali si le chgmt de langue est bon pour toi alors le reste est bon pour moi
