### ISSUE TITLE
missing btn edit annonce et rsc

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#719]
je ne vois plus le btn edit  des classifieds et des ressources

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-02-27 11-52-32](https://user-images.githubusercontent.com/8775448/36716701-b86b2cf0-1bb4-11e8-888c-e060815272b8.png)

pour ressource c'est fais

**Comment by RaphaelRIVIERE** [comment]
Après avec le btn plus en bas est-ce que c'est bien utile ?

**Comment by RaphaelRIVIERE** [comment]
Comme me la fais remarquer @clement59 , j'ai devais etre  def pour cofondre ajouter et editer

**Comment by oceatoon** [comment]
- ajout des btn -> ok
- tests editions et save 
    + poi OK
    - rsc OK
    - classified KO
- test delete 
    - poi 
    - rsc
    - classified   
- check deleted images 
     - poi 
     - rsc
     - classified

**Comment by oceatoon** [comment]
il reste un ti bug sur le preview de ressource
on a pas les images, ca doit pas etre grand chose je te le laisse @Kgneo

**Comment by clement59** [comment]
Pas mal !
Edit marche bien ... C'est normal qu'on est les sections/category généré en tags ?
![capture d ecran de 2018-03-06 16-11-48](https://user-images.githubusercontent.com/6576514/37040189-81c7273a-2159-11e8-96f0-0c40917bae12.png)
Les images au edit ne sont pas regénérées dans le fineuploader...
Le delete marche impec !

**Comment by clement59** [comment]
2 -L'image de profil des classified dans les directory n'est pas chargé alors que pour ressources c'est OK

**Comment by oceatoon** [comment]
- les categ et sections sont dupliqués dans les tags , c normal, c comme ca que se fait le search 
- les images ne remonte jamais dans les edits

**Comment by clement59** [comment]
Update classifieds 
1 - ne prends pas en compte mes anciennes sections et catégorie
![capture d ecran de 2018-03-08 18-24-42](https://user-images.githubusercontent.com/6576514/37166135-884fb22e-22fe-11e8-9da1-9f741f32d617.png)
2 - Catégorie undefined dans le dynform
![capture d ecran de 2018-03-08 18-24-02](https://user-images.githubusercontent.com/6576514/37166115-78180488-22fe-11e8-9110-ecf66bb2d83c.png)

3 - Oui mais du coup quand je up ma section "Give" en  "lookingFor" le mots reste tout de même, bon niveau recherche pas d'impact (bon je chipote)!
![capture d ecran de 2018-03-08 18-24-42](https://user-images.githubusercontent.com/6576514/37166140-8f354b12-22fe-11e8-8868-8ad57249e0be.png)

**Comment by oceatoon** [comment]
1 et 2 etait lié , c t une regression

**Comment by oceatoon** [comment]
3 fait parti du gros chantier internationalisation des tags

**Comment by clement59** [comment]
walouh
