### ISSUE TITLE
bug js form point of interest "rules"

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#72]
![capture d ecran de 2017-04-27 20-33-38](https://cloud.githubusercontent.com/assets/6576514/25498593/dd2d283a-2b88-11e7-9a09-24dc3428551f.png)

**Comment by RaphaelRIVIERE** [comment]
J'ai pas réussi a reproduire le bug, sois c'est corriger , sinon tu peux le re-testé et me donner plus de détail

**Comment by clement59** [comment]
ok c'est bon j'ai plus l'erreur
