### ISSUE TITLE
Ressources : quelque bug 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#722]
1) Il y a un undefined dans le formulaire 
![capture d ecran de 2018-02-27 12-01-10](https://user-images.githubusercontent.com/8775448/36717134-5210f410-1bb6-11e8-81c6-c67c2af1ea1d.png)

2) après avoir crée la ressource, j'ai un undefined 
![capture d ecran de 2018-02-27 12-02-16](https://user-images.githubusercontent.com/8775448/36717155-67a00d66-1bb6-11e8-9f79-83b58647dae4.png)

3) si je clique sur la ressource pour afficher la modal , j'ai cette erreur
![capture d ecran de 2018-02-27 12-08-48](https://user-images.githubusercontent.com/8775448/36717347-2b581eb0-1bb7-11e8-9c19-9a838b18c75c.png)

![capture d ecran de 2018-02-27 12-08-56](https://user-images.githubusercontent.com/8775448/36717357-3592b75a-1bb7-11e8-9824-ba10c7c78af8.png)

4) Si je clique sur l'url pour acceder à la ressource , j'ai cette erreur 

![capture d ecran de 2018-02-27 12-10-58](https://user-images.githubusercontent.com/8775448/36717418-72874086-1bb7-11e8-91c9-72b37f74ca35.png)

![capture d ecran de 2018-02-27 12-11-19](https://user-images.githubusercontent.com/8775448/36717422-76f50928-1bb7-11e8-94c9-67b41d9480ee.png)

5) Pas un bug , mais amélioration si on clique sur l'url , fermer la modal automatiquement 

![capture d ecran de 2018-02-27 12-13-17](https://user-images.githubusercontent.com/8775448/36717498-b8b7cfda-1bb7-11e8-8c2f-af501dcf92fc.png)

**Comment by oceatoon** [comment]
1) et 2) c ok

**Comment by oceatoon** [comment]
3 is ok

**Comment by oceatoon** [comment]
4 c ok

**Comment by RaphaelRIVIERE** [comment]
1) C'est bon 
2) Pas fini, il reste des undefineds cas : Offre > compétition > artistique ou artisanal (surement d'autre)
![capture d ecran de 2018-03-01 13-31-48](https://user-images.githubusercontent.com/8775448/36837441-d7374a22-1d55-11e8-9c67-1ff1fcdf2382.png)

3) c'est bon 
4) Toujours la 
![capture d ecran de 2018-03-01 13-37-13](https://user-images.githubusercontent.com/8775448/36837505-07fea52e-1d56-11e8-9273-5ac0b69a6ce4.png)
![capture d ecran de 2018-03-01 13-37-08](https://user-images.githubusercontent.com/8775448/36837515-0f3a9190-1d56-11e8-9ff9-0e904da6a843.png)

5) c'est bon

**Comment by oceatoon** [comment]
je penses que c bon là

**Comment by clement59** [comment]
yes
