### ISSUE TITLE
Bug : date : event : création 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#724]
![capture d ecran de 2018-02-28 15-41-51](https://user-images.githubusercontent.com/8775448/36785921-fb42c86e-1c9d-11e8-8aa1-5406a548e1c6.png)

**Comment by clement59** [comment]
Wahou tu as réussi à le trouver ch'ti ! Well done maestro !
J'ai testé pour moi ça passe
