### ISSUE TITLE
modifier une news, en ajoutant une url  > on save > ca plante 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#725]
![image](https://user-images.githubusercontent.com/192076/36889235-9cf2fcd6-1e12-11e8-843a-6691fcaa5a36.png)

**Comment by clement59** [comment]
Tu es sur quelle orga / quel rôle liens (admin or member) ...
Mais moi ton text ....
Prod ou local ? Si tu peux tester en local ...
Mais moi l'erreur de ta console network news/updateAction.php

**Comment by clement59** [comment]
Enfaite attends la mise en prod prochaine et là si ça bug tu me mets le détail

**Comment by oceatoon** [comment]
au vue de tes message tu as trouvé la réponse a=à tes questions ,non ?

**Comment by clement59** [comment]
Non non justement ce genre de bug sont très durs à reproduire en local ! Mais j'ai fixé pas mal de chose en dév actuel donc dès qu'il y a la livraison tu me retest ce bug et dans le même contexte ;)

**Comment by clement59** [comment]
Duplicate #779 to test
