### ISSUE TITLE
project > modifier les date > impossible d'avoir ou date de déb == fin

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#726]

**Comment by clement59** [comment]
Pour les dates moi y'a bon je peux updater tranquillement.... (en local)
Par contre deux petits usecase manquant dans le edit des dates projects:
- Je dirais qu'il y a possibilité de les effacer après coup, vu qu'elles ne sont pas obligatoire après coup
- Si pas de dates à la base... quand on édite il met à jour le pannel d'affichage des dates mais elles n'apparaisent (une fois ctrl+R tout fonctionne bien )

**Comment by clement59** [comment]
Mais c'est parfait...
