### ISSUE TITLE
Orga sans type => Undefined Bug 500

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#727]
Venant d'import et autres ... 
![capture d ecran de 2018-03-03 15-23-14](https://user-images.githubusercontent.com/6576514/36935344-23a5eea2-1ef7-11e8-8472-acae507d45be.png)

**Comment by RaphaelRIVIERE** [comment]
Est-ce que on fais un batch et on mais NGO a tout ou alors on les prend cas part cas et on cheque ?

**Comment by clement59** [comment]
On est en open edition ... NGO allez boum ! Je fais tu fais ?

**Comment by oceatoon** [comment]
bon bah j'ai hacké le truc avec un onload 
```
onload : function (data) { 
								//this is a hack too a strange bug
								//this select doesn't carry it's value
								if( contextData.type == typeObj.event.col || contextData.type == typeObj.organization.col )
									$("#type").val(data.type);
							}
```
je ne comprends pas et je suis fatigué de chercher

**Comment by RaphaelRIVIERE** [comment]
Voir devLog

**Comment by clement59** [comment]
ok bon ca passe en groupe ! Dans tous les cas c'est de l'openEdition
