### ISSUE TITLE
Form event - (general) short description pas de décompte des caractères

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#732]
![capture d ecran de 2018-03-06 16-26-59](https://user-images.githubusercontent.com/6576514/37040943-4803d154-215b-11e8-88cb-7bf0c3d9f062.png)

**Comment by clement59** [comment]
Le mek me le régle une heure avant ! Boumshaka !

**Comment by RaphaelRIVIERE** [comment]
Bim bam boum :p

**Comment by 360fun** [comment]
Would be nice to have a longer description, in order to describe extensively the event program.
Btw I created an event and nothing happened: I lost everything. :(
