### ISSUE TITLE
DDA Texte riche dans les champs textarea

### ISSUE THREAD

**Issue by numahell** [pixelhumain/co2#735]
Permettre l'édition en texte riche dans les champs textarea (ou en markdown, mais rester cohérent avec le reste du site)

**Comment by oceatoon** [comment]
les formulaires c'est fait demain
je gere l'affichage , 
ce sera disponible dans la prochaine livraison lundi en PROD si tout va bien demain 
sinon on test en QA demain

**Comment by numahell** [comment]
Cool si c'était prévu, mais dans mon esprit c'était pas pressé :)

**Comment by Drakone** [comment]
C'est la fête du close
