### ISSUE TITLE
Réseaux sociaux libres

### ISSUE THREAD

**Issue by numahell** [pixelhumain/co2#737]
Dans "A propos" d'une page, il manque les réseaux sociaux libres Diaspora et Mastodon. Ce sont également des liens.

**Comment by oceatoon** [comment]
ils arrivent dans la nouvelles version deja sur qa.communecter.org
je ferme donc l'issue

**Comment by oceatoon** [comment]
il seront disponibles dans la version imminente 
deja dispo sur qa.communecter.org
