### ISSUE TITLE
Logo sur la carte

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#744]
![capture d ecran_2018-03-11_18-35-34](https://user-images.githubusercontent.com/2474636/37254726-56636b66-255b-11e8-93e2-75cbd866b656.png)

Alors qu'ils sont référencées en tant qu'entreprise c'est le logo association qui apparaît dans la liste.

**Comment by Drakone** [comment]
C'était sur restovegan.re mais c'est revenu : 
![capture d ecran_2018-03-16_10-11-03](https://user-images.githubusercontent.com/2474636/37506310-ac6e9ef4-2902-11e8-8f9e-1b688da87957.png)

**Comment by RaphaelRIVIERE** [comment]
c'est général a tout Communecter
