### ISSUE TITLE
Couleur des liens

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#745]
![capture d ecran_2018-03-12_11-18-32](https://user-images.githubusercontent.com/2474636/37270213-6843d01e-25e7-11e8-8a7c-8668a560449c.png)

**Comment by clement59** [comment]
Pour moi c'est bon ...
Un peu plus de context, tu as un filtre bleu sur ton écran ? :P 
![capture d ecran de 2018-03-12 21-11-50](https://user-images.githubusercontent.com/6576514/37307107-20272ce2-263a-11e8-938d-0de97c8c838c.png)

**Comment by Drakone** [comment]
Je tourne sur Archlinux.
Ça ne fonctionne pas avec Firefox et Chromium mais sur Tor Browser (basé sur Firefox mais me change mon IP entre autre) ça s'affiche comme il faut !

**Comment by Drakone** [comment]
En prod c'est OK.
![capture d ecran_2018-03-15_09-59-12](https://user-images.githubusercontent.com/2474636/37446733-dc89a460-2837-11e8-9129-1e825b0e70d6.png)
