### ISSUE TITLE
création ressource

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#747]
J'ai créé une ressource mais une fois validée elle n'apparait pas. J'ai réactualisé et c'est OK.

**Comment by Drakone** [comment]
Un petit raccourcis comme pour l'ajout de point de contact ou la création d'évènement serait sympa.
![capture d ecran_2018-03-12_12-18-51](https://user-images.githubusercontent.com/2474636/37272403-f363e7a8-25ef-11e8-9aac-8b107da7ec7b.png)

**Comment by clement59** [comment]
ok j'ai tout testé ca s'actualise et tu parles de ce bouton ?
![capture d ecran de 2018-03-14 15-23-25](https://user-images.githubusercontent.com/6576514/37408124-bffcbe28-279b-11e8-8e8a-4495af2dcdc9.png)
![capture d ecran de 2018-03-14 15-22-05](https://user-images.githubusercontent.com/6576514/37408145-c744e5f2-279b-11e8-9dcc-6d0e10c054a7.png)
Allez hop one more
