### ISSUE TITLE
ressource à ouvrir

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#748]
J'arrive pas à ouvrir cette ressource qui m'a l'air fort intéressante pourtant.
![capture d ecran_2018-03-12_11-30-42](https://user-images.githubusercontent.com/2474636/37270689-28eefa36-25e9-11e8-8162-26e63fa70199.png)

**Comment by clement59** [comment]
wahwahawhah
Moi aussi elle m'intéresse ! Mais effectivement ... Erreur 500
undefined parentType @oceatoon tout est dans le code de permission d'edition de la ressource ligne 101 de ressoyurces/views/co/preview ...
Au passage c'est demander une permission sur le PzéroI ... 
![capture d ecran de 2018-03-12 21-07-40](https://user-images.githubusercontent.com/6576514/37306968-b77f8c2a-2639-11e8-9294-39c2bb4db8c1.png)

**Comment by clement59** [comment]
ok ca s'ouvre et correction url parent et droit d'édition good
![capture d ecran de 2018-03-13 15-40-08](https://user-images.githubusercontent.com/6576514/37348686-081642aa-26d5-11e8-8da1-6cb40a22f863.png)
