### ISSUE TITLE
Type orga non initialisé dans le edit / Suggestion apropos

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#75]
![capture d ecran de 2017-04-28 16-22-45](https://cloud.githubusercontent.com/assets/6576514/25532873/13557754-2c2f-11e7-9251-6870ed6cb656.png)
++ SUGGESTION
LES descriptions sont mis en premières...
Mais je sais pas si c'est une bonne idée ... à vide oui !! Mais une fois remplie. Va falloir aller chercher loin pour voir les tags l'email le site le nom etc ? wdyt ? @pixelhumain/dev

**Comment by oceatoon** [comment]
on s'y ait mis a 2 pour te comprendre
et heureusement que Rapha etait là :)

**Comment by clement59** [comment]
Garde le sous le coude, y'a comme un truk entre rapha et moi pour qu'il me comprenne si bien !

**Comment by RaphaelRIVIERE** [comment]
<3

**Comment by RaphaelRIVIERE** [comment]
Depuis la page d'un éléments ça fonctionne pas

**Comment by RaphaelRIVIERE** [comment]
c'est bon corriger
