### ISSUE TITLE
Zoom - dézoom bannière

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#750]
Il se passe rien au clique.

![capture d ecran_2018-03-12_11-37-17](https://user-images.githubusercontent.com/2474636/37270907-117a4062-25ea-11e8-8b49-104ce8c90b2e.png)

**Comment by oceatoon** [comment]
j'ai testé ca marchait bien 
peut etre que ton image n'est pas assez grande  ?

**Comment by clement59** [comment]
@Drakone c'est normal que tu ne puisse pas dézoomer ton image et à sa limite de taille pour le zoom je t'invite à retester ...

**Comment by Drakone** [comment]
Ça fonctionne avec une grande image.
