### ISSUE TITLE
Recherche pour invitation

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#751]
ZIBEL : OK
![capture d ecran_2018-03-12_11-40-50](https://user-images.githubusercontent.com/2474636/37271020-972adbae-25ea-11e8-9b7f-f504d5e323dc.png)

Julien : KO
![capture d ecran_2018-03-12_11-41-42](https://user-images.githubusercontent.com/2474636/37271037-a5dc0196-25ea-11e8-9375-caaa17300e40.png)

**Comment by clement59** [comment]
well done
