### ISSUE TITLE
Sous-catégorie annonce de loisirs

### ISSUE THREAD

**Issue by Fanie-reunion** [pixelhumain/co2#753]
![capture d ecran de 2018-03-12 11-44-07](https://user-images.githubusercontent.com/32702764/37271139-1bef8ede-25eb-11e8-8abc-d3206b665f12.png)

**Comment by Fanie-reunion** [comment]
il n'y a aucune sous-catégorie pour les annonces à donner dans la catégorie loisirs

**Comment by clement59** [comment]
ok c'est good ici et tester reste le usecase des offres d'emplois #763
