### ISSUE TITLE
Sous-catégorie des annonces indéfinis 

### ISSUE THREAD

**Issue by Fanie-reunion** [pixelhumain/co2#754]
Les sous-catégories des annonces sont indéfinis sauf pour les offres d'emplois
![capture d ecran de 2018-03-12 11-44-07](https://user-images.githubusercontent.com/32702764/37271484-825d3b52-25ec-11e8-9940-e6f5e1ee57c0.png)

**Comment by clement59** [comment]
duplicate #763 Maintenant c'est les offres d'emplois qui plante
