### ISSUE TITLE
Ajouter un contact

### ISSUE THREAD

**Issue by sittiharouna** [pixelhumain/co2#755]
les onglets en dessous de "ajouter un contact" ne fonctionnent pas

**Comment by clement59** [comment]
Hello sitti,
Peux tu me mettre un imprim écran. Je vois pas trop de quels onglets tu parles ?

**Comment by oceatoon** [comment]
les bouton de changement de format , liste , ou block

**Comment by clement59** [comment]
ah bah wi forcément :) ca existe encore contact :P
