### ISSUE TITLE
Ajouter "abonnés" et "projetct" sur oragnisation 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#76]
à déclinner sur projet (abonnés et pourquoi pas projet) et events (invités, participants et sous événements)
![capture d ecran de 2017-04-28 17-37-49](https://cloud.githubusercontent.com/assets/6576514/25536109/ce31543a-2c39-11e7-9568-eef279df1a86.png)

**Comment by oceatoon** [comment]
- faudrait peut etre expliquer la différence entre abonné et membres 
- membres est plus important et du coup devrait apparaitre en 1er non ?
