### ISSUE TITLE
catégorie des annonces ''undefined''

### ISSUE THREAD

**Issue by Lamonge** [pixelhumain/co2#763]
recent:///c2082a846174e956a3ac405d5aa64495

catégorie des annonces ''undefined''

**Comment by clement59** [comment]
Pour les catégories, ça m'a l'air bon sauf pour emplois !
Le dynform vrille un peu 
![capture d ecran de 2018-03-12 20-23-36](https://user-images.githubusercontent.com/6576514/37305068-93d81dd8-2633-11e8-9fab-01c7158329e1.png)

**Comment by oceatoon** [comment]
![image.png](https://zube.io/files/pixelhumain/6c8a4cb296455079d2931c5550b6a06e-image.png)

**Comment by oceatoon** [comment]
ca me semble bon de mon coté , tu confirme @clement59

**Comment by clement59** [comment]
Bah voilà voila
