### ISSUE TITLE
Bug affichage 

### ISSUE THREAD

**Issue by Alexandre97400** [pixelhumain/co2#764]
# Il y a un problème d'affichage de l'image profil sur les urls :

- http://qa.communecter.org/#annonces
- http://qa.communecter.org/#ressources

![screenshot from 2018-03-12 14-13-59](https://user-images.githubusercontent.com/37287404/37278495-512a6a5e-2601-11e8-8660-274199567ea2.png)

qui par défault devrait être  : 

![screenshot from 2018-03-12 14-31-27](https://user-images.githubusercontent.com/37287404/37278764-337fdd1c-2602-11e8-867d-3381dabd5ab6.png)

**Comment by clement59** [comment]
Tu l'avais pas réglé celle la ? @oceatoon

**Comment by clement59** [comment]
Avec plaisir monsieur
