### ISSUE TITLE
Bug : notification : nouveau comptes

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#768]
Si tu crée un nouveau comptes.
Tu a une erreur pour quand tu essayer de voir tes notifications

faut je dit a Alex de mettre les images

**Comment by clement59** [comment]
ahaaa c'est un peut vite comme attribution ! C'est les notifs DDA qui bugs ;) Allez je prends quand même ...

**Comment by clement59** [comment]
pas tout a fait 
![capture d ecran de 2018-03-14 15-10-29](https://user-images.githubusercontent.com/6576514/37407425-ea879340-2799-11e8-80ba-2a1ddf77541d.png)

**Comment by clement59** [comment]
Ok maintenant c'est bon
![capture d ecran de 2018-03-14 15-13-20](https://user-images.githubusercontent.com/6576514/37407563-473d3c34-279a-11e8-9708-b04337f47eac.png)
