### ISSUE TITLE
Notif DDA actions - ne renvoie vers rien

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#773]
![capture d ecran de 2018-03-15 14-34-03](https://user-images.githubusercontent.com/6576514/37466438-074fd8c4-285e-11e8-8f6c-9e7b337a1da4.png)

Enfaite j'ai réussi à l'avoir avec 3-4 click dessus et sur trois appels ctk une renvoie une erreur
![capture d ecran de 2018-03-15 14-43-01](https://user-images.githubusercontent.com/6576514/37466923-347b99f4-285f-11e8-93be-ba67ce605a96.png)
![Uploading Capture d'écran de 2018-03-15 14-42-54.png…]()

**Comment by Kgneo** [comment]
lé bon pour moi
