### ISSUE TITLE
Chart CO2 to test !!!

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#78]

**Comment by clement59** [comment]
nos valeurs > fini de remplir > pas de reload #97

**Comment by Kgneo** [comment]
l'intro de ce formulaire n'est pas fini
compléter les paragraphes en dessous des boutons "bien-commun" et "libre"

![valeurs](https://cloud.githubusercontent.com/assets/7578166/25806583/6ad238c8-344f-11e7-9c53-b314a6ffc5b6.png)

**Comment by clement59** [comment]
Ok fait ! je close !
![capture d ecran de 2017-05-16 18-54-05](https://cloud.githubusercontent.com/assets/6576514/26121189/bc43562c-3a73-11e7-838a-fe88d8300352.png)
![capture d ecran de 2017-05-16 18-52-00](https://cloud.githubusercontent.com/assets/6576514/26121196/c10c4b96-3a73-11e7-901d-73cde0c018a7.png)

**Comment by Kgneo** [comment]
beaucoup mieux :)
je vois encore quelques petits détails de design à finir, je passerai dessus si je trouve un ptit moment
