### ISSUE TITLE
Network - filtrage sur la list (pas de mise à jour et l'indiucateur de recherche en cours peu visible)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#782]
![capture d ecran de 2018-03-15 17-01-11](https://user-images.githubusercontent.com/6576514/37475283-9b36f3ec-2872-11e8-8383-6bbe5f2698e4.png)

**Comment by RaphaelRIVIERE** [comment]
J'ai mis en mode block par defauts , parce que les lists ne sont pas géré sur la gestion des tags

**Comment by Drakone** [comment]
C'est googoogoooddddddd
