### ISSUE TITLE
Network - carto des tiers lieux double id sub-menu-left

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#783]
Un pour les filtres villes
Et un pour les filtres au dessus gestion avancements etc

**Comment by RaphaelRIVIERE** [comment]
J'ai rien compris

**Comment by clement59** [comment]
Normale c'est corriger :p 
Tu avais ca:
if(tagsnetwork)
 <div id="sub-menu-left>
      $.each(tagsNetwork ....
</div>
if(scopefilters)
 <div id="sub-menu-left>
      $.each(scopeFilters ....
</div>
