### ISSUE TITLE
Chart not defined - DDA communecterTesteur

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#784]
https://www.communecter.org/#communecterTesteurs.view.coop.room.59ca33b540bb4e0770991ba0.resolution.59ca341840bb4e5070991b9c
![capture d ecran de 2018-03-15 17-44-23](https://user-images.githubusercontent.com/6576514/37477707-a87fd888-2878-11e8-9032-352ee871b55d.png)
![capture d ecran de 2018-03-15 17-44-14](https://user-images.githubusercontent.com/6576514/37477709-a907ac2c-2878-11e8-97d1-a8ff6a4d570b.png)

**Comment by Kgneo** [comment]
je dirais que c'est ok celle-ci 
c'était à l'ouverture d'une proposal en preview ?
si c bien ça tu peux close

**Comment by clement59** [comment]
Yep boy !
