### ISSUE TITLE
Accès au résultat

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#798]
Au clic sur le résultat ça me réactualise la page.

https://www.communecter.org/#commentSeCommunecter
https://www.communecter.org/#page.type.organizations.id.59bac8e940bb4e7872da291a

![peek 20-03-2018 10-06](https://user-images.githubusercontent.com/2474636/37638516-b74bdc2a-2c26-11e8-85ad-a93e3b9d1b47.gif)

**Comment by clement59** [comment]
ok good trouvé
c'est parcequ'on utilise #comment dans notre tableau urlCtrl.loadableUrl ...
D'ailleurs si y'en a un qui rentre le slug #gallery ou encore #element ça va bugguer pareil .... Donc faudrait voir ce qu'on fait de ces usecase @oceatoon @RaphaelRIVIERE 
Dans tous les cas, cette orga est fixé et utilisable au prochain up

**Comment by Kgneo** [comment]
lé bon
