### ISSUE TITLE
Changer le message de connexion

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#8]
Il faut changer le message de connexion, je pense qu'il était la pour Kgougle, mais ne correspond pas a Communecter

![capture d ecran de 2017-04-10 15-18-50](https://cloud.githubusercontent.com/assets/8775448/24859341/2b9f42d6-1e01-11e7-83ff-214c1ae1c72e.png)

**Comment by clement59** [comment]
J'ai craqué ... J'aime trop notre petite anime !!
![capture d ecran de 2017-05-10 20-07-44](https://cloud.githubusercontent.com/assets/6576514/25913894/aac6a04a-35bc-11e7-876f-e95f2993bd90.png)
![capture d ecran de 2017-05-10 20-07-41](https://cloud.githubusercontent.com/assets/6576514/25913899/b0559908-35bc-11e7-92fa-b3f15c4c4528.png)

**Comment by clement59** [comment]
Pour l'inscription, j'ai dupliquer en changeant le message et surtout en mettant un couleur success au btn d'inscription parceque le rouge sa fait un peu peur de cliquer dessus ;)
![capture d ecran de 2017-05-10 20-16-45](https://cloud.githubusercontent.com/assets/6576514/25914193/b6a78a4a-35bd-11e7-86d3-6b65a8cab982.png)
![capture d ecran de 2017-05-10 20-16-02](https://cloud.githubusercontent.com/assets/6576514/25914197/bb5617e6-35bd-11e7-9e7b-76f7babf4308.png)

**Comment by RaphaelRIVIERE** [comment]
Top , j'ai modifier le message de bienvenue 
Bienvenue sur la version co2 (1.0) => Bienvenue sur la version CO2 (0.2)

vu que CO2 c'est la 0.2 et pas la 1.0
