### ISSUE TITLE
Bug save proposal - get all dynform

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#808]
![capture d ecran de 2018-03-22 16-54-26](https://user-images.githubusercontent.com/6576514/37781826-ce791bf2-2df1-11e8-9ca8-80f9b56ef764.png)

Déroulé des opérations qui m'ont amené à ce bug : 
1 - Element avec DDA vierge => j'entre dans l"espace CO (j'arrive sur la page de bienvenu)
2 - Je crée un room
3 - Création d'un proposition dans la foulé en cliquant  sur le btn a coté du label proposition
4 - Au save - tout passe en get et boum badaboum

**Comment by clement59** [comment]
Bon celui là à l'air réglé ... I hope so 
J'en ai un autre !
Je n'ai pas room sur la gauche
![capture d ecran de 2018-03-30 11-15-15](https://user-images.githubusercontent.com/6576514/38132555-d21fa04e-340b-11e8-9b69-83a855045252.png)
![capture d ecran de 2018-03-30 11-15-23](https://user-images.githubusercontent.com/6576514/38132559-d6692da0-340b-11e8-87f1-e22437c8f322.png)
![capture d ecran de 2018-03-30 11-15-27](https://user-images.githubusercontent.com/6576514/38132563-d90c7256-340b-11e8-8032-11c0b3d1691c.png)
![capture d ecran de 2018-03-30 11-16-18](https://user-images.githubusercontent.com/6576514/38132567-db6c0700-340b-11e8-861c-424442c56796.png)

**Comment by Kgneo** [comment]
bug lié à l'idParentRoom
réglé ensemble avec @clement59
