### ISSUE TITLE
Ajout level scope news avec accent dans le nom (ex : Dijon)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#809]
![capture d ecran de 2018-03-22 16-59-42](https://user-images.githubusercontent.com/6576514/37782612-9fb772e4-2df3-11e8-8cf3-3a4143ff2738.png)

**Comment by clement59** [comment]
Bug présent sur la recherche aussi du coup comme depuis un moment les pauvres sur Marseille et le Dijonnais ils vont avoir du mal à communecter ;)

**Comment by RaphaelRIVIERE** [comment]
Corriger, obliger de revoir un peu le process mais c'est good :)

**Comment by Drakone** [comment]
Bon je comprend toujours pas le nom de cette issue... Il n'y a pas d'accent dans Dijon... Mais ça fonctionne.
