### ISSUE TITLE
Bouton inutile ?

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#812]
C'est sur mon fil d'actualité perso. Lorsque je clique en à gauche de la publication (engrenage) il se passe rien.
![capture d ecran_2018-03-23_15-12-07](https://user-images.githubusercontent.com/2474636/37826454-ee26ab34-2eac-11e8-8854-c7a1dba7e953.png)

**Comment by clement59** [comment]
+1 corrigé

**Comment by Drakone** [comment]
Oki
