### ISSUE TITLE
Accès direct documentation interne

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#813]
Je cherchai un moyen de renvoyer des gens vers la doc internet.
Mais lorsque j'utilise cet URL ça me fait planter l'affichage : https://www.communecter.org/#default.view.page.index.dir.docs

![capture d ecran_2018-03-23_16-12-53](https://user-images.githubusercontent.com/2474636/37828600-636dc6f4-2eb5-11e8-9a76-868c0bf23996.png)

**Comment by clement59** [comment]
To test l'ami !!

**Comment by clement59** [comment]
enfin quand la prod sera up ... du coup tu trouveras toutes les urls dans la doc 
c'est des urls type #docs.page.partners.dir.panels
ou  #docs.page.openatlas.dir.fr

**Comment by Drakone** [comment]
Trop bien, ça me servira, pour sûr.
