### ISSUE TITLE
erreurs d'orthographe dans la traduction anglaise

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#817]
![screenshot-www communecter org-2018-03-26-09-58-39](https://user-images.githubusercontent.com/2099251/37893952-d3b1cf5e-30dc-11e8-9ef5-66949d8ffd03.png)

" For Who ?"  devrait être "For whom?"

**Comment by clement59** [comment]
Corrigé ! J'ai mis la correction dans le doc de l'ami :)
![capture d ecran de 2018-03-27 15-42-07](https://user-images.githubusercontent.com/6576514/37971141-82ad7cee-31d5-11e8-9e8e-6d855d9cf7be.png)
![capture d ecran de 2018-03-27 15-40-56](https://user-images.githubusercontent.com/6576514/37971142-82cae676-31d5-11e8-9a1d-17a5ad4900ee.png)
