### ISSUE TITLE
meilleur lien vers la syntaxe Markdown

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#830]
![screenshot-www communecter org-2018-04-01-12-07-39](https://user-images.githubusercontent.com/2099251/38172056-806884b4-35a5-11e8-8ecc-3e2a1ebb0c3a.png)

Ce serait bien si le lien web était mieux marqué par exemple avec style="text-decoration : underline ;".

Le lien devrait être adapté aux versions internationalisées :

Anglais : https://daringfireball.net/projects/markdown/syntax ou https://en.wikipedia.org/wiki/Markdown

Français : https://michelf.ca/projets/php-markdown/syntaxe/ ou https://fr.wikipedia.org/wiki/Markdown

Allemand : http://markdown.de/syntax/ ou https://de.wikipedia.org/wiki/Markdown

Espagnol : https://markdown.es/sintaxis-markdown/ ou https://es.wikipedia.org/wiki/Markdown

**Comment by RaphaelRIVIERE** [comment]
@scoid c'est fais , tu pourrais traduire la ligne 39 de ce fichier s'il te plait : https://github.com/pixelhumain/pixelhumain/blob/master/ph/protected/messages/de/form.php 

Merci d'avance :)

**Comment by scoid** [comment]
exécuté. :-)

**Comment by RaphaelRIVIERE** [comment]
Désolé j'avais  oublié de valider les pull request
![capture d ecran de 2018-04-19 15-48-28](https://user-images.githubusercontent.com/8775448/38989823-20ffc166-43e9-11e8-8e16-176bb40de850.png)

Sa sera mis en ligne Lundi ou Mardi :)
