### ISSUE TITLE
Light Panel element - Directory d'un élément - manque les statuts admin ... en attente etc 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#836]
![capture d ecran de 2018-04-03 10-49-58](https://user-images.githubusercontent.com/6576514/38239366-c4dbafc6-372c-11e8-9bd5-c209617cf828.png)
![capture d ecran de 2018-04-03 10-50-35](https://user-images.githubusercontent.com/6576514/38239395-db7727d8-372c-11e8-8d58-b7880761d2e1.png)

**Comment by Kgneo** [comment]
je vois pas de quel bouton tu parles

**Comment by Kgneo** [comment]
![capture du 2018-04-10 18-02-35](https://user-images.githubusercontent.com/7578166/38540968-61423724-3ce9-11e8-8ef4-3ce7e793da32.png)

**Comment by Kgneo** [comment]
done
