### ISSUE TITLE
Groupe->communauté->rôles-> ?

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#848]
![capture d ecran 2018-04-12 a 16 16 59](https://user-images.githubusercontent.com/29157378/38676758-16cf0cc8-3e6d-11e8-85b7-648c3e6f26ac.png)

lorsque je clique sur animateur (1) y a toujours tous les rôles qui s'affichent sans distinction. 
j'ai réessayé à deux heures d'intervalles bug is still here 

@clement59

**Comment by Drakone** [comment]
Pourquoi c'est en test ?
Ça ne fonctionne pas sur aucun des serveurs.

**Comment by clement59** [comment]
ca arrive

**Comment by Drakone** [comment]
Au top la roulotte.
