### ISSUE TITLE
Edit infos générales - email non initiés dans le dynform

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#849]
![capture d ecran de 2018-04-12 15-03-43](https://user-images.githubusercontent.com/6576514/38678950-c35d28b8-3e62-11e8-9cb8-ec7bd20bd049.png)
![capture d ecran de 2018-04-12 15-03-40](https://user-images.githubusercontent.com/6576514/38678951-c37b9f64-3e62-11e8-9abe-ce7598982a36.png)

**Comment by Drakone** [comment]
Nickel chrome
