### ISSUE TITLE
Liste - description courte

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#867]
C'est pas censer être les descriptions courtes qui apparaissent à ce niveau ?
C'est la liste des membres d'une orga.

![capture du 2018-04-18 16-12-38](https://user-images.githubusercontent.com/2474636/38931296-bee4260e-4323-11e8-9b54-c0735860ba85.png)

**Comment by RaphaelRIVIERE** [comment]
+1

**Comment by Drakone** [comment]
Tip top je close
