### ISSUE TITLE
Click sur notif = ça ne marche pas

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#878]
yo yo ça fait plusieurs fois que j'ouvre le menu déroulant des notifs, et lorsque je clique sur l'une d'elles la page concernée ne s'ouvre pas. strange

**Comment by clement59** [comment]
Hello @Jahne-Anders ! Peux tu dire qu'elle notif ? @Drakone vient de nous en remonter une qui est en lien avec des notifs DDA qui on un nouveau système car on affiche les preview DDA mais peux tu confirmer que c'est bien de celle-ci dont on parle (DDA = proposal , résolution, actions, rooms)

**Comment by Jahne-Anders** [comment]
oui c'est bien DDA effectivement

**Comment by clement59** [comment]
duplicated #875

**Comment by clement59** [comment]
Jarrive po à reproduire @Jahne-Anders !
Tét un screenshot de la notif exactement?
