### ISSUE TITLE
Version co stagnante

### ISSUE THREAD

**Issue by Jahne-Anders** [pixelhumain/co2#879]
j'étais chez un pote récemment qui s'est inscrit sur communecter il ya deux versions de cela. Qd il m'a dit qu'il n'utilisait pas communecter parce que ça prenait trop de temps jlui ai dit qu'à l'heure acutelle ct bcp plus rapide + moins de bugs. En créant un event sur son compte, j'ai pris trois plombes pour le faire ! je ne pouvais même pas entrer "la réunion" pour l'adresse ou encore "saint-leu"
j'ai galéré pour mettre une photo de couverture, en vain 
'fin bref, on aurait dit que son communecter était resté figé dans le passé. 
On le faisait depuis un mac et sur le nav. Chrome

**Comment by oceatoon** [comment]
interessant
je ne sais pas comment c'est possible mais ca me semble un bon cas d'etude
perso un de mes objectifs de l'année est de faire une verison decoupé ,
light et rapide

**Comment by scoid** [comment]
Bonjour Jahne, je vois des contributions permanentes au code dans github..... Je crois que tous les développeurs aimeraient accélérer le CO. J'ai aussi l'impression que je préfère l'utiliser pour ma place aujourd'hui plutôt que demain. Mais sans incitations ou développeurs supplémentaires, les choses ne peuvent pas aller plus vite pour le moment. Soyez patient, je pense que votre contact avec le CCC a été une bonne contribution pour mieux faire connaître le projet au moins là-bas. Et les arguments de la CCC au début de l'année concernant la sécurité sont également plausibles.
Communecter semble être un pionnier en matière d'interopérabilité, établissant un nouveau standard de qualité pour ce type de logiciel. Il s'agit d'un nouveau territoire et d'une expérience dont d'autres peuvent apprendre et changer le paysage des applications de réseautage social. Le CO aura une influence sur la question de savoir s'il est actuellement applicable ou s'il s'agit encore d'un prototype. C'est déjà une démonstration, qui se souvient de l'éditeur web Amaya construit pour démontrer les standards w3c ? 
Nous devrions mettre davantage cette qualité au premier plan et interagir davantage avec les projets concernés. (Wikidata, Nominatim, etc.)
Il s'améliorera certainement et le projet sera structurellement adapté à un développement plus agile. S'il vous plaît, ne perdez pas courage.

**Comment by Jahne-Anders** [comment]
ce qui est étonnant  c'est que de mon ordi tout est quasi opérationnel, j'ai pas de pb à entrer des adresses. J'ai remarqué aussi que certaines fonctionnalités étaient plus opérationnelles d'un navigateur à un autre : 
ex : sur firefox je ne peux ouvrir mes notif mais sur chrome ça marche 
sur chrome

**Comment by Jahne-Anders** [comment]
@scoid oui toutes les améliorations sur communecter montrent à quel point le projet se développe à point et c'est tellement réjouissant de voir ça, pour moi l'intérêt d'utiliser CO grandit de jour en jour et l'apport de contributions comme les tiennes donne vraiment envie de continuer l'aventure !! lentement mais sûrement :) 
pour le CCC je n'ai pas eu de nouvelles par mail après mon départ, sais tu s'ils ont un chat sur lequel on peut communiquer ?

**Comment by scoid** [comment]
Hallo @Jahne-Anders ,

https://www.ccc.de/de/contact <-- hier stehen alle Kontaktmöglichkeiten

https://www.ccc.de/debate <-- hier finden Debatten statt

https://fdik.org/debate-faq <-- dort ist noch eine Anleitung zur
Benutzung der Mailingliste für Debatten. Der CCC mag off-topic Themen
gar nicht und liebt kurze präzise Fragen und gibt auch solche Antworten
(leider oft zu kurz und unverständlich)

ein wenig persönlicher, weil regionaler sind die
https://www.ccc.de/de/club/erfas Erfa-Kreise (Erfahrungs-Kreise). Hier
sind nur Webseiten aufgelistet und die Kontakte in den Webseiten
versteckt ...

Außer dem CCC gibt es noch die Open Knowledge Foundation, welche
CiviTech und Demokratie-Werkzeuge fördern will. Hier sind regionale
Treffpunkte in Deutschland https://codefor.de/ mit Kontakten.

Security-Experten sind leider sehr stark nachgefragt und haben oft wenig
Zeit.

Gruß + alles Gute,
Stephan.


Am 24.04.2018 um 10:36 schrieb Jahne-Anders:
