### ISSUE TITLE
Il manque une description des projets soutenus.

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#890]
![screenshot-www communecter org-2018-05-04-10-29-07](https://user-images.githubusercontent.com/2099251/39619534-8171ed44-4f88-11e8-99d1-7eceaeb8f973.png)

**Comment by clement59** [comment]
Yes bien vu @scoid ! Ceux sont deux projets qui ont un statuts de deleted ! 
Je me permets juste de poser la question à @scoid @oceatoon si quelqu'un a lié des projets ?

**Comment by scoid** [comment]
https://www.communecter.org/co2#@germanTranslationOfCommunecter est un sous-projet de coTranslate.

**Comment by clement59** [comment]
Aouuuuuuuuuuuuutch les ids ne sont pas boooooooooooooooooooooon !!!
J'ai up à la main pour germanTanslation !! As tu le deuxième projet @scoid ?  
I will search for the error right know !!

**Comment by clement59** [comment]
j'arrive pas à reproduire ;(

**Comment by clement59** [comment]
Ok j'ai quand mếme mis un parefeu sur le count ! donc il n'y a plus d'erreur ! 
Par contre il y avait bien un 2eme projet dans la liste ... J'ai recollé le germanTranslate mais dites moi si vous connaissez le 2eme et si vous avez une tit intuition de où ca pourrait venir @oceatoon @scoid

**Comment by scoid** [comment]
Je ne peux plus dire avec certitude si j'en ai essayé un autre. Je suis désolée.
