### ISSUE TITLE
régression #live

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#90]
![capture d ecran de 2017-05-01 19-05-04](https://cloud.githubusercontent.com/assets/6576514/25586794/4fb41754-2ea1-11e7-9b0c-13cc65852a5f.png)
   if(v.object.type != "news"){
            //console.log("load directory element !",v.object.id);
            var html = directory.showResultsDirectoryHtml(new Array(v.object), v.object.type);
            $("#newsActivityStream"+v.object.id).html(html);
          }

**Comment by clement59** [comment]
régression news plus de news.type == "news"

**Comment by Kgneo** [comment]
je comprend pas.
mais re-test voir si tu as toujours le pb, j'ai fais pas mal de correction

**Comment by clement59** [comment]
1 - Toutes les news ont disparus ... Il n'y a plus que des activityStream !
2 - Surlignage @mention avec lien disparu
3 - Modification texte undefined
4 - Suppression rien ne s'efface
5 - J'ai partagé une news privée (parler à ses membres et admin) de mon orga sur mon réseau ...
![capture d ecran de 2017-05-02 14-37-50](https://cloud.githubusercontent.com/assets/6576514/25617941/ff98faec-2f44-11e7-891d-121b01085e91.png)
6- Si je crée un projet autres d'un élément c'est l'élément qui crée et non le user
7 - Les filtres news scopisés ont resauté
8 - Niveau design - ActivityStream enlever btn link, enlever le type (bulle de couleur), mettre dans tout le cadre
9 - Mettre moins grand la timeline --- Mm si c'est blanc pour cette version on va vite y rajouter des chose (filtre tags, scope au scroll, brefs)
10 - News trop longue pas coupée
11 - Tags en bas - remonter en haut 
12 - j'avais écris un plug en js pour éviter que les news ne soient au même niveau à replugger
![capture d ecran de 2017-05-02 14-54-05](https://cloud.githubusercontent.com/assets/6576514/25618418/35264f46-2f47-11e7-8011-8fea03ccd001.png)
13 - A mon avis, il y a des bashs de donnée à prévoir ... ReferenceError: type is not defined[En savoir plus]

Voila pour un début de liste

**Comment by Kgneo** [comment]
si t'avais mis à jour avant de testé t'aurais évité une dizaine de bug...

**Comment by clement59** [comment]
J'ai toujours type undefined sur le live... Du coup, je peux pas tester le live!
Par contre, pour les fil d'actus ça a l'air de bien fonctionner 
Pour le partage, j'enleverai la fonctionnalité sur les news de type privé comme ça on est cohérent avec nos scope ... 
Les tags aussi je les remettrais au dessus
Et pour le design des activityStream je l'ai raprocherai du design d'avant (si possible) je le trouve plus cohérent pour des news

**Comment by clement59** [comment]
ok ma poule je ferme pour du spécifique
