### ISSUE TITLE
Résultats dans CO vs GeoSSE

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#906]
J'ai pleins de résultats sur la map de [GeoSSE](http://apps.socioeco.org/geosse/) alors qu'il y en a que 6 dans Communecter...

![capture du 2018-05-09 13-07-16](https://user-images.githubusercontent.com/2474636/39806236-70d4c9ec-538a-11e8-9f5e-7123ac8f8b03.png)
---
![capture du 2018-05-09 13-07-32](https://user-images.githubusercontent.com/2474636/39806250-78b597fe-538a-11e8-84cc-85889ced182b.png)

**Comment by JulienLecaille** [comment]
Là c'est juste des résultats en 67200

![strasbourg](https://user-images.githubusercontent.com/19620144/39817933-de5fab66-539f-11e8-9e3d-5ca15c5b8c62.JPG)

**Comment by JulienLecaille** [comment]
![image](https://user-images.githubusercontent.com/19620144/39818171-9244f686-53a0-11e8-839d-de92b58cff49.png)

**Comment by Drakone** [comment]
C'est en lien avec cette histoire d'arrondissement ? #473

**Comment by JulienLecaille** [comment]
Pas nécessairement des arrondissements, plutôt des zones postales différentes sur une même commune. Les codes postaux sont parfois des fractions de communes, et parfois des regroupement de communes

**Comment by clement59** [comment]
Je ferme en faite elle est résolue celle-là ... @Drakone c'est juste que tu t'es focus sur strasbourg avec un 67200 et du coup si tu cliques sur strasbourg tu as tous les résultats ...
Dans ce usecase, strasbourg posséde plusieurs code postaux (pas exactement des quartiers mais tout comme) c'est une découpe géographique spécifique au grande ville.
C'est similaire au cas de Lille ou là les codes postaux ont même des noms différents (59260 == Hellemmes Lille, 59000== Lille, 59800 == Eurallille, et 59100[jesuis plus sur du code exact]==LOMME)
Voila si c'est bon pour toi, on close
