### ISSUE TITLE
Bug : Recherche : bouton recherche

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#914]
le bouton recherche agit comme si on change de page dans une pagination 

faire une recherche "alter" par exemple.

![capture d ecran de 2018-05-15 15-09-42](https://user-images.githubusercontent.com/8775448/40053414-38793fac-5852-11e8-91df-597950fb288b.png)
 et cliqué sur le boutton : 
![capture d ecran de 2018-05-15 15-09-46](https://user-images.githubusercontent.com/8775448/40053428-42d97016-5852-11e8-8898-20422582345d.png)

le resultat va changer a chaque fois jusqu'a ne plus en avoir

**Comment by clement59** [comment]
ah ouais sympa ;)
C'est pour moi !!

**Comment by Drakone** [comment]
Lé bon
