### ISSUE TITLE
Bug : ajout d'une Association

### ISSUE THREAD

**Issue by dagobertstyle** [pixelhumain/co2#915]
Bonjour, j'ai voulu créer une page pour mon Association. Elle est créée, mais je ne peux rien modifier, comme si elle avait été créée par quelqu'un d'autre que moi. Du coup, j'en ai créée une seconde, mais cela fait pareil.
Il faut dire que pour ces deux création , j'ai fini par cliquer sur "Annuler", étant donné que le cercle de chargement tournait en boucle sans fin (plusieurs minutes).

**Comment by RaphaelRIVIERE** [comment]
@dagobertstyle  j'ai corrigé le problème. Lors de l'ajout d'une association, le type de l'organisation n'était pas définie.

Vous pouvez normalement acceder aux pages des associations que vous avez crée. Il faudra sûrement redéfinir le type de l'organisation en "association". 

Merci pour vos retours. N'hésité pas si vous avez d'autres problèmes

**Comment by dagobertstyle** [comment]
C'est OK.
