### ISSUE TITLE
Bug: le "+" en bas à droite ne fonctionne pas

### ISSUE THREAD

**Issue by dagobertstyle** [pixelhumain/co2#929]
Le "+" vert en bas à droite ne fonctionne que pour "inviter quelqu'un".

**Comment by RaphaelRIVIERE** [comment]
Yep , je l'ai vu et corriger se matin. On viens de mettre a jour le site , du coup sa devrait etre bon

**Comment by dagobertstyle** [comment]
Yep, c'est tout bon!
