### ISSUE TITLE
Bug sur le btn de fermeture "X" de la carto (générale)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#93]

**Comment by Kgneo** [comment]
? sur quelle page ?
moi ça à l'air de bien marcher

**Comment by RaphaelRIVIERE** [comment]
@clement59 avec des images ou une explications ça n'aurez pas était du luxe

@Kgneo quand tu ouvre un dynForm et que tu le ferme via le X en haut a droite, il y a un décalage qui se fais sur la droite. plus tu ouvre et ferme le dynform , plus le décalage grandi 
Ici normale : 
![capture d ecran de 2017-05-03 08-47-03](https://cloud.githubusercontent.com/assets/8775448/25648491/873a01c4-2fdd-11e7-9602-5031bdb63129.png)

Après la première fermeture : 
![capture d ecran de 2017-05-03 08-47-25](https://cloud.githubusercontent.com/assets/8775448/25648496/9ad9c00c-2fdd-11e7-8c03-afd7bbd567bd.png)

Après trois fermetures : 

![capture d ecran de 2017-05-03 08-47-48](https://cloud.githubusercontent.com/assets/8775448/25648499/a3fc957e-2fdd-11e7-966b-f5b0bc34b9bb.png)

**Comment by clement59** [comment]
Biene good for me
