### ISSUE TITLE
Titre form pas bon - Edition de la description short description

### ISSUE THREAD

**Issue by clement59** [pixelhumain/co2#933]
![capture d ecran de 2018-05-18 11-10-30](https://user-images.githubusercontent.com/6576514/40226519-283fbd6e-5a8c-11e8-99cc-ca3051eb06f6.png)

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2018-05-22 10-17-52](https://user-images.githubusercontent.com/8775448/40345225-6b715a78-5da9-11e8-9820-c482f0174b10.png)
On dirais que sa était corrigé
