### ISSUE TITLE
search où , ajouter sg il se peut par defaut

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#941]
![image](https://user-images.githubusercontent.com/192076/40357951-c9b66428-5dce-11e8-9ca2-458f3f9f69a3.png)

ce serait bien de toujours mettre le msg il se peut qu'il n'existe rien sur cette zone ..

**Comment by clement59** [comment]
![capture d ecran de 2018-05-22 13-00-28](https://user-images.githubusercontent.com/6576514/40358678-5b082f10-5dc0-11e8-8c8c-69564c5f8b54.png)
