### ISSUE TITLE
invite sur une orga

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#942]
mes contacts > je selectionnes une liste > j'ajoutes > ca passe niquel  
je me dis merde j'ai oublier qlqun
je reclick sur mes contact > je click un contact > je revois toute la liste qui vient d'etre ajouter 
elle n'est pas vider post invite process
------------------------------------------------------------------
si je suis sur la page communauté, et ou invité 
apres avoir invité, il faudrait un reload 
------------------------------------------------------------------

**Comment by clement59** [comment]
le point 1 est duplicated #911

**Comment by RaphaelRIVIERE** [comment]
je close vus que tu la déjà signaler dans l'autre
