### ISSUE TITLE
Ressources : sous catégorie en double.

### ISSUE THREAD

**Issue by Boomti** [pixelhumain/co2#950]
![screenshot from 2018-05-28 11-13-19](https://user-images.githubusercontent.com/39181697/40601995-3aa39f00-6268-11e8-8a6d-2fe795183029.png)
Comme vous pouvez le voir il y a deux fois Soins des Animaux une fois à la 2ème colonne ligne 4 et une fois à la dernière ligne  de la 2ème colonne

**Comment by clement59** [comment]
Yes merci ! Justement corriger semaine dernière ! Arrivera avec la prochaine version
