### ISSUE TITLE
Ping dans publication

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#951]
Celui là il est bien sympa.

Quand j'ouvre [ce message](https://www.communecter.org/#page.type.news.id.5b0d522640bb4e8a6cfd1fc9) seul il n'y a pas de soucis.
Mais dans le journal le lien vers le profil de jérome est cassé.
![peek 29-05-2018 15-15](https://user-images.githubusercontent.com/2474636/40661211-742a7988-6353-11e8-944b-0099abcaceeb.gif)

Je pense que c'est parce qu'il est à cheval avec "Lire la suite" mais faudrait tester.

**Comment by clement59** [comment]
Yes c'est exactement ça !! Pareil pour une url glaglagla ! Je m'étais déjà bien cassé les crocs dessus ! Greuh grueh merci pour le rappel :)
