### ISSUE TITLE
Évènement introuvable

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#955]
J'ai référencé un évènement en normandie mais il ne s'affiche pas dans l'agenda...
https://www.communecter.org/#@lesMascarets

![screenshot-2018-5-30 reseau societal citoyen](https://user-images.githubusercontent.com/2474636/40718560-c1f5cf92-6410-11e8-8b90-a8c2402de5cd.png)

**Comment by Drakone** [comment]
Autant pour moi. Je propose une amélioration du coup :

En bas de page proposer d'aller au mois suivant

**Comment by clement59** [comment]
Yes en amélioration du coup pourquoi pas quand on prendra le chantier agenda du coup ;) I close here
