### ISSUE TITLE
Photo de profil non reprise dans la liste des invités

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#960]
![capture d ecran_2018-06-04_16-08-43](https://user-images.githubusercontent.com/2474636/40922164-cee5ae70-6811-11e8-8c2f-fdf8da05ba85.png)

Et en passant : ce serait possible de réduire la taille du champs des rôles et de l'aligner sous la photo de profil ou sous la croix) ?

**Comment by RaphaelRIVIERE** [comment]
corriger sur dev

**Comment by Drakone** [comment]
OK pour moi
