### ISSUE TITLE
Partage de lien Communecter sur Communecter

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#967]
Il y aurait moyen de récupérer l'image de l'élément plutôt que l'arbre de Communecter ?

![capture d ecran_2018-06-10_10-58-18](https://user-images.githubusercontent.com/2474636/41200015-4b006538-6c9d-11e8-902a-dcb2586799f7.png)

**Comment by Drakone** [comment]
Up up up ça me semble important. @pixelhumain/organisation

**Comment by clement59** [comment]
c'est pas bon ça ?

**Comment by clement59** [comment]
ah mince ca le fait pas avec les slugs !
![capture d ecran de 2018-11-05 09-08-05](https://user-images.githubusercontent.com/6576514/47985578-5ea27e80-e0da-11e8-861a-f6941bb1a4f5.png)

**Comment by Drakone** [comment]
Yeah ça c'est cool !
