### ISSUE TITLE
Modification slug évènement

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#968]
J'ai pas accès à l'interface permettant de modifier le slug des RMLL : https://www.communecter.org/#@rencontresMondialesDuLogicielLibre2018

**Comment by clement59** [comment]
tu l'as as ça ?
![capture d ecran de 2018-07-23 10-42-04](https://user-images.githubusercontent.com/6576514/43066511-27462698-8e65-11e8-9b14-a9b01c1e6286.png)

**Comment by Drakone** [comment]
![capture d ecran_2018-07-23_10-50-22](https://user-images.githubusercontent.com/2474636/43066941-534c3eca-8e66-11e8-9102-c971e7d036a3.png)

**Comment by Drakone** [comment]
Ah bah c'est bon j'étais pas admin.
