### ISSUE TITLE
nos valeurs > fini de remplir > pas de reload

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/co2#97]

**Comment by oceatoon** [comment]
et au refresh , ya pas nos datas

**Comment by clement59** [comment]
?? meuha ??

**Comment by clement59** [comment]
Sur quel form? quel type ? pour un element sans chart ?

**Comment by clement59** [comment]
ya déjà une issue je vire cette issue dessus

**Comment by oceatoon** [comment]
screen shot montre le form commun

**Comment by clement59** [comment]
ya pas de screenshot :P
