### ISSUE TITLE
Lancer l'invitation

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#970]
Il se passe rien à l'image quand je clique sur "Lancer les invitations".
Pourtant la personne est belle et bien invitée.

![capture d ecran_2018-06-11_10-14-13](https://user-images.githubusercontent.com/2474636/41220077-7a482cb8-6d60-11e8-86d8-12ca69733f45.png)

![capture d ecran_2018-06-11_10-15-59](https://user-images.githubusercontent.com/2474636/41220079-7c28e856-6d60-11e8-97e3-ec5fd8213697.png)

**Comment by RaphaelRIVIERE** [comment]
Vieux bug , déjà corriger je close
