### ISSUE TITLE
Le lien ne fonctionne pas correctement en italien

### ISSUE THREAD

**Issue by scoid** [pixelhumain/co2#971]
Le lien vers la documentation ne fonctionne pas correctement à partir de l'italien.
https://www.communecter.org/co2#docs.page.welcome.dir.it

**Comment by clement59** [comment]
![capture d ecran de 2018-06-14 15-28-39](https://user-images.githubusercontent.com/6576514/41414935-a2969a68-6fe7-11e8-82ff-89eff96d0741.png)
