### ISSUE TITLE
Plusieurs ping dans un même message

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#972]
![peek 14-06-2018 09-33](https://user-images.githubusercontent.com/2474636/41397940-0cc0a30c-6fb6-11e8-920f-8918a4a285e8.gif)

![capture d ecran_2018-06-14_09-33-55](https://user-images.githubusercontent.com/2474636/41397957-1603d952-6fb6-11e8-9411-3b6208314d84.png)

**Comment by clement59** [comment]
aaaaaaaaaaaah excellent merci @Drakone ! Je vais essayer de me faire une session fix cette aprem

**Comment by clement59** [comment]
J'ai corriger le deuxième pour le premier j'ai aucune solution vlan une aprem pour rien ! haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa x'(

**Comment by clement59** [comment]
Ok cette fois ci fais toi plaisir l'ami ! @Drakone 
Il me reste un mini usecase (le plus dur techniquement à régler) mais je vais éviter de trop trainer ... Ca fait déjà 1jour et demi que je suis dessus ;)
