### ISSUE TITLE
erreur lors de la saisie d'adresse

### ISSUE THREAD

**Issue by Boomti** [pixelhumain/co2#979]
Je rencontre un petit problème lors de la saisie d'adresse au niveau de la ville, il faut absolument taper le nom de ville au complet exemple:
si je pour la ville je tape tampon dans la drop bar il m'affichera erreur.
![screenshot from 2018-06-20 10-12-23](https://user-images.githubusercontent.com/39181697/41640365-93b7e47c-7472-11e8-82e6-3c931c8be385.png)
Tandis que si je tape le tampon, la ça fonctionne.
![screenshot from 2018-06-20 10-14-30](https://user-images.githubusercontent.com/39181697/41640401-c43b1fa6-7472-11e8-881a-acf28457bace.png)

**Comment by Drakone** [comment]
Pour cet exemple c'est bon.
