### ISSUE TITLE
[Recherche] Passage d'une app à une autre

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#985]
Le champs recherche ne reprend pas le contenu. C'est déroutant.

![peek 27-06-2018 13-48](https://user-images.githubusercontent.com/2474636/41972015-c3722b34-7a10-11e8-8a43-938a69297091.gif)

**Comment by clement59** [comment]
Je l'ai corrigé ce matin sur dév
Je le mets sur master de suite
