### ISSUE TITLE
Impossible de publier !

### ISSUE THREAD

**Issue by Drakone** [pixelhumain/co2#997]
J'ai ajouté de nombreux lieux à cette publication je ne sais pas si ça a un rapport...

![peek 31-07-2018 17-04](https://user-images.githubusercontent.com/2474636/43468351-0619a8fc-94e4-11e8-9df7-36e216f293b0.gif)

**Comment by clement59** [comment]
Yes c'est effectivement dans les scopes @Drakone !

@RaphaelRIVIERE c'est pour toi .... j e t'ai mis l'erreur console ci dessous 
![capture d ecran de 2018-08-01 08-37-55](https://user-images.githubusercontent.com/6576514/43505207-7f45f848-9566-11e8-856d-acdd92dba227.png)

**Comment by RaphaelRIVIERE** [comment]
c'est fais :)
